### ISSUE TITLE
--share stopped working..

### ISSUE THREAD

**Issue by ne0ark** [sivel/speedtest-cli#100]
Hello,

I am getting http://www.speedtest.net/result/0.png instead of actual share URL.

-N

**Comment by sivel** [comment]
Cannot reproduce.  This is working in devel

**Comment by bourgeois** [comment]
I am also getting this result when I'm on a very fast connection.

Here is the output:

    Retrieving speedtest.net configuration...
    Retrieving speedtest.net server list...
    Testing from LeaseWeb B.V. (5.79.77.75)...
    Selecting best server based on latency...
    Hosted by fdcservers.net (Amsterdam) [2.87 km]: 2.956 ms
    Testing download speed........................................
    Download: 3159.37 Mbit/s
    Testing upload speed..................................................
    Upload: 541.30 Mbit/s
    Share results: https://www.speedtest.net/result/0.png

Is this a known limitation on their end (maybe to prevent people from generating fake results ?)

As a proof, here is the actual output from the SSH session.
![](http://i.imgur.com/5DhPfML.png)

Here is now the result when I try from a server much farther away (so I can get slower speeds). We can now see that it is working.

    Retrieving speedtest.net configuration...
    Retrieving speedtest.net server list...
    Testing from LeaseWeb B.V. (5.79.77.75)...
    Hosted by TIM Brasil (Rio de Janeiro) [9579.58 km]: 227.944 ms
    Testing download speed........................................
    Download: 32.00 Mbit/s
    Testing upload speed..................................................
    Upload: 4.49 Mbit/s
    Share results: https://www.speedtest.net/result/4222206614.png

![](http://i.imgur.com/KBMU4kM.png)

**Comment by djh00t** [comment]
I also get the same result on low latency, high speed servers.

```
root@ord-af0cbfe80941ec72:~# speedtest-cli --share --server 13425 --source 103.79.4.241
Retrieving speedtest.net configuration...
Testing from Ordnance Networks Pty (103.79.4.241)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by IP Transit (Sydney) [1.20 km]: 2.095 ms
Testing download speed................................................................................
Download: 2498.11 Mbit/s
Testing upload speed................................................................................................
Upload: 1894.17 Mbit/s
Share results: http://www.speedtest.net/result/0.png
root@ord-af0cbfe80941ec72:~#
```
