### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by gdhgdhgdh** [sivel/speedtest-cli#102]
Since the raw output is all now redirected to https://raw.githubusercontent.com/username/path/to/file, you need to add `-L` to the commandline for `curl` at https://github.com/sivel/speedtest-cli#just-download-like-the-way-it-used-to-be to follow `Location:` redirect headers.

..or just link to `https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest_cli.py` instead :)

Thanks for a beautifully compact way of using speedtest.net without a fat web browser and Flash!

Cheers,
Gavin.

**Comment by sivel** [comment]
Updated in devel, will soon be released.
