### ISSUE TITLE
Ping is way off

### ISSUE THREAD

**Issue by anfedorov** [sivel/speedtest-cli#116]
pi@raspberrypi ~ $ speedtest --server 1749 --simple
    Ping: 45.59 ms
    ^C
    Cancelling...
    pi@raspberrypi ~ $ ping -c10 speedtest.monkeybrains.net
    PING speedtest.monkeybrains.net (208.69.40.37) 56(84) bytes of data.
    64 bytes from speedtest.monkeybrains.net (208.69.40.37): icmp_req=1 ttl=60 time=4.64 ms
    64 bytes from speedtest.monkeybrains.net (208.69.40.37): icmp_req=2 ttl=60 time=5.33 ms
    64 bytes from speedtest.monkeybrains.net (208.69.40.37): icmp_req=3 ttl=60 time=6.88 ms
    64 bytes from speedtest.monkeybrains.net (208.69.40.37): icmp_req=4 ttl=60 time=9.11 ms
    64 bytes from speedtest.monkeybrains.net (208.69.40.37): icmp_req=5 ttl=60 time=8.03 ms
    64 bytes from speedtest.monkeybrains.net (208.69.40.37): icmp_req=6 ttl=60 time=8.79 ms
    64 bytes from speedtest.monkeybrains.net (208.69.40.37): icmp_req=7 ttl=60 time=11.2 ms
    64 bytes from speedtest.monkeybrains.net (208.69.40.37): icmp_req=8 ttl=60 time=6.46 ms
    64 bytes from speedtest.monkeybrains.net (208.69.40.37): icmp_req=9 ttl=60 time=8.56 ms
    64 bytes from speedtest.monkeybrains.net (208.69.40.37): icmp_req=10 ttl=60 time=5.18 ms

    --- speedtest.monkeybrains.net ping statistics ---
    10 packets transmitted, 10 received, 0% packet loss, time 9013ms
    rtt min/avg/max/mdev = 4.643/7.421/11.211/1.980 ms

**Comment by anfedorov** [comment]
no comment?

**Comment by dorth** [comment]
Just an observer here, but you might want to look at the readme section on inconsistency (https://github.com/sivel/speedtest-cli#inconsistency)  which I think will explain the lack of any comment.

"Latency reported by this tool should not be relied on as a value indicative of ICMP style latency. It is a relative value used for determining the lowest latency server for performing the actual speed test against."

"Issues relating to inconsistencies will be closed as wontfix and without additional reason or context."

**Comment by anfedorov** [comment]
Good call, thanks!
