### ISSUE TITLE
DNS resolve affects speed tests

### ISSUE THREAD

**Issue by 0xAF** [sivel/speedtest-cli#117]
Here is a result from speedtest-cli with OpenDNS (88.198.154.18), which is very slow sometimes...
```
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from XXX (xxx.xxx.xxx.xxx)...
Selecting best server based on latency...
Hosted by XXX [87.02 km]: 2532.407 ms
Testing download speed........................................
Download: 8.07 Mbits/s
Testing upload speed..................................................
Upload: 2.19 Mbits/s
```

here is with my ISP's DNS:
```
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from XXX (xxx.xxx.xxx.xxx)...
Selecting best server based on latency...
Hosted by XXX [87.02 km]: 27.983 ms
Testing download speed........................................
Download: 28.57 Mbits/s
Testing upload speed..................................................
Upload: 5.04 Mbits/s
```

The test server is the same...
I've tried this multiple times -> same result... with slow dns it shows low speed.

**Comment by sivel** [comment]
Neither python nor speediest-cli will cache the DNS results.  So for every connection, there will need to be a DNS lookup.  If the DNS queries are slow, this will impact speed measurements.

Consider using something like nscd to cache DNS queries.

**Comment by 0xAF** [comment]
I see, thanks for explaining and sorry for disturbing.
