### ISSUE TITLE
Cannot retrieve speedtest configuration

### ISSUE THREAD

**Issue by f5nerd** [sivel/speedtest-cli#118]
Hello, i use speedtest_cli in version 0.3.1. If i starton cli 

![2015-01-07 11_49_35-speedtest_cli_ connot retrieve speedtest configuration - plugins - monitoring-po](https://cloud.githubusercontent.com/assets/10433798/5644388/48edb304-9663-11e4-8d49-d97347a3c6f6.png)

If i try 
"wget -O testdatei-config.php http://www.speedtest.net/speedtest-config.php" the file is download. My Nagios is behind a proxy. 

Have you any ideas?
Greets

**Comment by xlash** [comment]
version 0.3.1 now uses the following url : http://www.speedtest.net/speedtest-servers-static.php

However, I have the issue with version 0.2.6 & version 0.3.1.

**Comment by f5nerd** [comment]
Thank you for feedback!

>> version 0.3.1 now uses the following 
>> url : http://www.speedtest.net/speedtest-servers-static.php
>> However, I have the issue with version 0.2.6 & version 0.3.1.

but i use version 0.3.1. In row 308 i can read "uh = urlopen('http://speedtest.net/speedtest-config.php')" and in row 345 i can read "uh = urlopen('http://www.speedtest.net/speedtest-server-static.php')". What can i do

**Comment by sivel** [comment]
This is fixed in devel. Release coming soon
