### ISSUE TITLE
Add support for pingtest.net

### ISSUE THREAD

**Issue by nedark** [sivel/speedtest-cli#125]
Hello, i love your tools and i was thinking that it would be great to include support for latency tests, using the speedtest.net sister webpage. 

As they says its useful to test connection quality for videogames, voip, streaming, etc- which "require more than just raw speed"

**Comment by nedark** [comment]
Closed without explanation..... ?

**Comment by sivel** [comment]
Not interested. Pretty sure things like the "ping" command are functional for this form of work.

Otherwise a new tool is appropriate as this is designed for testing speed.

**Comment by nedark** [comment]
I thought i would be easy to add support to pingtest.net if they use similar interfaces
Of course ping commands would be enough if you want to test against a fixed server/ip. My point is automatic selecting of best server based on location - like your tool does with speedtest.net. 
Maybe I can use the same server selected by the script and then run a custom ping command against it
The key parameters to calculate are jitter, packet loss and latency. 
Ok, you can close if not interested
