### ISSUE TITLE
Create a speedtestlib package

### ISSUE THREAD

**Issue by NotANormalNerd** [sivel/speedtest-cli#129]
Hey,

I really appreciate your work, but I would be really glad if you could somehow provide an API or a *lib package for others to use and build own tools.

Maybe you can also incooperate pingtest.

I would really like to build a webapp, to deploy on my homeserver and monitor my Internetconnection over a longer time. A speedtest api or *lib would really help me on that.

Thanks for your work

Greetings

**Comment by Chen-Huanyi** [comment]
+1

**Comment by archcorsair** [comment]
I also +1 this.

**Comment by sivel** [comment]
I had made an attempt about a year ago, and I didn't like the way it turned out.  I will attempt this again, but I cannot commit to when.
