### ISSUE TITLE
Is there a plan for a cloud based logger?

### ISSUE THREAD

**Issue by fedex1** [sivel/speedtest-cli#131]
(I've also created a pull request for this) see https://github.com/sivel/speedtest-cli/pull/130

I've installed speedtest-cli

Thanks.

I wonder if there is a plan for a cloud based logger

I created a little script that converts the output to CSV format

```
#! 
/usr/local/bin/speedtest-cli | awk '
BEGIN {
print "date,latency_ms,download_mbits_per_sec,upload_mbits_per_sec"
line = ""
}

/:/ {
# print $0
 line = line $(NF-1)  ","
}

END {
"date +'%Y-%m-%dT%H:%M:%S'"|getline date;
	print date ", " line
}' > $HOME/log/speedtest_log_macbook_pro.csv

```

then upload to bigquery

And the real time results with moving averages and standard deviation etc are available here:

http://speed-test-app.appspot.com/getdata

Sample output:

![table] (https://raw.githubusercontent.com/civic-data/speedtest-cli/master/logger/Screen%20Shot%202015-02-03%20at%2010.59.20%20PM.png)
```
ending_at_day	average_download	std__download	average_upload	std__upload	average_latency	std__latency	c
16469	32	11	24	3	21	3	1
16468	39	15	24	4	21	3	1
16467	28	12	24	3	24	8	1
16466	11	11	20	5	28	9	1
date	download_mbits_per_sec	upload_mbits_per_sec	latency_ms
2015-02-03 22:32:33	17.93	25.54	29.872
2015-02-03 21:32:27	20.79	15.78	25.724
2015-02-03 20:32:31	44.03	22.87	22.284
```

**Comment by sivel** [comment]
I'm not currently interested in this functionality. Thanks

**Comment by fedex1** [comment]
Okay Thanks for the reply

**Comment by Tux** [comment]
The perl version https://github.com/Tux/speedtest supports CSV output. Just add a cron job to collect the data

**Comment by fedex1** [comment]
Wow, thanks and will try it now.
