### ISSUE TITLE
0 Upload speed

### ISSUE THREAD

**Issue by vajonam** [sivel/speedtest-cli#137]
I am trying to run this through a OpenVPN VPN tunnel. From the regular network everything is okay through the VPN it shows a 0 upload speed.

my VPN address is 10.x.x.166 that I am binding to.

```bash
vdr@dvr:~$ speedtest-cli --source 10.x.x.166 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Amanah Tech (184.75.214.163)...
Selecting best server based on latency...
Hosted by TekSavvy Solutions (Toronto, ON) [1.99 km]: 8.108 ms
Testing download speed........................................
Download: 44.24 Mbit/s
Testing upload speed..................................................
Upload: 0.00 Mbit/s
```

Any ideas? all other traffic through the VPN works fine. I am guessing the "urls" in the upload method have something to w/ this. is there somewhere I can start looking to debug, once I find the problem I can do a PR, just need a pointer on where to start looking.

**Comment by sivel** [comment]
That would seem to indicate that all POST requests for the upload functionality failed.

**Comment by vajonam** [comment]
Turned out be an issue with OpenVPN "mssfix" settings, the POST packet packet was too big and wasn't getting through the tunnel and wouldn't get fragmented. playing around with the mssfix settings seems to have fixed it. i use a setting of 

```mssfix 1300```
