### ISSUE TITLE
Speedtest.net configuration fetching is broken on v0.3.2 and Python 2.7.9

### ISSUE THREAD

**Issue by pvalkone** [sivel/speedtest-cli#138]
```
$ speedtest --version
0.3.2
$ speedtest
Retrieving speedtest.net configuration...
Could not retrieve speedtest.net configuration
$ python --version
Python 2.7.9
```

Apparently certificate validation has been enabled by default in [Python 2.7.9](http://lwn.net/Articles/611243/), and this breaks the fetching of the speedtest.net configuration.

If certificate validation is disabled by applying the following quick and dirty fix, the program works as expected:

```
194,195d193
<     import ssl
<
197,200c195
<         ctx = ssl.create_default_context()
<         ctx.check_hostname = False
<         ctx.verify_mode = ssl.CERT_NONE
<         uh = urlopen(request, context = ctx)
---
>         uh = urlopen(request)
```

**Comment by sivel** [comment]
I'm not sure that I want to disable the security benefits of SSL because the openssl configuration and associated ca bundle isn't functional on the system where this script is run.

Maybe I can add another flag to disable verification, but for now I'm not sure how I would want to address this.

**Comment by jstarcher** [comment]
Workaround worked for me. Thanks.

Cheers, J

**Comment by sivel** [comment]
This is resolved in the current released version
