### ISSUE TITLE
Could not retrieve speedtest.net configuration - version 0.3.2

### ISSUE THREAD

**Issue by Venopsis** [sivel/speedtest-cli#142]
![speedtest](https://cloud.githubusercontent.com/assets/949573/6761728/50c08080-cf56-11e4-9e15-a88caa40c589.PNG)
Hello,

I open this ticket because I don't know why but I'm not able to retrieve the configuration file to do a speedtest. On my VMWare server it works properly but on my VPS it doesn't work. I think that the problem become because on my VPS it's a CentOS Minimal instead of Desktop version for my VMWare server.
Could you help me please because I don't find the solution on the web  and I'm disappointed :/

Thx to read me.

**Comment by sivel** [comment]
Can you provide the puthon version and the OS and version you are running on?

**Comment by Venopsis** [comment]
Linux CentOS 6.6 (Final)
Kernel release 2.6.32-042stab093.5

Python v 2.6.6. Upgrade to 2.7.9 required?

Other informations needed?

**Comment by Venopsis** [comment]
Hello,
Do you have a solution or the begin of a solution?

**Comment by Venopsis** [comment]
I just retried with the version 0.3.1 and it works correctly. The only thing who doesn't work properly is when I cancel the operation. I've got an exception but it's always possible to launch it again after this cancel.
Since you find a solution, I downgrading to the previous version 0.3.1

**Comment by Venopsis** [comment]
okay same problem with previous version. It seams that the problem is on my server. Do you have an idea? There is something I'll authorize into the firewall for example?

**Comment by sivel** [comment]
I am not sure.  I have not been able to duplicate your issue.

**Comment by colby-swandale** [comment]
I have encountered this issue when i installed it from pip on a fresh freeBSD installation.
Platform: FreeBSD storage 10.1-RELEASE FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 21:02:49 UTC 2014     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
Version: Python 2.7.9

I am not a python developer so let me know what (if any and preferably how) debug you need.

**Comment by Venopsis** [comment]
Hello, @colby-swandale.

Thx to send us your feedback. I hope that @sivel could find a solution to our problem.
The same for me about the informations, if you want more, just tell it to me. I give them with pleasure if it can help.

**Comment by sivel** [comment]
I've begun adding debug information to failure scenarios in the devel branch.  I would recommend starting with the devel branch add seeing how far that gets us:

https://raw.githubusercontent.com/sivel/speedtest-cli/devel/speedtest_cli.py

**Comment by farnoy** [comment]
```
➜  ~  python2 speedtest_cli.py 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Failed to retrieve list of speedtest.net servers:

 HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found
HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found
```

**Comment by ashishkumar** [comment]
Same problem with me.

OS X 10.10.3
Python 2.7.6
Installed via Homebrew

![screen shot 2015-04-09 at 11 18 59](https://cloud.githubusercontent.com/assets/1743699/7063831/442b8a6e-deaa-11e4-82f6-b9ff3a7dea3f.png)

**Comment by akhepcat** [comment]
This occurs even when specifying a specific server:

./speedtest_cli.py --server 1555
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Failed to retrieve list of speedtest.net servers:

 HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found
HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found

**Comment by akhepcat** [comment]
the old version (.21)  uses a different URL
"http://www.speedtest.net/speedtest-servers.php"

if you add this URL  to the list at the top of  closestServers()

        urls = [
            'http://www.speedtest.net/speedtest-servers.php',
            'https://www.speedtest.net/speedtest-servers-static.php',
            'http://c.speedtest.net/speedtest-servers-static.php',
        ]

then things magically start working again.

**Comment by Venopsis** [comment]
Hello, I try again after adding the url line but it doesn't fix my problem. I don't have exactly the same problem than you if you look correctly.
Your problem is you can't retrieve the server list but in my case it's the speedtest.net configuration that I can't retrieve. It's different from your problem.

I'll try with the dev branch to look if it's good with this. I send you my feedback after.

**Comment by Venopsis** [comment]
I just tried with the devel branch and I have this message:
![speedtest_cli_dev](https://cloud.githubusercontent.com/assets/949573/7085408/c2994946-df76-11e4-95df-be1d7a8ac54d.JPG)

**Comment by sivel** [comment]
> the old version (.21) uses a different URL
> "http://www.speedtest.net/speedtest-servers.php"

`http://www.speedtest.net/speedtest-servers.php` is a 302 redirect for `https://c.speedtest.net/speedtest-servers-static.php` which is already in the list, so I'm not sure why that would make things work.

**Comment by sivel** [comment]
> I just tried with the devel branch and I have this message:

@Venopsis: it sounds like you have some issue with using HTTPS on your machine.  I am looking into adding an `--insecure` option that would use all `http` URLs instead of `https`. I think I have decided that using https but ignoring errors isn't a good approach, so just reverting back to http is probably a good possibility.

**Comment by sivel** [comment]
Please give the `no-https` branch a try and see if it resolves your issues:

https://raw.githubusercontent.com/sivel/speedtest-cli/no-https/speedtest_cli.py

**Comment by Venopsis** [comment]
Hello @sivel,

I'll try it as I can. Normally max two or three days to wait. I'll give you my feedback immediately after try it.

**Comment by Venopsis** [comment]
Hello,
I finally try with the no-https branch and it always not work :/

**Comment by sivel** [comment]
What does "always not work" actually mean?  Did you get any specific errors?

And no, that is not the issue, I have tested on el6 without a problem.

**Comment by akhepcat** [comment]
the speedtest no-https  works fine for me.

Oddly, the original script is now working today, so it may have been a temporary issue.  

Got to love those.

**Comment by Venopsis** [comment]
Hello, 
When I said "always not work"  it's about the previous version 0.3.2 and the devel branch. About the errors it's always the same that at the beginning: impossible to retrieve... 

I thanked also that's certainly a probleme with my server and hoped you could help me. I disable the firewall and some others services to try but I don't find a solution. When I use the https the document root is not the good one. For example,  I set /var/www/domain/vhosts/... but finally the path used is /var/www/html/
Do you think that could be in correlation with my probleme about speedtest? Openssl could be not working correctly on my server and create some problems.

**Comment by Alberts00** [comment]
Also not working for me, getting 302, when running the no-https branch

```python2.7 speedtest_cli.py.1
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Failed to retrieve list of speedtest.net servers:

 HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found
HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found```

**Comment by sivel** [comment]
I've made another small update to the `no-https` branch to include a change to use a "better" user-agent, which others have mentioned helps.

https://raw.githubusercontent.com/sivel/speedtest-cli/no-https/speedtest_cli.py

See if that improves anything.

Also, please provide the output when reporting whether or not it helps.

**Comment by akhepcat** [comment]
latest no-https branch works fine in HTTP mode:

> ./speedtest_cli-b4.py  
Retrieving speedtest.net configuration...  
Retrieving speedtest.net server list...  
Testing from GCI Communications (localhost)...  
Selecting best server based on latency...  
Hosted by GCI (Anchorage, AK) [13.68 km]: 22.857 ms  
Testing download speed........................................  
Download: 35.64 Mbit/s  
Testing upload speed..................................................  
Upload: 6.88 Mbit/s  

And testing in HTTPS (--secure) mode:  
> ./speedtest_cli-b4.py --secure  
Retrieving speedtest.net configuration...   
Retrieving speedtest.net server list...  
Testing from GCI Communications (localhost)...  
Selecting best server based on latency...  
Hosted by GCI (Anchorage, AK) [13.68 km]: 17.291 ms  
Testing download speed........................................  
Download: 37.96 Mbit/s  
Testing upload speed..................................................  
Upload: 6.58 Mbit/s  

Now i just need to figure out why speedtest.net  is so far off in terms of reporting my bandwidth:

> betterspeedtest.sh | grep -i load:  
Download:  245 mb/s  
     Upload:  10 mb/s

**Comment by Venopsis** [comment]
Hello @sivel,

You will hate me but I changed nothing and suddenly it works perfectly -_-'
So I can close this ticket and pray for it continue like this.

Thanks to try to help me ;) 

--
Cordially, Venopsis.

**Comment by adambranicki** [comment]
CENTOS 6.6
speedtest ver. 0.3.2
Change line 343 in the script
https
to
http
Voilà :)

**Comment by teknogeek** [comment]
Yes! Thank you @adambranicki works perfect now. +1

**Comment by aloksinha2001** [comment]
Sivel,
I have been having the same problem - intermittently.

Interestingly... the probability of receiving the error when running on command line is about 3-4%

However, the probabilty of generating this error when running via cron --> shell -> script is actually 80-90%, meaning about 9 of 10 times it fails.

I have test this on
  - no-https version
  - devel version
  - and initially I had installed using apt-get install 
  - I am running Linux Mint 17.2 (same problem reported on 17 and 17.1)
 - This is the no-https version detail g8usa lo # speedtest-cli --version
0.3.3a

Can you please help.

**Comment by aloksinha2001** [comment]
Forgot to mention
I use specific server id
G8_MSG=$(speedtest-cli --simple --timeout 45 --server 982)

Here is the error report

Speed test for USA Server (982) Time Stamp : 17-Aug-2015 16:24:04 hrs EDT
Failed to retrieve list of speedtest.net servers:

 HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found
HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found


Speed test for Singapore Server (367) Time Stamp : 17-Aug-2015 16:24:06 hrs EDT
Failed to retrieve list of speedtest.net servers:

 HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found
HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found


Speed test for India Server (4156) Time Stamp : 17-Aug-2015 16:24:07 hrs EDT
Failed to retrieve list of speedtest.net servers:

 HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found
HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found

**Comment by palibaacsi** [comment]
I initially got an error like 

`Failed to retrieve list of speedtest.net servers:`

Rebooted machine and worked great!

**Comment by aloksinha2001** [comment]
Reboot should not have solved the problem - we have it running on several systems... reboots are normal... the problem still persists.

**Comment by jaggedsoft** [comment]
If anyone else gets this problem, download https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
Then run `python speedtest.py`
Works great :)

**Comment by menqgingyu** [comment]
https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
python speedtest.py
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: HTTP Error 404: Not Found
  

why?
