### ISSUE TITLE
ImportError: No module named http.client

### ISSUE THREAD

**Issue by moneypenny** [sivel/speedtest-cli#145]
In OS X Yosemite:

```
% wget -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest_cli.py
% chmod +x speedtest-cli
% speedtest-cli -h
Traceback (most recent call last):
  File "/Users/me/bin/speedtest-cli", line 55, in <module>
    from http.client import HTTPConnection, HTTPSConnection
ImportError: No module named http.client
% python --version
Python 2.7.3
```

**Comment by sivel** [comment]
That is interesting.  Sounds like you have a broken python install somehow.

I imagine it is actually a result of not being able to import `HTTPSConnection` from `httplib`.

I've just pushed some debug output functionality to the devel branch.  Give it a try and see what error is reported:

https://raw.githubusercontent.com/sivel/speedtest-cli/devel/speedtest_cli.py

**Comment by moneypenny** [comment]
I'd believe it! I couldn't get easy_install or pip to install speedtest-cli either, which is why I resorted to the wget/chmod route. With your new script:

```
% speedtest-cli -h
Your python installation is missing required HTTP client classes:

Python 2: cannot import name HTTPSConnection
Python 3: No module named http.client
```

**Comment by moneypenny** [comment]
So no worries about debugging my weird installation. I'll probably reinstall stuff via brew and see if I can't fix it. I'm guessing this isn't a problem speedtest-cli needs to handle. Thanks!
