### ISSUE TITLE
Speedtest.net don't like the speedtest-cli user agent.

### ISSUE THREAD

**Issue by mikkeloscar** [sivel/speedtest-cli#146]
I was getting the errors:

```
HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
```

Which resulted in the speedtest-cli error:

```
Failed to retrieve list of speedtest.net servers
```

Turns out this only happens when using the default `speedtest-cli/%version%` user agent string. If I use anything else, it works fine, so it looks like speedtest.net is trying to "block" this tool.

**Comment by sivel** [comment]
I cannot replicate this behavior. Perhaps you could replicate and figure out what the location header specifies in the 302.

**Comment by mikkeloscar** [comment]
You are right, I think it is me they don't like. I have queried speednet quite regularly for a long time, so they must have blocked me. It works fine from another location.
