### ISSUE TITLE
0 mbit/s Upload speed

### ISSUE THREAD

**Issue by dakky** [sivel/speedtest-cli#148]
Hello

I get wrong values when testing my upload speed:

```
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from M-net Telekommunikations GmbH (188.x.x.x)...
Selecting best server based on latency...
Hosted by süc//dacor GmbH (Coburg) [173.67 km]: 33.899 ms
Testing download speed........................................
Download: 11.16 Mbit/s
Testing upload speed..................................................
Upload: 0.00 Mbit/s
```
I tried different setups:
* windows/cygwin
* Mac Yosemite
* Ubuntu
* debian

All with the same result.
Any Idea whats wrong? How can i debug this any further?

greetings

**Comment by sivel** [comment]
Does this help at all?  https://github.com/sivel/speedtest-cli/issues/137#issuecomment-78623413

**Comment by dakky** [comment]
Nope. I Don't use any kind of VPN.
Just plain PC => switch => router => internet.

I don't see anything, which might limit the POST request size.

**Comment by Axel-Erfurt** [comment]
I have the same problem, but only in Windows 7. OSX is OK.

**Comment by xiconet** [comment]
Same problem here, with WindowsXPsp3 and Python 2.7

**Comment by zizof** [comment]
Same problem with Windows 7 and Ptython 2.5.1
Test OK with OSX

There is no solution ?

**Comment by sebastien-bratieres** [comment]
Same here. Python 3.4.3. Windows 8. speedtest-cli 0.3.4. Sporadically (around 50% of time) getting upload speed 0.00 Mbit/s.
