### ISSUE TITLE
Default server list not returning all servers

### ISSUE THREAD

**Issue by neilgierman** [sivel/speedtest-cli#149]
I noticed that when I ran the script the local AT&T and Google Fiber servers are not listed. When I use the Flash test at speedtest.net, they are there. In looking at the network traffic, when the flash version pulls http://c.speedtest.net/speedtest-servers-static.php it passes the parameter "threads=4". When I do that, all of the servers are returned. Also I needed to put that URL as the first URL in the script and now everything works for me.

**Comment by sivel** [comment]
That is interesting.  I cannot seem to duplicate that.  Whether I supply the threads or not, it returns the same server list.  I'll see if I can do some more testing.  As long as I can validate that speedtest.net does sent that query arg, I can add it regardless.

**Comment by Anmavi** [comment]
It would be interesting that you could fix the script, for people who do not know programming.
Thank you for your work.

**Comment by sivel** [comment]
Can you test with https://raw.githubusercontent.com/sivel/speedtest-cli/threadsperurl/speedtest_cli.py and see if that resolves your issue?
