### ISSUE TITLE
Run against a specific server without downloading the full server list.

### ISSUE THREAD

**Issue by SimplGy** [sivel/speedtest-cli#150]
`speedtest-cli --list` times out a lot. I'm in Vietnam, so my connection is rough sometimes, but I figure that's when this tool is most useful.

I'm writing a little bash script to results into a `csv` file on every test run so you can see at a glance wifi network name, speed, date of test and so on. It tries to hit a server in San Francisco so that it tests the cross-pacific connection speed.

`speedtest-cli --server 5754` is cool, but it always tries to download the server list before running the actual test, and this often times out. That isn't so cool.

Is there a way to run the test against a specific server without downloading the whole server list? Is this what the `--source` option is for? It's not explained in the docs, and nowhere is the IP for server 5754 printed.

Here's the bash script, in case you're interested in what I'm up to:

```bash
date="$(date +"%Y-%m-%d")"
time="$(date +"%l:%M%p")"
dest=5754
destination="San Francisco [$dest]"
# Split a string at the delimeter 'Network ' into variables 1, 2, etc.
wifi=`networksetup -getairportnetwork en0 | awk -F'Network: ' '{printf $2}'`
outputFile=~/Desktop/sf-speedtest-output.csv

# -------------------------------------------- Say what we're about to do
echo "$wifi --> $destination"
echo "Running speedtest-cli..."

# -------------------------------------------- Start the Test
# Run a command, printing to stdout while it runs, but also saving the output to a variable
exec 5>&1
output=$(speedtest-cli --server $dest | tee >(cat - >&5))

# Parse the output for useful data
down=`echo "$output" | awk -F'Download: ' '{printf $2}'`
down=`echo "$down" | awk -F' ' '{printf $1}'`
up=`echo "$output" | awk -F'Upload: ' '{printf $2}'`
up=`echo "$up" | awk -F' ' '{printf $1}'`
ping=`echo "$output" | awk -F'km]: ' '{printf $2}'`
ping=`echo "$ping" | awk -F' ms' '{printf $1}'`
echo "Speeds: $down/$up mbps. Ping: $ping ms."


# -------------------------------------------- Save to File
# File Format: wifi, downspeed, upspeed, date, time, destination, ping
echo "$wifi,$down,$up,$date,$time,$destination,$ping" >> $outputFile
echo "Test results saved to $outputFile"
```

**Comment by sivel** [comment]
Currently there is no way to not pull the full server list.  When you specify a single server we still need the server list to output information about that server.  Speediest.net does not provide a way to get details about only a single server.

Also `--source` is listed in the `--help` output as `Source IP address to bind to`.

**Comment by SimplGy** [comment]
Yes, obviously I've read that, both in `--help` and in README.md. What is a source IP address? is this a server?

**Comment by SimplGy** [comment]
I can pull a server IP from the web gui of speedtest but if I drop it in to the source command:

    speedtest-cli --source 116.98.140.243 // Could not retrieve speedtest.net configuration

Bupkis

**Comment by sivel** [comment]
The source is where the speedtest originates from which would be where you run this script from.  It allows you to test on different interfaces on your machine.  It has nothing to do with speedtest.net servers.
