### ISSUE TITLE
Error encoding data from --list

### ISSUE THREAD

**Issue by twitteried** [sivel/speedtest-cli#154]
No prior experience with Python 3 here, but I just noticed that while running this on ArchLinux (which uses Python 3.4 as default), I get the following error:

Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/speedtest_cli.py", line 593, in speedtest
    unicode()
NameError: name 'unicode' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/speedtest", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/speedtest_cli.py", line 758, in main
    speedtest()
  File "/usr/lib/python3.4/site-packages/speedtest_cli.py", line 596, in speedtest
    print_('\n'.join(serverList))
UnicodeEncodeError: 'ascii' codec can't encode character '\xed' in position 34806: ordinal not in range(128)

**Comment by sivel** [comment]
This is not a python3.4 issue.  It just happens that there was a problem encoding the data to be printed to the screen.

**Comment by sivel** [comment]
See if this branch helps:

https://raw.githubusercontent.com/sivel/speedtest-cli/always-encode/speedtest_cli.py

**Comment by twitteried** [comment]
Yep. That worked! Thanks for the assistance and the general explanation.

**Comment by pe1mew** [comment]
Today i found that my script was failing. The branch seems to solve thr problem here too.

**Comment by sivel** [comment]
This branch has, as of earlier today, been merged in the devel branch.  The next step is a merge to master.
