### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by gregtampa** [sivel/speedtest-cli#156]
:~# python speedtest-cli/setup.py install
Traceback (most recent call last):
  File "speedtest-cli/setup.py", line 22, in <module>
    from setuptools import setup
ImportError: No module named setuptools

**Comment by sivel** [comment]
The installer requires setuptools.  Install python-setuptools if you want to use the installer.  Otherwise just copy down the speedtest_cli.py file.

**Comment by chovy** [comment]
How do I install python-setuptools?
