### ISSUE TITLE
Only tests from eth0 interface when two interfaces are being used.

### ISSUE THREAD

**Issue by HaniKali** [sivel/speedtest-cli#157]
I am using Kali linux and SSH over LAN on a static ip (with no internet on the interface) And using a wifi adapter to connect and speedtest different AP's. 

It gives me the following error:

root@kali:~# ./speedtest-cli
Retrieving speedtest.net configuration...
Could not retrieve speedtest.net configuration

If I forward internet to my ethernet interface then it works fine example below but only tests eth0 connection regardless of which AP i am using with wifi interface.

./speedtest-cli
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from TPG Internet (xxxxxxxxxxxxx)...
Selecting best server based on latency...
Hosted by UberGlobal (xxxxxxxx) [7.10 km]: 129.057 ms
Testing download speed........................................
Download: 4.09 Mbit/s
Testing upload speed..................................................
Upload: 0.79 Mbit/s

Why is it unable to speedtest when I turn off internet on eth0 interface and connect to wifi? I dont have a monitor and mouse attached but will test the script on wlan interface without SSH and post my findings. Maybe it is an issue on my side.

UPDATE: With only the wlan interface connected and directly sitting infront of terminal I was able to speedtest successfully on wlan interface.

But the issue remains, It wont work when two interfaces are connected or will give preference to the eth0 interface

thanks

**Comment by sivel** [comment]
It sounds like you have a OS configuration issue in that your default gateway is incorrectly set when using both interfaces.

However you can use the `--source` argument to get it to use the proper interface. That option takes an IP address and should be the IP of the interface you want to use when testing.

**Comment by bladebeam** [comment]
For others who had this issue, I found the fix after dozens of hours of trial and error.  You have to set the default gateway to one interface or the other, using "sudo route add default gw x.x.x.x".  Speedtest-cli will not be able to use --source to set the interface unless that interface is the default gateway.
