### ISSUE TITLE
Slow download speed on router

### ISSUE THREAD

**Issue by wbtf** [sivel/speedtest-cli#160]
This utility outputs slower download speeds than on a Tomato Firmware based router. 

I am not sure if it is because of the Python version running on the router but I get about half of the download speed when I run it on the router (Python 2.5.6) vs my computer (Python 2.7.6).

Router:
Download: 56.06 Mbps
Upload:  9.18 Mbps

Computer:
Download: 90.22 Mbps
Upload 9.47 Mbps

Note: Only download speeds seems to be affected.

Any idea how I can troubleshoot this?

**Comment by sivel** [comment]
https://github.com/sivel/speedtest-cli/blob/master/README.rst#inconsistency
