### ISSUE TITLE
allow to choose gateway 

### ISSUE THREAD

**Issue by mRdebugginHammer** [sivel/speedtest-cli#161]
Hello sivel,

speedtest-cli is great as it is, but it would be even more awesome if you could add a way to choose another gateway for the test. Do you think it's possible to add an option to specify the desired gateway?

Kind regards,
MrHammer

**Comment by sivel** [comment]
Generally speaking the `--source` argument should allow for this, as it allows you to specify the IP of the interface you want to use.  This app cannot influence routing, so routing would have to be handled some place external.
