### ISSUE TITLE
Can't get share image

### ISSUE THREAD

**Issue by KR2615** [sivel/speedtest-cli#168]
speedtest-cli --share
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from X (IP)...
Selecting best server based on latency...
Hosted by Y (CIty) [1.07 km]: 1.616 ms
Testing download speed........................................
Download: 2004.05 Mbit/s
Testing upload speed..................................................
Upload: 268.99 Mbit/s
Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 794, in <module>
    main()
  File "/usr/local/bin/speedtest-cli", line 788, in main
    speedtest()
  File "/usr/local/bin/speedtest-cli", line 783, in speedtest
    scheme, resultid[0])
TypeError: not enough arguments for format string

**Comment by alesnav** [comment]
I have just publish a fix for devel branch. Hope it helps.

**Comment by KR2615** [comment]
Works fine, thanks :)
