### ISSUE TITLE
Git install stuck to "writing entry points to speedtest_cli.egg-info/entry_points.txt"

### ISSUE THREAD

**Issue by hista** [sivel/speedtest-cli#170]
Hi, I'm trying to install speedtest-cli according to the wiki:
git clone https://github.com/sivel/speedtest-cli.git
python speedtest-cli/setup.py install

But it stays stuck for hours to:
python speedtest-cli/setup.py install
running install
running bdist_egg
running egg_info
writing speedtest_cli.egg-info/PKG-INFO
writing top-level names to speedtest_cli.egg-info/top_level.txt
writing dependency_links to speedtest_cli.egg-info/dependency_links.txt
writing entry points to speedtest_cli.egg-info/entry_points.txt

How can I fix it?

Best regards

**Comment by sivel** [comment]
This could be any number of things.  It's not specifically related to this project but more of a system or pythons related issue.

Maybe try stracing the install or something similar.

**Comment by hista** [comment]
Thanks for your quick answer.
Could you please explicit what do you mean by stracing the install?

**Comment by hista** [comment]
Well, I've strace the install, it seems to be block on a loop, any idea why?
> stat("./.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/locale/fr/LC_MESSAGES", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
openat(AT_FDCWD, "./.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/locale/fr/LC_MESSAGES", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
getdents(3, /* 3 entries */, 32768)     = 88
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
stat("./.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/locale/fr/LC_MESSAGES/hidetopbar.mo", {st_mode=S_IFREG|0664, st_size=1087, ...}) = 0
stat(".teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/locale/fr/LC_MESSAGES/hidetopbar.mo", {st_mode=S_IFREG|0664, st_size=1087, ...}) = 0
openat(AT_FDCWD, "./.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.teamviewer/7/drive_c/users/rm/Mes documents/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/locale/zh_CN", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
getdents(3, /* 3 entries */, 32768)     = 80
