### ISSUE TITLE
Failed to retrieve list of speedtest.net servers: - comes again intermittently

### ISSUE THREAD

**Issue by aloksinha2001** [sivel/speedtest-cli#171]
have been having the same problem - intermittently.

Interestingly... the probability of receiving the error when running on command line is about 3-4%

However, the probabilty of generating this error when running via cron --> shell -> script is actually 80-90%, meaning about 9 of 10 times it fails.

I have tested this on

no-https version
devel version
and initially I had installed using apt-get install
I am running Linux Mint 17.2 (same problem reported on 17 and 17.1)
This is the no-https version detail g8usa lo # speedtest-cli --version 0.3.3a
Can you please help.

Forgot to mention
I use specific server ids (this is just an example)
G8_MSG=$(speedtest-cli --simple --timeout 45 --server 982)

Here is the error report

Speed test for USA Server (982) Time Stamp : 17-Aug-2015 16:24:04 hrs EDT
Failed to retrieve list of speedtest.net servers:

HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found
HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found

**Comment by sivel** [comment]
Closing as a duplicate. I saw your comment on the other issue.
