### ISSUE TITLE
Using speedtest on specific device (Enhancement)

### ISSUE THREAD

**Issue by aloksinha2001** [sivel/speedtest-cli#172]
It would be wonderful, if we can embed the feature of device (eth0, eth1 or wlan0) to be used as default device for speed test.

There are multiple devices (eth0 and eth1) connected from two different ISPs
There are times, when the VPN is also on. (ppp0)

It would be nice, to be able to connect via specific device, while doing speed test.

Possible ?

**Comment by sivel** [comment]
This is already possible by passing the IP of the interface to the `--source` argument.
