### ISSUE TITLE
Failed to retrieve list of speedtest.net servers

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [sivel/speedtest-cli#174]
I've opened a new issue because #155  is closed. I found that this error only occurs on the second execution on the same day. I guess Speedtest is blocking connections on the second request from the same device. This doesn't occur with this node js client. https://github.com/sindresorhus/speed-test 
Perhaps that helps..

**Comment by sivel** [comment]
Please test with the current devel version: https://raw.githubusercontent.com/sivel/speedtest-cli/devel/speedtest_cli.py

**Comment by CalumJEadie** [comment]
I've been able to replicate the issue with the current master version and get correct behaviour with the current devel version.

```
$ wget -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest_cli.py

Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Failed to retrieve list of speedtest.net servers

$ wget -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/devel/speedtest_cli.py

Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from TalkTalk (...)...
Selecting best server based on latency...
Hosted by UK Broadband/PCCW (Ealing) [28.42 km]: 57.241 ms
Testing download speed........................................
Download: 14.48 Mbit/s
Testing upload speed..................................................
Upload: 0.49 Mbit/s

```

**Comment by sivel** [comment]
Sounds good to me.  I'll look at releasing devel soon.
