### ISSUE TITLE
Install via pip on Ubuntu Mate (Arm) does not make executable available

### ISSUE THREAD

**Issue by codecowboy** [sivel/speedtest-cli#180]
I installed speedtest-cli via pip on Ubuntu Mate 15.04 on a Raspberry Pi 2. Python version is 2.7. ```sudo pip install speedtest-cli``` ran successfully but if I try ```speedtest-cli``` or ```speedtest``` at the terminal, I get : 

```
speedtest-cli
The program 'speedtest-cli' is currently not installed. You can install it by typing:
sudo apt-get install speedtest-cli
```
I'm not a python developer so don't really want to mess around with python versions. Should this 'just work' or am I missing something?

**update**

I realised that it got installed in ```/home/codecowboy/.local/bin``` but would still like to understand why

**Comment by sivel** [comment]
That would be due to pip configuration.  Perhaps a mate thing?
