### ISSUE TITLE
About manpage installation

### ISSUE THREAD

**Issue by david-geiger** [sivel/speedtest-cli#183]
Hi Matt,

I see that a man file is present, would it be possible to integrate installation directly into the setup.py?

Something like that:

![capture d ecran2](https://cloud.githubusercontent.com/assets/4344460/10014465/aef4ce5e-6119-11e5-872d-73f86aeeb4da.png)

Best regards David

**Comment by sivel** [comment]
I'm not interested in installing the man page when used as a standard Python install. It is only there for OS package managers that have it as a requirement for packaging.
