### ISSUE TITLE
 HTTP Error 401: Authorization Required

### ISSUE THREAD

**Issue by smartpandian** [sivel/speedtest-cli#184]
I was getting  "HTTP Error 401: Authorization Required" in a corp network, Command line option to pass the username and password as argument.. enhance the speedtest-cli in corp network.
![image](https://cloud.githubusercontent.com/assets/10723978/10046315/13e44170-61d6-11e5-8673-409000b70525.png)

**Comment by sivel** [comment]
Python should be able to automatically handle this via the `http_proxy` environment variable.  Specific changes to speedtest-club will not be made to accept user/pass for a proxy.
