### ISSUE TITLE
302 error

### ISSUE THREAD

**Issue by uotw** [sivel/speedtest-cli#185]
I'm getting this error on both of my ubuntu servers.  Does  cookie need to be set? [http://stackoverflow.com/questions/4098702/python-urllib2-urlopen-returning-302-error-even-though-page-exists]
![screen shot 2015-09-24 at 12 03 35 pm](https://cloud.githubusercontent.com/assets/14109479/10078771/5edfc60c-62b4-11e5-84ad-3f0c8c548579.png)

**Comment by sivel** [comment]
Please provide a version.  Your traceback was insufficient as to see any code operating within this app.  This should be fixed in the current release.

**Comment by uotw** [comment]
Version 0.2.4
![screen shot 2015-09-24 at 12 10 17 pm](https://cloud.githubusercontent.com/assets/14109479/10078944/54a8db5a-62b5-11e5-8a99-e4d01e5d71c1.png)

**Comment by sivel** [comment]
That is not the most recent version of speedtest-cli.  The current version is 0.3.4.  Please upgrade.
