### ISSUE TITLE
speedtest Download: 0.00 Mbit/s Upload: 0.00 Mbit/s

### ISSUE THREAD

**Issue by juige** [sivel/speedtest-cli#186]
Hi all, 

I run speedtest on an embedded linux board. But got 0 speed due to the IOError when doing urlopen.
Does anyone have suggestion? Thanks~

<urllib2.Request instance at 0x958a48>
.Exception in thread Thread-89:
Traceback (most recent call last):
  File "/apps/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "speedtest_cli.py_mod", line 288, in run
    f = urlopen(self.url)
  File "/apps/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/apps/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/apps/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/apps/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/apps/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/apps/lib/python2.7/urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11] Resource temporarily unavailable>

**Comment by sivel** [comment]
Please try on the recently released 0.3.4

**Comment by juige** [comment]
Hi sivel,

Thanks for reply.

I make a workaround on 0.3.4. During setting source IP, I use the blocking socket. And It works fine now.

def bound_socket(*args, **kwargs):
    """Bind socket to a specified source IP address"""

    global source
    sock = socket_socket(*args, **kwargs)
    sock.setblocking(1)
    sock.bind((source, 0))
    return sock

**Comment by sivel** [comment]
That is odd that adding `sock.setblocking(1)` did anything.  The default is that new sockets are blocking:

https://docs.python.org/2/library/socket.html#socket.socket.setblocking

> Initially all sockets are in blocking mode.

Seeing as though that is the default, I suppose there is no harm in also setting it explicitly.  I'll look into that.

**Comment by sivel** [comment]
Please test with the recently released v1.0.0.
