### ISSUE TITLE
--sources does not work with IPv6

### ISSUE THREAD

**Issue by MPW1412** [sivel/speedtest-cli#187]
Hello,

on IPv6 only networks, --source [ipv6] does not work:

    Could not retrieve speedtest.net configuration: <urlopen error [Errno -9] Address family for hostname not supported>

**Comment by sivel** [comment]
speedtest.net does not support IPv6.

https://support.speedtest.net/hc/en-us/articles/203845430-Does-Speedtest-net-support-IPv6-
