### ISSUE TITLE
Witch ports speedtest_cli use for testing ?

### ISSUE THREAD

**Issue by peterpt** [sivel/speedtest-cli#196]
I have a restrict iptables rules witch drop every input except the ones that i allow on iptables , when i test speedtest_cli with iptable activated , i get 500K/s down and 500k/s up  , but if i drop iptables rules i get 14M/s down and 800k/s up .
so this must e related with the ports that speedtest_cli is using .

**Comment by sivel** [comment]
tcp/80 and tcp/443

**Comment by peterpt** [comment]
Thanks .
