### ISSUE TITLE
Update Speedtest CLI on homebrew to 0.3.4

### ISSUE THREAD

**Issue by shsu** [sivel/speedtest-cli#200]
Currently the version installed by homebrew is `0.3.2`
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/speedtest_cli.rb

**Comment by sivel** [comment]
I do not manage the homebrew formula for speedtest-cli.  In addition I fundamentally disagree with installing python applications via homebrew, and as such do not support that as any form of official installation method.
