### ISSUE TITLE
Option to select interface for speedtest

### ISSUE THREAD

**Issue by carestad** [sivel/speedtest-cli#201]
Hi

Would it be possible to add a --interface argument or something to the script, to route the speedtest traffic through a specified interface? The --source doesn't necessarily work, for example on a system where the default gateway is used by all interfaces, without the exception of a few IP address that will be passed through eth1, eth2 and so on.

**Comment by sivel** [comment]
The method of binding to an interface in python is to bind to an IP address on a specific interface.  I am not aware of another way to achieve this.
