### ISSUE TITLE
Suitable to test 300 Mbit/s download speed ?

### ISSUE THREAD

**Issue by 262media** [sivel/speedtest-cli#206]
All my tests always give under 100 Mbit/s results but using other tools i can get to 280 Mbit/s

**Comment by sivel** [comment]
I cannot duplicate.  On my 320 Mbit/s connection:

```
Testing download speed........................................
Download: 189.57 Mbit/s
```

Depending on time of day and such, I expect these results.

Also see https://github.com/sivel/speedtest-cli#inconsistency

**Comment by 262media** [comment]
Thank you

**Comment by amac16** [comment]
I get pretty consistent results over 800Mb/s in a data center on 0.3.2.
