### ISSUE TITLE
Failed to parse list of speedtest.net servers

### ISSUE THREAD

**Issue by jason-utilityapi** [sivel/speedtest-cli#214]
Having this issue a lot lately.

```Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Failed to parse list of speedtest.net servers```

**Comment by sivel** [comment]
What version of speedtest-cli?

**Comment by jason-utilityapi** [comment]
0.3.1 - just did pip install --upgrade

**Comment by sivel** [comment]
0.3.1 is not the current version.  0.3.4 is the current version.  Please upgrade and validate.

**Comment by jason-utilityapi** [comment]
OK. Likely a version issue with python (multiple installs). Thanks
