### ISSUE TITLE
Move ping time to separate line

### ISSUE THREAD

**Issue by taismi** [sivel/speedtest-cli#217]
Hello

Could you move the ping time to separate line?

Now speedtest-cli prints:
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from XXXX (xxx.xxx.xxx.xxx)...
Hosted by Brandl Services GmbH (Pavelsbach) [1940.63 km]: 57.347 ms
Testing download speed........................................
Download: 10.31 Mbit/s
Testing upload speed..................................................
Upload: 10.60 Mbit/s

I would like to speedtest-cli to print like this:
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from XXXX (xxx.xxx.xxx.xxx)...
Hosted by Brandl Services GmbH (Pavelsbach) [1940.63 km]
Ping: 57.347 ms
Testing download speed........................................
Download: 10.31 Mbit/s
Testing upload speed..................................................
Upload: 10.60 Mbit/s

Now ping, download and upload syntax would match --simple option:
Ping: 57.347 ms
Download: 10.31 Mbit/s
Upload: 10.60 Mbit/s

**Comment by sivel** [comment]
I cannot as this changes what people have come to expect.
