### ISSUE TITLE
Issue with --share option

### ISSUE THREAD

**Issue by jmmadrid** [sivel/speedtest-cli#219]
Hi! 
I just built the speedtest-cli utility using the pip tool for Python 2.7 on windows. 
Installation went good, but I am having problems with the "--share" option. 
Everytime I run "speedtest-cli --share" the output I got looks like: 

"Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Movistar Chile (201.223.233.10)...
Selecting best server based on latency...
Hosted by Entel (Santiago) [395.34 km]: 195.726 ms
Testing download speed........................................
Download: 1.38 Mbit/s
Testing upload speed..................................................
Upload: 0.00 Mbit/s
Share results: http://www.speedtest.net/result/0.png"

Then I go to the URL and the image looks  like this : 
![connect_output_0](https://cloud.githubusercontent.com/assets/8238763/12080600/767370b4-b23e-11e5-972d-c303ed7073f3.png) 

Am I just not using the tool properly ?

**Comment by sivel** [comment]
I'm going to have to assume it is due to the upload speed being 0.

In any case I don't have much insight into that API.  If it works it works.  It's more of a nice to have.
