### ISSUE TITLE
Very different upload speeds from cli vs. UI across multiple runs hitting the same server

### ISSUE THREAD

**Issue by dogeared** [sivel/speedtest-cli#221]
The results below are against the same server in Garden City, NY (id `6166`). 

All 10 tests were done within (roughly) 5 minutes of each other, one at a time.

```
Download: 57.19 Mbit/s
Upload: 35.93 Mbit/s

Download: 57.31 Mbit/s
Upload: 37.75 Mbit/s

Download: 56.59 Mbit/s
Upload: 24.12 Mbit/s

Download: 56.53 Mbit/s
Upload: 39.21 Mbit/s

Download: 57.17 Mbit/s
Upload: 37.85 Mbit/s
```

![image](https://cloud.githubusercontent.com/assets/364562/12455723/b2264eae-bf6a-11e5-9d9a-7634f875e022.png)

**Comment by sivel** [comment]
Per the README, this falls under inconsistencies.

The methods used by this script and speedtest.net are inherently different.

Of note I am working on a new branch, which can be found at https://github.com/sivel/speedtest-cli/pull/212 . Of interest in this branch is consistently better upload speeds.
