### ISSUE TITLE
error: can't start new thread

### ISSUE THREAD

**Issue by ax42** [sivel/speedtest-cli#222]
Running on an Asus ac87u with entware python (which is v2.7 as far as I can tell). 

``` ./speedtest-cli
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Cablecom GmbH (xxxxxxxxxxx)...
Selecting best server based on latency...
Hosted by GGA Maur (Binz) [19.25 km]: 14.5 ms
Testing download speed......Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./speedtest-cli", line 268, in producer
    thread.start()
  File "/opt/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
```

Completely understand if you won't fix this given the non-standard platform.  Happy to provide whatever details you would like if I can help fix it.

**Comment by sivel** [comment]
That's interesting.  I may indeed look into it.  I do some of my performance testing on a Asus RT-N66U running Python 2.7 from entware.  I've not run into that problem before.

**Comment by xpavli44** [comment]
use
ulimit -s  256
and it works (tested on Asus AC-68U) 
credits to http://stackoverflow.com/questions/33318304/python-cant-start-a-new-thread

**Comment by ax42** [comment]
Thanks.  Confirmed to work on ac87u as well (merlin firmware).

**Comment by myahmao** [comment]
met same issue on asuswrt-merlin firmware.

Testing download speed..............................Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/lib/python2.7/site-packages/speedtest_cli.py", line 268, in producer
    thread.start()
  File "/opt/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

looks merlin firmware has strict memory limitation than dd-wrt.
my solution is to decrease queue size for both download and upload threads.
