### ISSUE TITLE
speedtest vs speedtest-cli

### ISSUE THREAD

**Issue by SammysHP** [sivel/speedtest-cli#223]
The setup script installs two scripts, speedtest and speedtest-cli. Both do the same. Is there a reason for the two commands?

**Comment by sivel** [comment]
Fun

**Comment by SammysHP** [comment]
So one version will be removed? Great!

**Comment by demahum** [comment]
Since they do the same as I got it, it is my opinion as well that one of them should be removed.

**Comment by skywinder** [comment]
+
