### ISSUE TITLE
Socket Error Errno 104: connection reset by peer

### ISSUE THREAD

**Issue by ricardovianna** [sivel/speedtest-cli#224]
Hi,

I'm trying to run speedtest-cli on a SHMZ release 6.6 (Final), but I can't get to results. This is the error:

```
[root@furquilha-voip /]# speedtest-cli
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 796, in <module>
    main()
  File "/usr/bin/speedtest-cli", line 790, in main
    speedtest()
  File "/usr/bin/speedtest-cli", line 641, in speedtest
    servers = closestServers(config['client'])
  File "/usr/bin/speedtest-cli", line 436, in closestServers
    serversxml.append(uh.read(10240))
  File "/usr/lib64/python2.6/socket.py", line 383, in read
    data = self._sock.recv(left)
  File "/usr/lib64/python2.6/httplib.py", line 542, in read
    s = self.fp.read(amt)
  File "/usr/lib64/python2.6/socket.py", line 383, in read
    data = self._sock.recv(left)
socket.error: [Errno 104] Connection reset by peer
[root@furquilha-voip /]# 
```

Although, I am able to pull the servers lists by speedtest-cli --list

Full Linux version: SHMZ release 6.6 (Final) - 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux.

This distro comes with FreePBX.

Any help is appreciated!
Tks

**Comment by face0b1101** [comment]
I ran into this problem myself.

I found the script runs as expected if you stick a --secure onto the end.

Hope that helps.

**Comment by sinjin** [comment]
That's fantastic, will give it a bash, thanks!

**Comment by sivel** [comment]
This should be resolved in the latest release

**Comment by ubnt-kannan** [comment]
@sivel Could you please provide more information about the fix?
