### ISSUE TITLE
This test is not reliable at high speeds

### ISSUE THREAD

**Issue by virtuallynathan** [sivel/speedtest-cli#226]
Testing on a Comcast 250/25 connection (Provisioned around 300/30), as compared with various other speedtests. 

**speedtest-cli:**
Nathans-MacBook-Pro:~ virtuallynathan$ speedtest-cli --server 1769
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Comcast Cable (68.84.XXX.XXX)...
Hosted by Comcast (Plainfield, NJ) [92.80 km]: 24.155 ms
Testing download speed........................................
Download: 136.20 Mbit/s
Testing upload speed..................................................
Upload: 26.90 Mbit/s

**Speedtest.net**
Plainfield, NJ
Ping: 13ms
Down: 288Mbps
Up: 30Mbps
http://www.speedtest.net/result/5045175786.png 

**Speedtest.comcast.net**
Plainfield, NJ
Ping: 13ms
Down: 275Mbps
Up: 30Mbps
http://results.speedtest.comcast.net/result/1198333904.png 

**DSLReports**
Ping: 17ms
Down: 280Mbps
Up: 30Mbps
http://www.dslreports.com/speedtest/2841780.png 

See (1000 speedtests over a bit less than 24hrs): 
![screen shot 2016-02-01 at 9 14 57 am](https://cloud.githubusercontent.com/assets/3472173/12720281/008a9a62-c8c8-11e5-8382-2e5d9be1b0cc.png)

**Comment by virtuallynathan** [comment]
This is not a CPU/memory limitation

**Comment by virtuallynathan** [comment]
I read the README.md, but that states "This is not a reliable latency reporting tool". At the very least, please update it to state it is not a reliable measurement tool for speeds, or latency.

**Comment by sivel** [comment]
I'll get on that.
