### ISSUE TITLE
Raw bps and Bps output

### ISSUE THREAD

**Issue by q1x** [sivel/speedtest-cli#227]
To reuse the data from speedtest-cli in other tools, I'd like to have an option to output speeds in bps and Bps instead of kbps/Mbps/Gbps. 

This will make it easier to compare speeds in external monitoring tools.

**Comment by sivel** [comment]
This is already planned and implemented in another branch and will be part of the next major release.

See https://github.com/sivel/speedtest-cli/pull/212
