### ISSUE TITLE
Wrong upload values when using python3

### ISSUE THREAD

**Issue by baco** [sivel/speedtest-cli#231]
Using python3 to run the script computes no upload, returning always zero.

I add some output sample. I've added a raw print (without units computation) of the ``ulspeed`` value after the default script output:

    $ python speedtest_cli.py
    Retrieving speedtest.net configuration...
    Retrieving speedtest.net server list...
    Testing from Telecom Argentina S.A. (186.124.32.131)...
    Selecting best server based on latency...
    Hosted by Telecom Argentina (Cordoba) [34.42 km]: 48.004 ms
    Testing download speed........................................
    Download: 5.91 Mbit/s
    Testing upload speed..................................................
    Upload: 0.83 Mbit/s
    104273.198831

    $ python3 speedtest_cli.py
    Retrieving speedtest.net configuration...
    Retrieving speedtest.net server list...
    Testing from Telecom Argentina S.A. (186.124.32.131)...
    Selecting best server based on latency...
    b'Hosted by Telecom Argentina (Cordoba) [34.42 km]: 46.179 ms'
    Testing download speed........................................
    Download: 5.53 Mbit/s
    Testing upload speed..................................................
    Upload: 0.00 Mbit/s
    0.0

**Comment by baco** [comment]
The issue seems to happen in python 3.5 but no in 3.4.

**Comment by n0vember-** [comment]
same here : 

```
$ ./speedtest_cli.py --simple --server 4158
Ping: 35.768 ms
Download: 12.33 Mbit/s
Upload: 0.00 Mbit/s
$ python2 ./speedtest_cli.py --simple --server 4158
Ping: 36.219 ms
Download: 12.28 Mbit/s
Upload: 0.95 Mbit/s
$ python --version
Python 3.5.2
$ python2 --version
Python 2.7.12
```

Problem is the same with python 3.6 : 
```
$ python3.6 --version
Python 3.6.0b2
$ python3.6 ./speedtest_cli.py --simple --server 4158
Ping: 35.516 ms
Download: 12.29 Mbit/s
Upload: 0.00 Mbit/s
```
