### ISSUE TITLE
CPU at 100% with ksoftirqd/0 (Local timer interrupts)

### ISSUE THREAD

**Issue by Aikhjarto** [sivel/speedtest-cli#239]
I'm running speedtest-cli on an OpenSUSE 13.1 on a  Xeon L5506  2.13GHz with a 100 MBit/s Internet connection and Python 2.7.6.
speedtest-cli reports just a bit over 50 MBit/s download. Download with wget work with 100 MBit/s, so the internet connection seems fine. 

When speedtest-cli is running, the CPU is 100% occupied (viewed with 'top') with [ksoftirqd/0]. 
/proc/interrupts shows a significant increase of local timer interrupts.

So IMHO the maximum bandwidth is capped by [ksoftirqd/0] and not by the internet connection.

**Comment by Aikhjarto** [comment]
Additional info: The machine i ran speedtest-cli on had lots of iptable rules. Reducing the number of rules reduces also the load produced by [ksoftirqd/0] while speedtest-cli is running.

Interestingly only speedtest-cli is capping [ksoftirqd/0] to 100% CPU utilization.

**Comment by sivel** [comment]
Yes, as the readme states, CPU will play a large role in the speeds you can achieve.
