### ISSUE TITLE
--share not working when over 2000Mbps

### ISSUE THREAD

**Issue by Angristan** [sivel/speedtest-cli#241]
Hi, I see a bug when the download speed is over 2000mbps : the image link is http://www.speedtest.net/result/0.png

Proofs : 

```
root@scw-799166:~# speedtest-cli --server 4010 --share
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Free SAS (212.47.238.104)...
Hosted by LaFibre.info (Douai) [176.09 km]: 2.106 ms
Testing download speed........................................
Download: 2000.80 Mbit/s
Testing upload speed..................................................
Upload: 476.39 Mbit/s
Share results: http://www.speedtest.net/result/0.png

root@scw-799166:~# speedtest-cli --server=4010 --share
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Free SAS (212.47.238.104)...
Hosted by LaFibre.info (Douai) [176.09 km]: 2.133 ms
Testing download speed........................................
Download: 2035.18 Mbit/s
Testing upload speed..................................................
Upload: 462.38 Mbit/s
Share results: http://www.speedtest.net/result/0.png

root@scw-799166:~# speedtest-cli --share --server 4010
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Free SAS (212.47.238.104)...
Hosted by LaFibre.info (Douai) [176.09 km]: 2.252 ms
Testing download speed........................................
Download: 1996.12 Mbit/s
Testing upload speed..................................................
Upload: 408.84 Mbit/s
Share results: http://www.speedtest.net/result/5150873544.png

root@scw-799166:~# speedtest-cli --share --server 4010
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Free SAS (212.47.238.104)...
Hosted by LaFibre.info (Douai) [176.09 km]: 2.161 ms
Testing download speed........................................
Download: 1887.79 Mbit/s
Testing upload speed..................................................
Upload: 499.12 Mbit/s
Share results: http://www.speedtest.net/result/5150874251.png

```

**Comment by sivel** [comment]
Intriguing, although I don't know if this can be easily solved.  speedtest.net does not expose the inner workings of how to submit these API calls, so I don't really have any documentation to go on for how this might be resolved, assuming that it is even possible.

**Comment by OxLemonxO** [comment]
`Retrieving` speedtest.net configuration...
Testing from DigitalOcean (ip censored)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Citybridge (New York City, NY) [10.20 km]: 2.551 ms
Testing download speed................................................................................
Download: 2282.38 Mbit/s
Testing upload speed................................................................................................
Upload: 1599.23 Mbit/s
Share results: http://www.speedtest.net/result/0.png

Retrieving speedtest.net configuration...
Testing from DigitalOcean (ip censored)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Citybridge (New York City, NY) [10.20 km]: 2.831 ms
Testing download speed................................................................................
Download: 1741.68 Mbit/s
Testing upload speed................................................................................................
Upload: 1626.51 Mbit/s
Share results: http://www.speedtest.net/result/6309035195.png

Retrieving speedtest.net configuration...
Testing from DigitalOcean (ip censored)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Citybridge (New York City, NY) [10.20 km]: 2.662 ms
Testing download speed................................................................................
Download: 2219.94 Mbit/s
Testing upload speed................................................................................................
Upload: 1903.15 Mbit/s
Share results: http://www.speedtest.net/result/0.png
`` Yep..

**Comment by djh00t** [comment]
I get the same result

```
root@ord-af0cbfe80941ec72:~# speedtest-cli --share --server 13425
Retrieving speedtest.net configuration...
Testing from Ordnance Networks Pty (103.79.4.241)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by IP Transit (Sydney) [1.20 km]: 2.095 ms
Testing download speed................................................................................
Download: 2498.11 Mbit/s
Testing upload speed................................................................................................
Upload: 1894.17 Mbit/s
Share results: http://www.speedtest.net/result/0.png
root@ord-af0cbfe80941ec72:~#
```

**Comment by Octylpy** [comment]
A very first world problem, but same here.

```
Hosted by Race Communications (Los Angeles, CA) [2.73 km]: 1.783 ms
Testing download speed................................................................................
Download: 2294.62 Mbit/s
Testing upload speed................................................................................................
Upload: 1316.61 Mbit/s
Share results: http://www.speedtest.net/result/0.png
```

**Comment by ZordoPlayz** [comment]
Same here
`Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Strato AG (***.***.***.***)...
Selecting best server based on latency...
Hosted by SysEleven GmbH (Berlin) [1.13 km]: 1.703 ms
Testing download speed........................................
Download: 5445.60 Mbit/s
Testing upload speed..................................................
Upload: 99.74 Mbit/s
Share results: http://www.speedtest.net/result/0.png
`

**Comment by ZordoPlayz** [comment]
Nope still there
`Retrieving speedtest.net configuration...
Testing from Strato AG (85.214.62.175)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Interoute VDC (Berlin) [1.13 km]: 1.711 ms
Testing download speed................................................................................
Download: 4067.54 Mbit/s
Testing upload speed................................................................................................
Upload: 98.94 Mbit/s
Share results:  http://www.speedtest.net/result/0.png
`

**Comment by ZordoPlayz** [comment]
Nope still there.
```
Retrieving speedtest.net configuration...
Testing from Strato AG (***.***.***.***)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Interoute VDC (Berlin) [1.13 km]: 1.711 ms
Testing download speed................................................................................
Download: 4067.54 Mbit/s
Testing upload speed................................................................................................
Upload: 98.94 Mbit/s
Share results: http://www.speedtest.net/result/0.png
```
