### ISSUE TITLE
Download url via curl fails on OS X

### ISSUE THREAD

**Issue by jsejcksn** [sivel/speedtest-cli#244]
I tried downloading via `curl` in Terminal (per the [readme](https://github.com/sivel/speedtest-cli#just-download-like-the-way-it-used-to-be)):

```
curl -Lo speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest_cli.py
```

but the url did not resolve and it failed. I tried to curl again using the url below (which is the link accessible via the "Raw" button on [the file page](https://github.com/sivel/speedtest-cli/blob/master/speedtest_cli.py):

`https://github.com/sivel/speedtest-cli/raw/master/speedtest_cli.py`

It succeeded after that.

**Will someone else please test for confirmation?**

_(I'm using OS X 10.11.4)_

**Comment by sivel** [comment]
The `curl` command works as expected for me:

```
$ ls -1 speedtest-cli
ls: speedtest-cli: No such file or directory
$ curl -Lo speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest_cli.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24994  100 24994    0     0  64016      0 --:--:-- --:--:-- --:--:-- 64087
$ ls -1 speedtest-cli
speedtest-cli
```
