### ISSUE TITLE
Feature request: add an option to generate CSV output for logging internet performance from a cron job

### ISSUE THREAD

**Issue by lemmy04** [sivel/speedtest-cli#245]
I would like to see an option to generate CSV output which could be appended to a text file from cron.

**Comment by lemmy04** [comment]
You'll find two commits in https://github.com/lemmy04/speedtest-cli that implement this.

I'm new to python so please look them over and "make them right" if there's any bad shit in it.

**Comment by sivel** [comment]
This has already been added in the `modularize-2` branch that will become the the next major release.

**Comment by lemmy04** [comment]
..any ETA on that release?
