### ISSUE TITLE
Use only one binary

### ISSUE THREAD

**Issue by kbabioch** [sivel/speedtest-cli#246]
Currently there seem to be two binaries ("entry points"), namely `speedtest` and `speedtest-cli`. This is not only confusing, but also makes autocompletion in various shells cumbersome. If there is not a technical reason for those two binaries, we should get rid of one.

**Comment by sivel** [comment]
The reason is for historical purposes.  `speedtest-cli` was the original name and some expect it to be there.  Some complained that `cli` was redundant, so an alternative was added.

You can't always have your cake and eat it too.  Just going to have to deal with it.
