### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by WASasquatch** [sivel/speedtest-cli#248]
Having some issues installing on Debian Jessie. I tried through `apt-get` and that speedtest-cli would not obtain servers for best latency, just froze. Was hoping this would work. 

```
Traceback (most recent call last):
  File "speedtest-cli/setup.py", line 22, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```

**Comment by sivel** [comment]
In order to install this package you need setuptools, such as via `apt-get install python-setuptools`.  Or if you install via pip:

```
apt-get install python-pip
pip install speedtest-cli
```
