### ISSUE TITLE
How could I save only one command without remove the package

### ISSUE THREAD

**Issue by MrBowen** [sivel/speedtest-cli#258]
I installed your speedtest_cli with brew.
Now I has two commands for one speedtest_cli package.
They are speedtest_cli and speedtest-cli.

I like your package, but it sucks with two commands when I use "Tab" to fill the command...

So, I wanna know that how could I delete one command (save only one whichever speedtest_cli or speediest-cli), without remove the speediest_cli package?

Thanks

**Comment by sivel** [comment]
rm?
