### ISSUE TITLE
speedtest-cli consistently giving results very very different to web-based version. 

### ISSUE THREAD

**Issue by lozbrown** [sivel/speedtest-cli#263]
I recently installed a cron that runs speedtest-cli every 15 mins and formats the results into a log file like so:

> 20160514-22:30:01,Server: 5090,Ping: 30.506 ms,Download: 1.19 Mbit/s,Upload: 0.84 Mbit/s
> 20160514-22:45:01,Server: 5980,Ping: 30.842 ms,Download: 1.19 Mbit/s,Upload: 0.84 Mbit/s
> 20160514-23:00:01,Server: 2789,Ping: 33.251 ms,Download: 1.97 Mbit/s,Upload: 0.75 Mbit/s
> 20160514-23:15:01,Server: 6151,Ping: 29.978 ms,Download: 1.62 Mbit/s,Upload: 0.75 Mbit/s
> 20160514-23:30:01,Server: 5090,Ping: 30.387 ms,Download: 1.57 Mbit/s,Upload: 1.13 Mbit/s
> 20160514-23:45:01,Server: 6151,Ping: 29.87 ms,Download: 1.62 Mbit/s,Upload: 0.69 Mbit/s

The results seemed very low so I started investigating, strange thing is a web based speedtest from the same machine consistently returns in the high 30 Mbps for download. Other web based speedtest providers are consistent (or at least all in the same sort of region) with speedtest.net web based.
[http://www.speedtest.net/result/5326361857.png](url)

And I seem not to be the only one experiencing such an issue:
http://superuser.com/questions/1074568/speedtest-slow-via-ssh/1077025#1077025

The default python on my machine is Python 2.7.11+ 

Could this be some sort of clash? is there anything i should check?

**Comment by CyberMew** [comment]
Is this a known issue?

**Comment by lozbrown** [comment]
Out of interest why was this closed, seems like a re-producable issue that can be narrowed down to speedtest-cli.

**Comment by taismi** [comment]
If download speed is stable cli and web gives same results. If speed is varying web test returns higher speed.
https://github.com/sivel/speedtest-cli/issues/331
