### ISSUE TITLE
Gives error when I try to execute on Centos 6.7

### ISSUE THREAD

**Issue by ameyaagashe** [sivel/speedtest-cli#266]
[jim@agent2 ~]$ ./speedtest_cli.py --simple
./speedtest_cli.py: line 5: syntax error near unexpected token `newline'
./speedtest_cli.py: line 5: `<!DOCTYPE html>'

Any idea how to have it fixed?

**Comment by sivel** [comment]
Seems you downloaded an html file instead of a python file

**Comment by ameyaagashe** [comment]
I agree, my mistake. I did wget as I was not able on able to save on my external hard drive because of permissions. I downloaded the correct python file and now its working.
Ameya 

    On Friday, 3 June 2016, 22:01, Matt Martz <notifications@github.com> wrote:
 

 Seems you downloaded an html file instead of a python file—
