### ISSUE TITLE
Speedtest returns Failed to parse list of speedtest.net servers

### ISSUE THREAD

**Issue by mikesand** [sivel/speedtest-cli#268]
Since this seems to happen often and the fix is to switch line 345 to use c.speedtest.net or vice versa why not check to make sure it worked and resolve the other location if it failed?

```
uh = urlopen('http://www.speedtest.net/speedtest-servers-static.php')
if uh.read() == '':
    uh = urlopen('http://c.speedtest.net/speedtest-servers-static.php')
```

**Comment by sivel** [comment]
You should probably try upgrading.  This has been fixed for quite some time.

**Comment by mikesand** [comment]
I just upgraded today.

On Sunday, June 12, 2016, Matt Martz <notifications@github.com> wrote:

> You should probably try upgrading. This has been fixed for quite some time.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sivel/speedtest-cli/issues/268#issuecomment-225461094>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASvaVh3q6OmUZ4QWtQ9my-ks5Id91t0cks5qLHf5gaJpZM4IzzyM>
> .
>


-- 

*Regards,*

*Mike Sanders*
*Cenersys*
*www.cenersys.com <http://www.cenersys.com>*
*305 209-3835*

**Comment by mikesand** [comment]
And the problem persists.

**Comment by sivel** [comment]
I don't know how you upgraded but the version here on github does not contain the line you reference and has been updated to try a combination of 4 URLs.

The version of pypi matches what is here.

`speedtest-cli --version` should report `0.3.4`

**Comment by mikesand** [comment]
I used apt-get upgrade but it's showing an earlier version. I'll upgrade without that and see if it works out.

**Comment by mikesand** [comment]
I copied it from here and problem solved so it is just an old version from apt-get. Thanks!
