### ISSUE TITLE
Configuration time out

### ISSUE THREAD

**Issue by brentfredericksmith** [sivel/speedtest-cli#278]
Hello,
I am running the latest version on github.
When I run script from CLI everything does smoothly.
When I run a the script via cron and output to log I frequently get this result "Could not retrieve speedtest.net configuration: timed out" but sometimes it runs just fine. I cannot figure out why it runs just fine sometimes with cron, but other times I get the timed out error.

Any insights would be appreciated. I can provide whatever info you might find useful.

**Comment by runxctry** [comment]
I tried to reproduce by running the script every minute - couldn't reproduce.

Not sure where to start with this one - what kind of debugging have you done so far?  Have you tried to run the cronjob as a local user instead of root?  How about setting up a continuous ping against google.com to make sure that your network is ok?

**Comment by brentfredericksmith** [comment]
Thanks for taking the time to respond.
It is likely something in the way I have set things up and not an issue with speedtest-cli. My working knowledge of linux is still a work in progress.

Continuous ping results are fine. I might add that I am doing this on a Ubiquiti EdgeRouter-X which runs on Debian.

My cron config: (crontab -e)
0 5 * * * bash /home/admin/speedtest_script
0 17 * * * bash /home/admin/speedtest_script

The small script is attached

The generated log file:
07/08/16 17:00:01 - Could not retrieve speedtest.net configuration: timed out
07/09/16 05:00:01 - Could not retrieve speedtest.net configuration: timed out
07/09/16 17:00:01 - Could not retrieve speedtest.net configuration: timed out
07/10/16 05:00:01 - Ping: 24.174 ms Download: 115.42 Mbit/s Upload: 8.36 Mbit/s
07/10/16 17:00:01 - Ping: 24.817 ms Download: 111.69 Mbit/s Upload: 8.81 Mbit/s
07/11/16 05:00:01 - Could not retrieve speedtest.net configuration: timed out
07/11/16 17:00:01 - Ping: 24.377 ms Download: 122.06 Mbit/s Upload: 8.62 Mbit/s
07/12/16 05:00:01 - Could not retrieve speedtest.net configuration: timed out
07/12/16 17:00:01 - Could not retrieve speedtest.net configuration: timed out
07/13/16 05:00:01 - Could not retrieve speedtest.net configuration: timed out
07/13/16 17:00:01 - Ping: 24.845 ms Download: 62.57 Mbit/s Upload: 10.97 Mbit/s
07/14/16 05:00:01 - Ping: 24.316 ms Download: 119.52 Mbit/s Upload: 8.81 Mbit/s
07/14/16 17:00:01 - Ping: 23.495 ms Download: 123.08 Mbit/s Upload: 6.13 Mbit/s

As seen above, sometimes it runs just fine, and other times it gives the time out error.
When I run the script from bash it runs 100% of time.
[speedtest_script.txt](https://github.com/sivel/speedtest-cli/files/365241/speedtest_script.txt)

**Comment by runxctry** [comment]
Since you mention it's a router, I wonder about the niceness (resource priority) of cron vs foreground processes.  Googling didn't give me any straight answers.  
Not sure if it matters, but my Linux knowledge is sub-par.  

To test it, can you try passing in a longer timeout time,

**Comment by sivel** [comment]
Sounds like your connection is too inconsistent to even download the configuration.  Without the configuration, a test cannot be executed.  Maybe wrap the call in a script, and if the return code is not 0 try again.
