### ISSUE TITLE
URL for server lists has changed

### ISSUE THREAD

**Issue by FrakGart** [sivel/speedtest-cli#282]
The URLs for the server list appears to have changed today. They now require a ?threads=1 at the end eg:

http://c.speedtest.net/speedtest-servers-static.php?threads=1

**Comment by petehoffswell** [comment]
Confirmed.  

Adding "?threads=1" to the server list solved the problem for me.

`# diff speedtest-cli-orig /usr/local/bin/speedtest-cli
102d101
<
156d154
<
208d205
<
210d206
<
225d220
<
365d359
<
420,423c414,417
<         '://www.speedtest.net/speedtest-servers-static.php',
<         '://c.speedtest.net/speedtest-servers-static.php',
<         '://www.speedtest.net/speedtest-servers.php',
<         '://c.speedtest.net/speedtest-servers.php',
---
>         '://www.speedtest.net/speedtest-servers-static.php?threads=1',
>         '://c.speedtest.net/speedtest-servers-static.php?threads=1',
>         '://www.speedtest.net/speedtest-servers.php?threads=1',
>         '://c.speedtest.net/speedtest-servers.php?threads=1',
#
`

**Comment by aaronjs0** [comment]
They seem to be working again with the original URLs. I guess speedtest.net was doing some config changes and made a temporary change on their end.

**Comment by wopalka** [comment]
First, thanks for a great tool.  I pulled down the recent version 2 days ago and it works occasionally, however over the last 48 hours, I haven't seen it come back with a good result.  When I run speedtest-cli stand alone I get "Failed to retrieve list of speedtest.net servers:".  From my browser, I'm finding that I need to add the '?threads=1' to get the list.  If I were more familiar on how to rebuild this, I would give it a try but alas, I'm still trying to learn Python.

**Comment by FujiMakoto** [comment]
I can reproduce this problem locally at the moment. The following URL returns an empty response:
http://c.speedtest.net/speedtest-servers-static.php

Adding **?threads=1** to the end of the URL does resolve the issue.

However, simply changing the URL from http to https *also* appears to resolve the issue (suggested by @jdsmit60 in #86).

I'm not sure why the HTTPS URL works and why the HTTP URL does not. This appears to be an issue on speedtest.net's end either way, as you can also add **?threads=2** (what's supposed to be the default value) to the end of the URL above and it will return the same results.

**Comment by sivel** [comment]
This is already resolved by #212 which will be the basis of the next release.
