### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by cmgodoy** [sivel/speedtest-cli#284]
Hi,

I have this problem with encoding:

$ speedtest-cli 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Traceback (most recent call last):
  File "./speedtest-cli", line 796, in <module>
    main()
  File "./speedtest-cli", line 790, in main
    speedtest()
  File "./speedtest-cli", line 644, in speedtest
    print_('Testing from %(isp)s (%(ip)s)...' % config['client'])
  File "./speedtest-cli", line 146, in print_
    write(arg)
  File "./speedtest-cli", line 111, in write
    fp.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 22: ordinal not in range(128)

I solve this problem changing the line 111 from:
            fp.write(data)
to
            fp.write(data.encode('utf8'))

After the change:
$ speedtest-cli 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Cablevisión Fibertel ( ##### )...
Selecting best server based on latency...
Hosted by Horus Sistemas Informaticos SRL (Berisso) [9.77 km]: 4.043 ms
Testing download speed........................................
Download: 65.79 Mbit/s
Testing upload speed..................................................
Upload: 15.29 Mbit/s

--
Regards.

**Comment by sivel** [comment]
This is already resolved by #212 which will be the basis of the next release.
