### ISSUE TITLE
I end up with a template png and no overplayed data on the graphic, CLI results are only close on download, upload shows 0MB/s

### ISSUE THREAD

**Issue by 5c0tt** [sivel/speedtest-cli#286]
speedtest-cli --share --server 5086
I seem to get a blank template image back, waiting to have data overlaid on it.

me@lappy ~ $speedtest-cli --share --server 5086
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from XFINITY (73.70.244.46)...
Hosted by Google Fiber (Palo Alto, CA) [124.84 km]: 27.275 ms 
 ------ ***** --( When did google and Comcast hook ip like that? )
Testing download speed........................................
 ->OK +/- 2% Margin of Error — Download: 30.51 Mbit/s
Testing upload speed..................................................
 ->BAD +/- 100% Margin of Error — Upload: 0.00 Mbit/s

And this thing, is just a background image, a nice one, but noting I would want to share :)
Share results: http://www.speedtest.net/result/0.png

The odd thing, is, the download is about 1.5Mb/s slower than my local speed watcher and I  am  checking it now, the upload hits 12-13 Mb/s solid while the CLI states it took only shoes 0 Mb/s though I can tell you sure sure, data was indeed moved.  Any ideas?

I can strip it down to just the curl and poke at hat, I have no idea how to use python or whatever other languages are in this aside form feeling pretty good with bash and other CLI based hacks here and there for a few decades.

Curious — Why is there an identical version on `brew`, wasting 30 minutes of my day and ending in me laughing my ass off, over an underscore, and a dash, identical in every way. Speediest-cli and speediest_cli, might want to add speediest+cli and speediest—cli with speediest[-cli-] and perhaps speediest(cli) or even speediest----10-------20------30-------1000---->!!!!***-cli->

Thanks, great tool.
--

**Comment by sivel** [comment]
If you get a result of 0, the share graphic will fail.

There is a better version in devel that measures a bit better, that will be released soon.

As far as brew, I don't support that and don't recommend installing via brew.

**Comment by 5c0tt** [comment]
Any technical reason why? I don;r mind living on the edge a bit, but as long as I know where to look out for, I should be ok.  If I just take it down to the raw curl commands I estimate this is using, I should be able to figure out why it is hitting zero, present a patch, and then it will go into brew with no issues, it is after all, just a package manager like any of the others.  Or are you stating you prefer we install and compile from source?  Or do you have Binary blobs ready to go?

Thanks again.
