### ISSUE TITLE
Are simultaneous speedtest sessions possible?

### ISSUE THREAD

**Issue by RERobbins** [sivel/speedtest-cli#288]
I have set up a cron job to run speedtest-cli against a few servers of interest, including a mini server I set up in my Amazon Web Services virtual private cloud.  I have found that if I fork a process for each speedtest session the output that I get seems broken, i.e., I don't get clean, independent output for each process.  So, I'm running the speedtest-cli calls in sequence with no process forking, which seems to work.  I was wondering if I am doing something wrong in trying to fork three or four sub-processes to run speedtest-cli simultaneously with each process utilizing a different server.

**Comment by sivel** [comment]
If you run multiple speedtest processes simultaneously, you are obviously going to run into problems, because each process is trying to consume the most bandwidth possible.  

I do this a lot in testing, and generally configure cron to run in offsets
