### ISSUE TITLE
Wrong printing type when outputing host

### ISSUE THREAD

**Issue by baco** [sivel/speedtest-cli#290]
.encode method applied[0] to the string containing the host returns a bytes type value, which in Python3's print builtin outputs b'...' instead of the plain string.

[0] https://github.com/sivel/speedtest-cli/blob/7b09d8759fcbbda8a71aa49a4eaa825581b07439/speedtest_cli.py#L706

**Comment by sivel** [comment]
This is already fixed in the branch that will become the next release
