### ISSUE TITLE
speedtest.net returned an error ip of my gateway/router.

### ISSUE THREAD

**Issue by qurikuduo** [sivel/speedtest-cli#292]
Hi, bro. Thank U for what U have done!
  When I use speedtest-cli to test my network on a CentOS server, I found there were some incorrect  information of my network's IP address. So I forked your Incredible work and made a little modification to found out what happened when this program was running. So  I added a request to https://wtfismyip.com/text to retrieve my gateway/router's IP address, And I also print the response of request to http://www.speedtest.net/speedtest-config.php .  When I compare the response of the two URLs. I found the two IP addresses returned were different. The http://www.speedtest.net webpage test(flash) shows the correct IP address as same as https://wtfismyip.com/text shows. But http://www.speedtest.net/speedtest-config.php shows <client ip="xxx.xxx.xxx.xxx" the incorrect IP. Surprisingly, this URL returned several IP address, all of these IP addresses are at the same city as my gateway/router and as same ISP as mine.
  So I want to know whether some additional parameters should be appended when we request to
 http://www.speedtest.net/speedtest-config.php ? Or this is the speedtest.net's mistake? Does anyone know what did speedtest.net do to fill the ip parameter in the response of   http://www.speedtest.net/speedtest-config.php xml file's <client> node?

PS:
There are no catche servers in my network.

**Comment by qurikuduo** [comment]
Plz check this picture:

![speedtest net-python](https://cloud.githubusercontent.com/assets/4517807/18001505/dde85328-6bb5-11e6-8d61-a7d9897f973e.png)

or :

 https://pbs.twimg.com/media/Cqxs_YkUEAAsyxm.jpg:large

**Comment by qurikuduo** [comment]
Another screenshot:
![speedtest net-cli](https://cloud.githubusercontent.com/assets/4517807/18002334/afe614b6-6bb9-11e6-939b-8a382aa614e9.png)

**Comment by sivel** [comment]
This is outside of my control, and I have no affiliation with speedtest.net.  Based on what you are showing, speedtest.net, via their `speedtest-config.php` is returning an IP address different from what other sources are reporting.

Unfortunately I have no insight, and as mentioned no control over this.

**Comment by qurikuduo** [comment]
Thanks a lot.
