### ISSUE TITLE
I'm getting 0 for my upload speed

### ISSUE THREAD

**Issue by leftynaut** [sivel/speedtest-cli#295]
Did some research and saw this was a problem in the past. What's the current recommended fix?

Running on a Raspberry Pi connected directly to my router.

**Comment by sivel** [comment]
Try the following branch, I believe you should see an improvement:

https://raw.githubusercontent.com/sivel/speedtest-cli/modularize-2/speedtest.py

**Comment by leftynaut** [comment]
I installed with PIP and have no idea how to find and/or update that file. :/

Any tips?

**Comment by sivel** [comment]
Just download it and run it.  

```
wget https://raw.githubusercontent.com/sivel/speedtest-cli/modularize-2/speedtest.py
python speedtest.py
```

**Comment by leftynaut** [comment]
Thanks

**Comment by leftynaut** [comment]
While that works... is there a way I can call speedtest-cli like usual, but using that .py file?

**Comment by sivel** [comment]
```
pip install -I git+https://github.com/sivel/speedtest-cli.git@modularize-2#egg=speedtest_cli
```

**Comment by leftynaut** [comment]
Sorry for all the questions ... getting an error

copying build/lib.linux-armv7l-2.7/speedtest.py -> /usr/local/lib/python2.7/dist-packages

error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/speedtest.py'

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-WrzdPC/speedtest-cli/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-GJRrMw-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-WrzdPC/speedtest-cli
Storing debug log for failure in /home/pi/.pip/pip.log

**Comment by sivel** [comment]
Sounds like you need to run pip via `sudo` as it is installed in a place unprivileged users don't have access to.  

Additionally, I am locking this thread.  This is not the place for linux administration questions.
