### ISSUE TITLE
Failed to retrieve list of speedtest.net servers

### ISSUE THREAD

**Issue by csheldrick** [sivel/speedtest-cli#296]
Testing script off fresh download:
wget -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest_cli.py
chmod +x speedtest-cli

When run I am getting:
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Failed to retrieve list of speedtest.net servers:

However on another device this is working correctly.

**Comment by sivel** [comment]
Try https://raw.githubusercontent.com/sivel/speedtest-cli/modularize-2/speedtest.py

I believe this issue is already fixed there.

**Comment by csheldrick** [comment]
That worked thank you
