### ISSUE TITLE
test random server?

### ISSUE THREAD

**Issue by chovy** [sivel/speedtest-cli#300]
Can we get a `speedtest --random` flag to test a random server from `speedtest --list`?

I'm doing this right now but its pretty hacky:

`speedtest --server $(speedtest --list | awk -F')' '{print $1}' | sort -R | head -n 1)`

USA only:
`speedtest --server $(speedtest --list | ack -i 'United States' | awk -F')' '{print $1}' | sort -R | head -n 1)`

alias to pick a random US server and output simple results:

```
speedtest-random(){
  loc=$(speedtest --list | ack -i 'United States' | sort -R | head -n 1)
  id=$(echo $loc | awk -F')' '{print $1}')
  echo $loc
  speedtest --server $id --simple
}
```

**Comment by sivel** [comment]
What benefit would this provide?  Testing randomly wouldn't be very efficient and wouldn't be conducive to trending.
