### ISSUE TITLE
Force interface?

### ISSUE THREAD

**Issue by vacherub** [sivel/speedtest-cli#307]
I'm testing it on a Raspberry Pi3b, and I need any way to force the use of one of the interfaces (eth0).

Is possible?

**Comment by sivel** [comment]
`--source 192.168.0.123` where `192.168.0.123` is the IP address of eth0.

**Comment by treaki** [comment]
it would be nice if you could add the usual -I attribute as in many other unix/gnu-linux tools. Thanks
