### ISSUE TITLE
Failed to retrieve list of speedtest.net servers

### ISSUE THREAD

**Issue by jterning** [sivel/speedtest-cli#310]
is there something I need to do to fix this:

$ speedtest-cli --list
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Failed to retrieve list of speedtest.net servers:

**Comment by sivel** [comment]
Try downloading and using the following version https://raw.githubusercontent.com/sivel/speedtest-cli/modularize-2/speedtest.py

**Comment by jterning** [comment]
this version gives list index out of range

$ python speedtest.py 
Retrieving speedtest.net configuration...
Testing from AT&T U-verse (108.85.88.46)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Traceback (most recent call last):
  File "speedtest.py", line 1321, in <module>
    main()
  File "speedtest.py", line 1311, in main
    shell()
  File "speedtest.py", line 1268, in shell
    speedtest.get_best_server()
  File "speedtest.py", line 915, in get_best_server
    fastest = sorted(results.keys())[0]
IndexError: list index out of range

**Comment by sivel** [comment]
That indicates that you can not communicate with any of the speedtest test servers.  I've fixed that error, but it would not allow you to continue forward.

Communication with these servers typically happens over http (tcp/80).
