### ISSUE TITLE
Unable to retrieve list of servers

### ISSUE THREAD

**Issue by whiskeyalpharomeo** [sivel/speedtest-cli#312]
> Retrieving speedtest.net configuration...
> Retrieving speedtest.net server list...
> Failed to retrieve list of speedtest.net servers:

I know this has happened from time to time before...  Did they move the server list on the Speedtest side?

When I manually try the following URLs from a browser, I get no results:

-     http://www.speedtest.net/speedtest-servers-static.php
-     http://c.speedtest.net/speedtest-servers-static.php
-     http://www.speedtest.net/speedtest-servers.php
-     http://c.speedtest.net/speedtest-servers.php

**Comment by sivel** [comment]
Try downloading and using the following version https://raw.githubusercontent.com/sivel/speedtest-cli/modularize-2/speedtest.py

**Comment by whiskeyalpharomeo** [comment]
> Retrieving speedtest.net configuration...
> Testing from ISP (xxx.xxx.xxx.xxx)...
> Retrieving speedtest.net server list...
> Selecting best server based on ping...
> ERROR: Unable to connect to servers to test latency.
