### ISSUE TITLE
Failed to retrieve server list?

### ISSUE THREAD

**Issue by hwine** [sivel/speedtest-cli#313]
Looks like Okla changed their protocol today. As of 2016-09-26 00:00 -0700, I stopped being able to get a server listing. (I have an hourly cron that had been running successfully since February.)

I don't see any notice or uproar, so it could be me, but I've tried over 3 different ISPs where I could successfully get a browser speed test from the same site.

Any idea? Happy to help troubleshoot. Current output:
```
2016-09-26 19:34 PDT
$ speedtest-cli --list
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Failed to retrieve list of speedtest.net servers:
```

**Comment by xelfer** [comment]
Same error here

**Comment by sivel** [comment]
Please try https://raw.githubusercontent.com/sivel/speedtest-cli/modularize-2/speedtest.py and let me know if that resolves your issue.

**Comment by hwine** [comment]
Thanks for quick turn, no error message, but no server list either:
```
$ python2 speedtest.py --list
Retrieving speedtest.net configuration...
0 [hwine@hwin-28520 t (speedtest)]
$ python2 speedtest.py
Retrieving speedtest.net configuration...
Testing from AT&T U-verse (75.25.142.220)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
ERROR: Unable to connect to servers to test latency.
```

**Comment by sivel** [comment]
Technically you were able to get the server list, however it failed to actually connect to any of the test servers.

**Comment by hwine** [comment]
Not sure - [--debug output](https://gist.github.com/a4bf2fc2c28264f6f8930accccea8609
) - those look like the hardcoded values in the config

**Comment by sivel** [comment]
I've just pushed some additional debug output into that same branch/file.  Feel free to test, and see what debug information is provided.

**Comment by stemendrew** [comment]
I'm having the same problem. Debug output [here](https://gist.github.com/stemendrew/93f91a491854e135634e021fe5f3d029).

**Comment by mdupuy** [comment]
If I try to use any of the 0.3.4 (master, devel, no-https) branches on my Macs (installed via brew, pip or just git) and run, I get the very common "Failed to retrieve server list" seen in many different issues. If I simply add "https" to each of the lines in your "urls" assignment, it works fine. 

`    urls = [
        'https://www.speedtest.net/speedtest-servers-static.php',
        'https://c.speedtest.net/speedtest-servers-static.php',
        'https://www.speedtest.net/speedtest-servers.php',
        'https://c.speedtest.net/speedtest-servers.php',
    ]`

Running Python 2.7.12
I can try to re-link my /usr/local/bin/python to a 3.5 install if that'd help.

**Comment by sivel** [comment]
There is no need to https anywhere, you can always just run with `--secure` to get that same functionality.

**Comment by stemendrew** [comment]
Verified that it works correctly if I pass "--secure", and does not work at all if I do not.

**Comment by hwine** [comment]
And as of 2016-09-28 00:00:04 PDT it is back to working on http, so it was an Okla issue with a workaround (use of ```--secure``` option). 

I plan to update my script invocations to use the ```--secure``` option, but now I can take my time. 💯
