### ISSUE TITLE
Wrong IP address is being displayed

### ISSUE THREAD

**Issue by RobJDavey** [sivel/speedtest-cli#317]
When running the tool the wrong value is being displayed for my IP address.
I noticed where this tool states "Testing from _isp_ (_ip_)…" that the IP shown was not my actual IP address.
I did some investigation into the cause and discovered this appears to be the IP address returned by the `speedtest-config.php` file.
I tested what was happening by running the following commands:

``` sh
curl -s "https://www.speedtest.net/speedtest-config.php" | egrep --color="auto" 'ip=".*?"' #this is the IP returned from speedtest
dig @resolver1.opendns.com myip.opendns.com +short #this is my actual IP
```

The results:

``` text
<client ip="81.xxx.yyy.146" lat="51.4964" lon="-0.1224" isp="PlusNet" isprating="3.2" rating="5" ispdlavg="11049" ispulavg="2413" loggedin="0" />
80.xxx.yyy.198
```

For some reason the connection from the command line causes speedtest.net to return a different IP address.
The strange thing is, if I access that file from any of my web browsers (tested in Safari, and Firefox) the **correct** IP address is displayed.
At first I wondered if this was being caused by the `User-Agent` but if I pass the same one as my browser uses I see no change in the results. I've tried sending all the same request headers that were present in the web browser request but that still resulted in the wrong IP being returned so I've run out of ideas what is causing this difference in behaviour between browser and command line.

**Comment by bighippo999** [comment]
+1 I've just noticed this today. I've got a CSV log going back to May, on the 23/8 it started getting different addresses as the originator. I dont think speedtest-cli has been upgraded at that time so maybe it's speedtest.net and how it reports the originating address.
Not sure if it's coincidence but I'm on plusnet and I can see '81.174.yyy.146 too. It's one of many IP's in the log though.

**Comment by triple-it** [comment]
Noticed the (this) same issue today. It looks like they are pointing a whole /24 to the first ip they have found in their database in the CIDR block.  So .4 was the first ip in the speedtest databases --> the whole /24 gets .4 as %config['client'] --> ip

**Comment by sivel** [comment]
Please try with the latest version to see if it resolves any issues

**Comment by RobJDavey** [comment]
@sivel I'm seeing the correct IP now. 👍
