### ISSUE TITLE
Add a parameter to --list

### ISSUE THREAD

**Issue by alepuccetti** [sivel/speedtest-cli#322]
It would be very useful to add a parameter to the command line option `--list N` to display only the N closest servers. e.g `speedtest-cli --list 10`

**Comment by gaddman** [comment]
Yeah, something I was after too. I'm guessing @sivel is putting his effort into the new code, but you could try [my fork ](https://github.com/gaddman/speedtest-cli) for now. This adds a `--limit` option, which you can use with the list, or with the test itself.

**Comment by Phrohdoh** [comment]
Is piping to `head -n N` not enough?

**Comment by alepuccetti** [comment]
> Is piping to head -n N not enough?

Having an option in the code

**Comment by sivel** [comment]
I am in agreement with @Phrohdoh 

As such, I'm closing this issue.

**Comment by TigersWay** [comment]
Never tried it before. But at least today it does not "totally" work
```
./speedtest --list | head -n 20
Retrieving speedtest.net configuration...
 2953) Atlantic Metro (Los Angeles, CA, United States) [1.30 km]
 5827) Time Warner Cable (Los Angeles, CA, United States) [1.30 km]
 .......
 7017) C3Network.Inc (Diamond Bar, CA, United States) [41.20 km]
11603) Ultimate Internet Access (Ontario, CA, United States) [56.51 km]
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```
Thanks

**Comment by OSryx** [comment]
can you print 
`dmesg | tail `
