### ISSUE TITLE
THe <urlopen error timed out> issue

### ISSUE THREAD

**Issue by MurKit** [sivel/speedtest-cli#323]
Linux Mint 17.3
./speedtest-cli 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Failed to retrieve list of speedtest.net servers:

 <urlopen error timed out>
<urlopen error timed out>
<urlopen error timed out>

**Comment by nodesocket** [comment]
I had this error last night, but it started working again today. Not sure what is going on.

**Comment by sivel** [comment]
Please test with the recently released v1.0.0.
