### ISSUE TITLE
Different printing with Python 3 than with Python 2.

### ISSUE THREAD

**Issue by taismi** [sivel/speedtest-cli#327]
When using Python 3.5.2
_"C:\Program Files (x86)\Python35-32\python.exe" speedtest_cli.py --server 1002_
prints line
_b'Hosted by SkyBroadband (Manila) [8796.24 km]: 441.581 ms'_

When using  Python 2.7.11
_"C:\Program Files (x86)\Python\python.exe" speedtest_cli.py --server 1002_
prints line
_Hosted by SkyBroadband (Manila) [8796.24 km]: 343.899 ms_

I'm using Windows 7 Pro SP1.

**Comment by sivel** [comment]
Already resolved in devel.  Thanks for being the 1000th person to report this bug.  Your prize will be shipped to you asap.

**Comment by taismi** [comment]
When will the fixed version be released?

**Comment by sivel** [comment]
Within the next 14 years.  Probably much sooner.
