### ISSUE TITLE
Using six library

### ISSUE THREAD

**Issue by tusharmakkar08** [sivel/speedtest-cli#330]
I was going through the code and found [this](https://github.com/sivel/speedtest-cli/blob/master/speedtest_cli.py#L96) . Any specific reason for not using `six` library. I know it will add external dependency but it'll make the code cleaner and easily maintainable.

**Comment by sivel** [comment]
Exactly, I want no external dependencies.

**Comment by tusharmakkar08** [comment]
But due to that, we're doing EAFP which is making it unclean. Six would make the code look clean and beautiful.
