### ISSUE TITLE
<urlopen error [Errno -2] Name or service not known> Error

### ISSUE THREAD

**Issue by yidingalan** [sivel/speedtest-cli#338]
I am testing the Ethernet speed (using a ENC28J60 module) on a Raspberry pi zero. When I run `speedtest-cli`, it gives me this error:
`Could not retrieve speedtest.net configuration: <urlopen error [Errno -2] Name or service not known>`

Any idea of what might cause this issue? Thanks

**Comment by pbulteel** [comment]
You cannot get to the speedtest.net server. Can you go anywhere else? Can you do a wget https://speedtest.net? It could be a simple matter of resolving DNS or your interface is not reaching the internet.

**Comment by yidingalan** [comment]
Yeah looks like it's a network issue on my end. Thanks
