### ISSUE TITLE
Upload results inaccurate on low-speed uplinks

### ISSUE THREAD

**Issue by chanetd** [sivel/speedtest-cli#341]
I have a test setup with an uplink that is shaped to max 1Mbit/sec. Version 0.3.4 of speedtest-cli reliably reported upload speeds of ~0.83Mbit/s, but v1.0.0 reports upload speeds of ~1.69Mbit/s. The issue lies with the way speedtest-cli computes the upload speed, because the TX byte counters on the interface show results that are consistent with speedtest-cli 0.3.4.

I did some digging, and I think I have found a lead towards the source of the inaccuracy: the HTTPUploader class tallies bytes as they are passed on to urllib2 for uploading, but due to the slow uplink, all HTTPUploader instances raise SpeedtestTimeout before the full upload is complete.  My guess is that the final upload results therefore incorrectly counts a number of bytes as uploaded whereas they're really stuck in urllib's (or the outgoing interface's) TX buffer.

An extra data point that (I think) supports my assumption: if I increase the HTTPUploader timeout by a factor of 10, the uploads complete successfully (i.e. no SpeedTestTimeout exceptions are raised) and the reported upload speed is back down to ~0.9Mbit/s, which is in line with reality.

**Comment by KoenR3** [comment]
We are having this issue as well.  It is not as much related to inaccurate results as an incorrect tallying of the results of the speedtest.
