### ISSUE TITLE
Download test works fine, upload fails:

### ISSUE THREAD

**Issue by red-uk** [sivel/speedtest-cli#343]
Pip installed on rasp pi b wheezy

Download: 38.18 Mbit/s
Testing upload speedTraceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 9, in <module>
    load_entry_point('speedtest-cli==1.0.0', 'console_scripts', 'speedtest-cli')()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1400, in main
    shell()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1376, in shell
    speedtest.upload(callback=callback)
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1086, in upload
    data._create_data()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 497, in _create_data
    (chars * multiplier)[0:int(self.length) - 9]
MemoryError

**Comment by klaeufer** [comment]
Exact same traceback here, Pogoplug 4 with wheezy.

**Comment by diwilli** [comment]
Seeing the same thing with my Pi Zero using the curl-ed raw file.

**Comment by sivel** [comment]
Please try with the devel version and see if it resolves your issue:

https://raw.githubusercontent.com/sivel/speedtest-cli/devel/speedtest.py

**Comment by diwilli** [comment]
Works for me thanks.

**Comment by sivel** [comment]
Great.  I was trying before release to optimize some code, and made a change that broke performing a speedtest on devices with limited memory.  I reverted that change in the devel branch, and will likely make a new release soon with the change.

**Comment by red-uk** [comment]
Great news, many thanks!

**Comment by red-uk** [comment]
Works for me too, thanks

**Comment by sivel** [comment]
I've released the fix in v1.0.1

**Comment by jsalatiel** [comment]
Is this really fixed ?
I am trying to run on a mips router with 64MB ram and upload gets killed by OOM.
The old speedtest-cli.py version 0.3.1 worked just fine.
