### ISSUE TITLE
support for ipv6

### ISSUE THREAD

**Issue by deuntje** [sivel/speedtest-cli#345]
Please add support for ipv6 testing. I tried to force ipv6 testing by doing:

```
# speedtest --source 2a02:f68:XXX::1
Retrieving speedtest.net configuration...
Could not retrieve speedtest.net configuration: <urlopen error [Errno -9] Address family for hostname not supported>
```

it would be nice if you can test using --ipv4 / --ipv6 flags or by setting the ipv6 source address.

**Comment by sivel** [comment]
Speedtest.net does not support IPv6, so supporting it doesn't make much sense
