### ISSUE TITLE
The file speedtest_cli.py has been deprecated in favor of speedtest.py and is available for download at:

### ISSUE THREAD

**Issue by tyrsrd** [sivel/speedtest-cli#347]
how to fix this

[root@hestia ~]# speedtest-cli -h
The file speedtest_cli.py has been deprecated in favor of speedtest.py
and is available for download at:

https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
[root@hestia ~]#

**Comment by tyrsrd** [comment]
anybody help?

**Comment by sivel** [comment]
Pretty sure the error message indicates the problem and what is needed.

**Comment by szwifi** [comment]
I also meet this issue.
