### ISSUE TITLE
Cannot retrieve speedtest configuration

### ISSUE THREAD

**Issue by hsienchiaolee** [sivel/speedtest-cli#352]
Version 1.0.1, installed using `pip install speedtest-cli`. Python version: `2.7.6`.

Tried looking at the older version issues, but couldn't get them to work.

```
$ speedtest-cli
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: 1
```

**Comment by TigersWay** [comment]
Just tried the curl download and got same trouble....
```shell
$ ./speedtest-cli
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: 1

$ ./speedtest-cli --version
1.0.1
```
Thanks

**Comment by alexivanou** [comment]
Previous version output:
```
Retrieving speedtest.net configuration...
Could not retrieve speedtest.net configuration: HTTP Error 504: Gateway Timeout

```
I think "ERROR: 1" is much less informative than "HTTP Error 504: Gateway Timeout"

**Comment by Octolus** [comment]
root@la-1:~# ./speedtest-cli
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: 1

**Comment by Octolus** [comment]
seems to be fixed

**Comment by sivel** [comment]
This appeared to be an issue with speedtest.net itself.  However I have made some changes to report the error better in these cases.
