### ISSUE TITLE
Is the brew install option available for OSX legit?

### ISSUE THREAD

**Issue by mrkent** [sivel/speedtest-cli#356]
http://brewformulas.org/SpeedtestCli

If so, it'd be helpful to include it on the README.

**Comment by sivel** [comment]
It is not. I do not support it and the options I the readme are my only recommendations

**Comment by jb510** [comment]
I understand (using brew for Py seems inefficient) and certainly respect your prerogative on what you support.

...but a pointless +1 for brew (because I update brew packages regularly and don't regularly use/update pip)
