### ISSUE TITLE
Output total downloaded and updated bytes

### ISSUE THREAD

**Issue by securitypedant** [sivel/speedtest-cli#358]
I am using your super helpful script as part of a way to monitor my home connection. However, I want to be sure I am not eating huge amounts of data usage per month. It would be great if your script could calculate, per test, the amount of uploaded/download data so I can aggregate over a day and tweak how often I run the script.

**Comment by sivel** [comment]
This data is already collected and stored, it's just not output anywhere.  Adding it to the `JSON` output at minimum would be pretty easy.

**Comment by securitypedant** [comment]
Would be great if you can dump into the JSON. Then I can easily get into my script and add to a daily total counter.

**Comment by sivel** [comment]
I've pushed that change into the devel branch to return `bytes_received` and `bytes_sent` as part of the JSON output.

You can give it a try by downloading the speedtest.py from devel:

https://raw.githubusercontent.com/sivel/speedtest-cli/devel/speedtest.py

**Comment by securitypedant** [comment]
OK, testing now.

BTW I did my install using pip install, I ended up with a very old version.

ssimon:~ simon$ speedtest-cli --version
0.3.2

I'll instead pull from this git rather than using pip.

**Comment by securitypedant** [comment]
Perfect, just what I was after... thanks.

1534-simon:~ simon$ speedtest --json 
{"timestamp": "2017-01-18T21:23:33.693046", "ping": 4.801, "upload": 93556747.81899936, "server": {"latency": 4.801, "name": "San Francisco, CA", "url": "http://sfo.speedtest.sbcglobal.net/speedtest/upload.php", "country": "United States", "lon": "-112.4165", "cc": "US", "host": "sfo.speedtest.sbcglobal.net:8080", "sponsor": "AT&T", "lat": "35.7110", "id": "6026", "d": 2.0690134581951136}, "bytes_sent": 35127296, "download": 527192145.0704664, "bytes_received": 409373932}
