### ISSUE TITLE
Very different results between versions

### ISSUE THREAD

**Issue by brentfredericksmith** [sivel/speedtest-cli#359]
After using 0.3.4 for several months to take twice daily speed tests and log them I upgraded to 1.0.1.

1.0.1 gives me very different results, after running dozens of tests to compare it seems that 1.0.1 shows my connection about 20% slower than 0.3.4.

The same external server is being used for testing, and test are being run from the same device.

Any thoughts as to why this might be?

**Comment by sivel** [comment]
The timing is much more exact in v1 than it was before. However over the three months of performance testing that I ran on a 10 minute interval, I saw better results with v1 than earlier versions.

I have no insight specifically as to why it would be less performant for you.

If you figure out why, feel free to open a new issue with specific details.
