### ISSUE TITLE
Listing servers returns error at the end of list

### ISSUE THREAD

**Issue by tonymorello** [sivel/speedtest-cli#361]
`speedtest --list` at the end of the list shows this error message...

> Traceback (most recent call last):
>   File "/usr/bin/speedtest", line 11, in <module>
>     load_entry_point('speedtest-cli==1.0.3a0', 'console_scripts', 'speedtest')()
>   File "/usr/lib/python3.6/site-packages/speedtest.py", line 1420, in main
>     shell()
>   File "/usr/lib/python3.6/site-packages/speedtest.py", line 1348, in shell
>     print_(line)
> UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 19: ordinal not in range(128)

**Comment by ylluminate** [comment]
I think it's essentially the same error as this:
https://github.com/sivel/speedtest-cli/issues/362
