### ISSUE TITLE
Missing python package? ImportError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by fabiocannizzo** [sivel/speedtest-cli#363]
Just installed the Linux arch community package. I get the error below.
Am I supposed to install separately some python packages?
I am not experienced with python. With `which` I can see I have both `python` an `python2`.
I also have the `setuptools` package.

```
[~]# speedtest-cli
Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```

**Comment by sivel** [comment]
Sounds like you have a broken python setuptools install

**Comment by rjt** [comment]
On other platforms, python-setuptools had to be reinstalled.  
On CentOS7: `yum reinstall python-setuptools`
i do not know the reinstall command for ARCH offhand.  
(No module named pkg_resources)[https://stackoverflow.com/a/31200131/711422]

**Comment by gundamlh** [comment]
try
    pip -V
    pip install speedtest-cli
