### ISSUE TITLE
Set a mini server using API

### ISSUE THREAD

**Issue by k-aclyon** [sivel/speedtest-cli#365]
hello! thank you for this good script :) he's very useful for us, we manage over 500 linux firewall in our schools and we are using your script every night for checking the bandwidth. 
But i got a problem with setting up a mini server, i tried :

```
s = speedtest.Speedtest()
s.set_mini_server("http://speedtest.test.fr/") #this is not the real url
s.download() 
```

but i got this error : 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "speedtest.py", line 1039, in download
    (os.path.dirname(self.best['url']), size, size))
KeyError: 'url'
```
can you tell me what's my mistake ?

thank you.

**Comment by sivel** [comment]
speedtest.py itself does the following when using `--mini`

```
s = speedtest.Speedtest()
s.get_best_server(s.set_mini_server("http://speedtest.test.fr/"))
s.download()
```
