### ISSUE TITLE
problems with --mini

### ISSUE THREAD

**Issue by Benjarobbi** [sivel/speedtest-cli#374]
I just have problems with mini. My older copy of speedtest-cli works fine with it.
I try 
`./speedtest-cli --mini http://exampleserver.com/mini/index-php.html
Retrieving speedtest.net configuration...
Testing from linuxservers (1.2.3.4)...
ERROR: Failed to connect to http://exampleserver.com/mini/index-php.html
`
Just giving me an error. 
The older copy:
`./p.py --mini http://exampleserver.com/mini/index-php.html
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from linuxservers (1.2.3.4)...
Hosted by Speedtest Mini (exampleserver.com) [0.00 km]: 12.801 ms
Testing download speed........................................
Download: 892.63 Mbit/s
Testing upload speed..................................................
Upload: 33.03 Mbit/s
`

**Comment by sivel** [comment]
You need to make sure that your webserver configuration specifies `index-php.html` as the default document.  Or copy the correct file to the default document. This may be as easy as:

```
ln -s index-php.html index.html
```

The install instructions for speedtest mini indicate that this is a step:

```
Setup Instructions
1. Read the Terms and Conditions
2. Download mini.zip
3. Unzip it onto your server
4. Decide on PHP, ASP.NET, ASP or JSP
5. Select which index file to use
6. Rename the file to index.html
7. Load index.html in your browser
```

**Comment by Benjarobbi** [comment]
Thank you,

i just noticed that this wasn't necessary in the old script.

Thank you! :+1:
