### ISSUE TITLE
ERROR: Unable to connect to servers to test latency.

### ISSUE THREAD

**Issue by 1265578519** [sivel/speedtest-cli#376]
[root@vultr ~]# ./speedtest.py --share
Retrieving speedtest.net configuration...
Testing from Choopa (104.238.161.188)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
ERROR: Unable to connect to servers to test latency.

**Comment by sivel** [comment]
As mentioned, this indicates that you cannot connect to the test servers to do a latency check.

Run it agin with `--debug` to see the URLs it is attempting to connect to.  That will give you an idea of what firewall or restrictions you have in place that are blocking the functionality.
