### ISSUE TITLE
DNS lookups impact results

### ISSUE THREAD

**Issue by johnavp1989** [sivel/speedtest-cli#381]
The amount of time it takes to resolve hostnames is included in the timer. This does not have a significant impact if DNS is working properly but skews the results when DNS responses are delayed.

Here's the result when DNS is working properly:

```
speedtest-cli
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Selecting best server based on latency...
Hosted by School District of Philadelphia (Philadelphia, PA) [24.88 km]: 71.063 ms
Testing download speed........................................
Download: 75.16 Mbit/s
Testing upload speed..................................................
Upload: 35.38 Mbit/s
```

And the same after introducing a 5 second delay to DNS requests:

```
speedtest-cli
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Selecting best server based on latency...
Hosted by Hotwire Communications (Philadelphia, PA) [24.88 km]: 56.714 ms
Testing download speed........................................
Download: 7.03 Mbit/s
Testing upload speed..................................................
Upload: 2.90 Mbit/s
```

**Comment by sivel** [comment]
There is no built in mechanism in python to cache DNS within it's http libraries.

It is not the goal of this project to solve poorly configured host DNS.  This should be resolved at the OS level, potentially via nscd.
