### ISSUE TITLE
Parser error when running program remotely 

### ISSUE THREAD

**Issue by craigers521** [sivel/speedtest-cli#383]
Hi - i pushed this program out to some remote servers and i'm trying to execute the script remotely and get the results sent back locally.  I keep getting this parser error though. 

```
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/tmp/./speedtest", line 1475, in <module>
    main()
  File "/tmp/./speedtest", line 1465, in main
    shell()
  File "/tmp/./speedtest", line 1368, in shell
    speedtest = Speedtest()
  File "/tmp/./speedtest", line 726, in __init__
    self.get_config()
  File "/tmp/./speedtest", line 766, in get_config
    root = ET.fromstring(''.encode().join(configxml))
  File "<string>", line 124, in XML
cElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```

Any ideas?

**Comment by sivel** [comment]
I recommend running with `--debug` to see what is returned while fetching the config from speedtest.net

**Comment by craigers521** [comment]
Hi Matt. Just found out we have a firewall blocking it the zip file. Any
other to pull down the config? Can I set it locally?

**Comment by sivel** [comment]
No, there is no current way to provide the config by any other means that letting the script fetch it during runtime.

**Comment by craigers521** [comment]
All good. I just have to beg the security guys for a variance. Thanks for
the reply Matt.

**Comment by sivel** [comment]
You might have additional issues with opening up firewall access to the test servers as well, since they are not hosted with speedtest.net but usually with other service providers.  Using `--list` to nail down an individual host may help with that in the future, tied with `--server` to specify that single host.
