### ISSUE TITLE
Correct error

### ISSUE THREAD

**Issue by CraftHosting** [sivel/speedtest-cli#384]
When i'm typing : 
 ./speedtest.py --share --no-download

i'm obtain this : 

Retrieving speedtest.net configuration...
Testing from Netrix (89.234.***.1**)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Orange (Paris) [15.19 km]: 2.373 ms
Skipping download test
Testing upload speed....................................................................................................
Upload: 246.74 Mbit/s
Share results: http://www.speedtest.net/result/0.png

And this picture it's not work

**Comment by sivel** [comment]
I'm not sure anything can be done here, other than documenting that this wont work.

I don't control the speedtest.net API, and they dictate what is valid.  Sending a 0 for upload or download will cause the API to fail and not render an image.
