### ISSUE TITLE
Does not test if --csv-header specified

### ISSUE THREAD

**Issue by LeeThompson** [sivel/speedtest-cli#386]
If you run the script with --csv-header, you only get the csv-header and it does not perform any tests.

```
speedtest-cli.py --csv-header
speedtest-cli.py --csv --csv-header
speedtest-cli.py --csv-header --csv
```

**Comment by sivel** [comment]
That is expected.  You wouldn't want to output the csv header over and over again, piped into a single csv file.

Run it once to create the header, and all future executions should only use --csv
