### ISSUE TITLE
timestamp written with --csv is utc

### ISSUE THREAD

**Issue by C-gotoh** [sivel/speedtest-cli#387]
My issue with this is that I would like to know the time of the execution and would therefore like to have the program use the systems localtime for the timestamp.
The output format "2017-04-24T17:00:38.717966" makes it harder to adjust later than a standard unix timestamp.
Are you against having a flag such as --localtime to define this behaviour?

**Comment by sivel** [comment]
Sorry, I'm going to stick with the ISO8601 date format.  Also

Any modern language or spreadsheet application should have functionality to handle ISO8601 dates and timezone manipulation.
