### ISSUE TITLE
Speedtest server returns U:0, D:0

### ISSUE THREAD

**Issue by jenschurchill** [sivel/speedtest-cli#389]
This server works (reports download/upload above 0), when called via http://speedtest.net or using the windows app...

However calling:
speedtest-cli --server 5669

Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Gigabit (Ballerup) [10.98 km]: 5018.571 ms
Testing download speed................................................................................
Download: 0.00 Mbit/s
Testing upload speed....................................................................................................
Upload: 0.00 Mbit/s

**Comment by sivel** [comment]
With a ping time of 5 seconds, I don't doubt that you get a 0 speed.  Use a closer/faster server

**Comment by jenschurchill** [comment]
Thing is, in the app and website, it reports sub 2 ms ping.
speedtest-cli ping time has always been unreliable, so I didn't mention it.

That server is the closest, it is run by my internet provider.
On speedtest.net, from that server, I just got:
PING 2 ms, DOWNLOAD 94.99 Mbps, UPLOAD 95.36 Mbps
