### ISSUE TITLE
Setting Source as per Wiki API example doesn't use source for transfer

### ISSUE THREAD

**Issue by cfulton** [sivel/speedtest-cli#390]
I have two IP's and the router will route based on which IP is used.

I.E 
192.168.1.101 -> WAN1 
192.168.1.102 -> WAN2

I verified that when using the following commands both work and send data via provided source

```
speedtest-cli --source '192.168.1.101'
speedtest-cli --source '192.168.1.102'
```

The problem is, regardless of source provided from the WIKI example, 192.168.1.101 will always be used.

```
source = "192.168.1.102"
speedtest.SOURCE = source
s = speedtest.Speedtest()
s.get_best_server()
s.download()
s.upload()
```

Could the following changes to the API be made?

Inclusion of a call similar to the following

speedtest.set_source(string of ip)

**Comment by sivel** [comment]
I didn't write that portion of the docs, I guess someone else did.  In any case, maybe I can add a helper, maybe not. In any case you need to also set `speedtest.socket.socket = speedtest.bound_socket`

Honestly though I wouldn't rely on that behavior.  I am planning to rewrite uses of global vars. But I'll make sure to bump the version to indicate backwards incompatible changes.

**Comment by cfulton** [comment]
Perfect, worked. Thanks mate.

**Comment by rimkov** [comment]
i forgot this line
added to wiki
