### ISSUE TITLE
ping from python

### ISSUE THREAD

**Issue by screig** [sivel/speedtest-cli#392]
Can one get the ping number, like one can get the upload or download speeds, via python:

```
s = speedtest.Speedtest()
s.get_best_server()
s.download()
s.upload()
```

Additional, through callling this in python how can I get the results in bytes.  Like so for the command line version:

>  --bytes                                  Display values in bytes instead of bits. Does not affect the image generated by --share, nor output from --json or --csv

**Comment by sivel** [comment]
All results are stored in `s.results` such as `s.results.ping` which is established from `s.get_best_server()`

To get bytes instead of bits,

`s.results.download / 8.0`

**Comment by screig** [comment]
Thanks
