### ISSUE TITLE
get_servers returns KeyError: 'url' when specifying a Server ID

### ISSUE THREAD

**Issue by rhart211** [sivel/speedtest-cli#393]
I'm trying to specify a single server ID, however when I do so I get  KeyError.
`import speedtest`
`servers = [1344]`
`s = speedtest.Speedtest()`
`s.get_servers(servers)`
which returns:
`{781.9148366108192: [{'name': 'Reston, VA', 'url': 'http://speed1.iad2.inforelay.net/speedtest/upload.php', 'country': 'United States', 'lon': '-77.3414', 'cc': 'US', 'host': 'speed1.iad2.inforelay.net:8080', 'sponsor': 'InfoRelay Online Systems', 'url2': 'http://67.208.74.124/speedtest/upload.php', 'lat': '38.9686', 'id': '1344', 'd': 781.9148366108192}]}`
But download returns the KeyError:
`s.download()`
`Traceback (most recent call last):`
`File "<stdin>", line 1, in <module>`
 `File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1086, in download`
 `   (os.path.dirname(self.best['url']), size, size))`
`KeyError: 'url'`

What am I doing wrong?
Thanks.

**Comment by sivel** [comment]
Per the docs at https://github.com/sivel/speedtest-cli/wiki you also need to call `s.get_best_server()`

Regardless of specifying only a single server, get_best_server still calculates necessary information.

**Comment by rhart211** [comment]
Okay. Thanks for the guidance. I thought that even though I had included that function, it would choose a different server, even though I had a specified one in get_servers(). 

Thanks.
