### ISSUE TITLE
speedtest --list result with ping 

### ISSUE THREAD

**Issue by dade80vr** [sivel/speedtest-cli#394]
HI, great work!
Would it be possible to add the ping time in the --list result?
Additionally would it be possible to sort list by ping?
Only for stats..

Thank you!

**Comment by sivel** [comment]
I don't have any plans on adding that.  

From a list, I see 5921 servers.  To get a ping average, that is 3 requests per server, which would result in 17763 HTTP requests.  Those happen serially, and would take a really long time.

We already ping the 5 closest servers, and pick the one with the lowest ping.
