### ISSUE TITLE
Connection error with --json does not return json

### ISSUE THREAD

**Issue by bunnymatic** [sivel/speedtest-cli#401]
It would be really nice if in the case of error, the output was in the format requested.  In particular, when the system can't get the config (because the net connection is down or bad), and I've requested `json` output, that the result was `json`.

I looked into the code and was thinking about updating this

```
    printer('Retrieving speedtest.net configuration...', quiet)
    try:
        speedtest = Speedtest()
    except (ConfigRetrievalError, HTTP_ERRORS):
        printer('Cannot retrieve speedtest configuration')
        raise SpeedtestCLIError(get_exception())
```
with something like
```
    printer('Retrieving speedtest.net configuration...', quiet)
    try:
        speedtest = Speedtest()
    except (ConfigRetrievalError, HTTP_ERRORS):
        if machine_format:
            print_error_in_machine_format("Cannot retrieve config")
        else:
            printer('Cannot retrieve speedtest configuration', )
        raise SpeedtestCLIError(get_exception())
```

Before I go down that road, I thought I'd just see how you felt about a change like that.  It seems like (in the json case), you could add a `status` or `success` field field in the reponse that indicated the status and maybe a `message` field that could be used in the case of error.  I'm not sure how this would go for a csv output.

Any thoughts?  I may try to do a little coding and submit a PR.  But if you have already thought about this, I'd love to hear your thinking so my solution might fit into the project.

Thanks for building the script.

**Comment by sivel** [comment]
You should be using the exit code to determine success and not store or use the returned data if the exit code is not 0

Should you want more flexibility, I suggest using the python API directly and not calling as a script
