### ISSUE TITLE
--secure has stopped working

### ISSUE THREAD

**Issue by stevewrightnz** [sivel/speedtest-cli#403]
Hi Sivel
The -- secure option seems to have stopped working a couple of days ago.

-----ERROR-----
$ speedtest-cli --secure
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: 1
-----END ERROR-----

Steve

**Comment by laudatioUno** [comment]
Yep, I can confirm this. My script isn't running since 15th of june at 00:00.

The response is:
# ./speedtest.py --secure
ERROR: HTTP Error 404: Not Found

Whitout the --secure option speedtest is running.

Thanks for checking an fixing.

**Comment by sivel** [comment]
Yeah, I have no idea why, but speedtest.net is blocking the User-Agent speedtest-cli is using when communicating with https.

This has happened in the past, and usually been temporary.

Just don't supply `--secure` for now.

You can see more information when running if you supply `--debug` also.

**Comment by MIK-BGC** [comment]
Seems to work again since yesterday evening(7pm CET)...

**Comment by rpe1313** [comment]
Speedtest is blocking headers from speedtest-cli. Modified 394 thru 400 (User-Agent Header) as follows
`    ua_tuple = (
        'Mozilla/5.0',
        '(%s; U; %s; en-us)' % (platform.system(), platform.architecture()[0]),
        'Gecko/20100101',
        '(KHTML, like Gecko)',
        'Firefox/53.0'
    )`

This resolves the 404 error.

**Comment by sivel** [comment]
`--secure` is working as expected currently
