### ISSUE TITLE
Support for Speedtest Custom (the Replacement for Speedtest Mini)

### ISSUE THREAD

**Issue by RERobbins** [sivel/speedtest-cli#418]
Now that speedtest mini has been deprecated in favor of speedtest custom, I was wondering if speedtest-cli will work with a speedtest custom server.

**Comment by ChMG** [comment]
+1 I also need this feature.

**Comment by edwardally** [comment]
Good 1..  +1

**Comment by sivel** [comment]
https://github.com/sivel/speedtest may have that functionality.  I'm guessing speedtest custom is just the renaming of ookla's for sale speedtest product.

**Comment by RERobbins** [comment]
Has there been any movement on this front?

**Comment by sivel** [comment]
I have no plans to add this functionality to speedtest-cli at this time.  speedtest-cli will continue to only support the legacy http tests.
