### ISSUE TITLE
Hassio Python 3.6  speedtest no work

### ISSUE THREAD

**Issue by EabeyTong** [sivel/speedtest-cli#421]
Hassio Python 3.6  speedtest no work

**Comment by sivel** [comment]
I have no idea when this means.  Try opening issues with more relevant information.

**Comment by vslavik** [comment]
The original submitter was probably referring to the fact that the speedtest sensor depends on speedtest-cli, which isn't available to it in the Hassio distribution:

```
Error executing speedtest: Command '['/usr/bin/python3', '/usr/lib/python3.6/site-packages/speedtest.py', '--simple', '--server', '4162']' returned non-zero exit status 1.
```
