### ISSUE TITLE
Upload test is Killed

### ISSUE THREAD

**Issue by moqiaoduo** [sivel/speedtest-cli#424]
I get the Download Speed, but then terminal show me "Killed" and no more show anything. Please tell me why it happened. Thank you!

**Comment by sivel** [comment]
You are likely running out of memory.  You will need to use the `--no-pre-allocate` option.

```
  --no-pre-allocate     Do not pre allocate upload data. Pre allocation is
                        enabled by default to improve upload performance. To
                        support systems with insufficient memory, use this
                        option to avoid a MemoryError
```

**Comment by csugulo** [comment]
I used --no-pre-allocate but it was still killed, I have 128MB memory, isn't it enough for upload test?
