### ISSUE TITLE
ipv6 support planned?

### ISSUE THREAD

**Issue by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [sivel/speedtest-cli#427]
ipv6 support planned?

**Comment by sivel** [comment]
ipv6 is not possible as speedtest.net does not support ipv6 tests.

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
if ever you are interested in adding ipv6 support via a different provider testing platform, apparent the xfinity tests allow you to choose between ipv4 and ipv6 individually.

http://speedtest.xfinity.com/
