### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by vchrizz** [sivel/speedtest-cli#430]
like in #412 im running this on mipsel router, im using no-pre-allocate as recommended.
on about 30 of our routers (all same hw and sw) this runs well, but on 2-3 i get the following exception.
what could be wrong? where should i look into?
```
user@router:~$ rm -f speedtest.py; curl -sO https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py && chmod +x speedtest.py
user@router:~$ ./speedtest.py --simple --server 3199 --no-pre-allocate
Exception in thread Thread-81:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "./speedtest.py", line 592, in run
    f = urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1211, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1178, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 962, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 996, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 958, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 822, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 789, in send
    datablock = data.read(blocksize)
  File "./speedtest.py", line 564, in read
    chunk = self.data.read(n)
  File "./speedtest.py", line 558, in data
    self.pre_allocate()
  File "./speedtest.py", line 551, in pre_allocate
    (chars * multiplier)[0:int(self.length) - 9]
MemoryError

Traceback (most recent call last):
  File "./speedtest.py", line 1504, in <module>
    main()
  File "./speedtest.py", line 1494, in main
    shell()
  File "./speedtest.py", line 1466, in shell
    speedtest.upload(callback=callback, pre_allocate=args.pre_allocate)
  File "./speedtest.py", line 1191, in upload
    self.results.bytes_sent = sum(finished)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
user@router:~$ free -m
             total       used       free     shared    buffers     cached
Mem:           249        213         35          0         12        107
-/+ buffers/cache:         93        155
Swap:            0          0          0
user@router:~$ python --version
Python 2.7.3
user@router:~$ uname -a
Linux router 3.10.14-UBNT #1 SMP Sat Apr 22 06:38:07 PDT 2017 mips GNU/Linux
```

**Comment by sivel** [comment]
It seems that even without pre-allocation, that device is still too limited in memory to generate the necessary data for the upload test.

**Comment by vchrizz** [comment]
oh ok, then you might see from following list what the required free/unused memory is?
it works on all routers but not on: "biss" and "gri106" and "mh".
on "mh" it even "crashes" the router so a physical reboot is required...
maybe its helpful for others to know what the minimum requirement of free memory is..

arn22      ping ok      Mem: 249M 210M 38M 0B 25M 104M -/+ buffers/cache: 80M 168M
bal3       ping ok      Mem: 249M 143M 105M 0B 12M 56M -/+ buffers/cache: 74M 174M
bec2       ping ok      Mem: 249M 219M 29M 0B 29M 113M -/+ buffers/cache: 76M 172M
biss       ping ok      Mem: 249M 233M 15M 0B 17M 123M -/+ buffers/cache: 92M 156M
bm5        ping ok      Mem: 249M 213M 35M 0B 12M 111M -/+ buffers/cache: 89M 159M
cza44      ping ok      Mem: 249M 153M 95M 0B 15M 66M -/+ buffers/cache: 72M 176M
duer9      ping ok      Mem: 249M 141M 107M 0B 10M 52M -/+ buffers/cache: 78M 170M
feh39      ping ok      Mem: 249M 174M 74M 0B 19M 81M -/+ buffers/cache: 73M 175M
fen42      ping ok      Mem: 249M 215M 33M 0B 26M 107M -/+ buffers/cache: 81M 167M
fl49       ping ok      Mem: 249M 154M 94M 0B 13M 59M -/+ buffers/cache: 81M 167M
frieden    ping ok      Mem: 249M 214M 34M 0B 27M 109M -/+ buffers/cache: 76M 172M
gob34      ping ok      Mem: 249M 212M 36M 0B 26M 106M -/+ buffers/cache: 79M 169M
goz19      ping ok      Mem: 249M 218M 30M 0B 30M 113M -/+ buffers/cache: 74M 174M
gri106     ping ok      Mem: 249M 238M 10M 0B 17M 125M -/+ buffers/cache: 95M 153M
gri121     ping ok      Mem: 249M 159M 89M 0B 11M 69M -/+ buffers/cache: 77M 171M
gs15       ping ok      Mem: 249M 150M 98M 0B 14M 62M -/+ buffers/cache: 73M 175M
hnd1       ping ok      Mem: 249M 218M 30M 0B 29M 113M -/+ buffers/cache: 74M 174M
hw         ping ok      Mem: 249M 212M 36M 0B 23M 98M -/+ buffers/cache: 90M 158M
jed99      ping ok      Mem: 249M 210M 38M 0B 27M 107M -/+ buffers/cache: 75M 173M
kobe4      ping ok      Mem: 249M 210M 38M 0B 26M 103M -/+ buffers/cache: 80M 168M
kr3        ping ok      Mem: 249M 142M 106M 0B 12M 56M -/+ buffers/cache: 73M 175M
kryptaroof ping ok      Mem: 249M 159M 89M 0B 12M 66M -/+ buffers/cache: 79M 169M
lax2       ping ok      Mem: 249M 135M 113M 0B 11M 52M -/+ buffers/cache: 72M 176M
lsg33      ping ok      Mem: 249M 225M 23M 0B 31M 118M -/+ buffers/cache: 75M 173M
mh         ping ok      Mem: 249M 240M 8.9M 0B 5.7M 165M -/+ buffers/cache: 69M 179M
nessus     ping ok      Mem: 249M 132M 116M 0B 7.7M 46M -/+ buffers/cache: 77M 171M
oswald5    ping ok      Mem: 249M 146M 102M 0B 13M 59M -/+ buffers/cache: 74M 174M
ows0       ping ok      Mem: 249M 213M 35M 0B 28M 109M -/+ buffers/cache: 74M 174M
ows2       ping ok      Mem: 249M 174M 74M 0B 19M 82M -/+ buffers/cache: 72M 176M
pbg9       ping ok      Mem: 249M 228M 20M 0B 23M 131M -/+ buffers/cache: 72M 176M
pod41      ping ok      Mem: 249M 207M 41M 0B 24M 107M -/+ buffers/cache: 76M 172M
quell165   ping ok      Mem: 249M 161M 87M 0B 16M 71M -/+ buffers/cache: 74M 174M
veit53     ping ok      Mem: 249M 224M 24M 0B 31M 117M -/+ buffers/cache: 75M 173M
vor203     ping ok      Mem: 249M 217M 31M 0B 29M 113M -/+ buffers/cache: 74M 174M
we16       ping ok      Mem: 249M 208M 40M 0B 27M 106M -/+ buffers/cache: 74M 174M
wuk        ping ok      Mem: 249M 223M 25M 0B 31M 117M -/+ buffers/cache: 74M 174M
jed99r1    ping ok      Mem: 249M 220M 28M 0B 30M 113M -/+ buffers/cache: 76M 172M
ows0r1     ping ok      Mem: 249M 208M 40M 0B 27M 105M -/+ buffers/cache: 75M 173M
test       ping ok      Mem: 249M 218M 30M 0B 28M 111M -/+ buffers/cache: 78M 170M
