### ISSUE TITLE
Adding PerfData for monitoring Metrics with Graphite for Icinga2 and Grafana

### ISSUE THREAD

**Issue by enrutador** [sivel/speedtest-cli#435]
Hi 
I add a simple piece of code for monitoring the metrics in the speedtest.py  in the argunents in the function upload, and Download. Whit this you can see the metrics of you internet bw in yours grafana or  icinga server.
```

    if args.download:
        printer('Testing download speed', quiet,
                end=('', '\n')[bool(debug)])
        speedtest.download(callback=callback)
        printer('Download: %0.2f M%s/s' %
                ((results.download / 1000.0 / 1000.0) / args.units[1],
                 args.units[0]),
                quiet)
        #PERFDATA

        note = 'Speed Download OK: %0.2f M%s' % (((results.download / 1000.0 / 1000.0) / args.units[1], args.units[0]))
        perf_data = 'Speed_Download=%0.2f;;' % (((results.download / 1000.0 / 1000.0)))
        print note + "|" + perf_data
    else:
        printer('Skipping download test')

    if args.upload:
        printer('Testing upload speed', quiet,
                end=('', '\n')[bool(debug)])
        speedtest.upload(callback=callback, pre_allocate=args.pre_allocate)
        printer('Upload: %0.2f M%s/s' %
                ((results.upload / 1000.0 / 1000.0) / args.units[1],
                 args.units[0]),
                quiet)
        #PERFDATA

        note1 = 'Speed Upload OK: %0.2f M%s' % (((results.upload / 1000.0 / 1000.0) / args.units[1], args.units[0]))
        perf_data1 = 'Speed_Upload=%0.2f;;' % (((results.upload / 1000.0 / 1000.0)))
        print note1 + "|" + perf_data1

    else:
        printer('Skipping upload test')
```
![grafana-speed](https://user-images.githubusercontent.com/13056292/31180430-e1236030-a91e-11e7-8c06-0c8f1c4e1990.png)

![icinga2-speed](https://user-images.githubusercontent.com/13056292/31180433-e44212e8-a91e-11e7-84a1-79386b16d0fe.png)

A lot of thanks for your work

**Comment by sivel** [comment]
This is not going to be accepted in this current form. I would entertain a contrib script that does this, but not integrated in the main speedtest.py file. The contrib script would need to live in a contrib directory, and it would also not be included in pip installs. It wold have to be manually downloaded from github.

Please keep us up to date on your progress. I'd like to create a wiki page or similar to link to projects of this type.
