### ISSUE TITLE
API for source-binding

### ISSUE THREAD

**Issue by debrigand** [sivel/speedtest-cli#436]
When run from a command line I can add a `--source` argument to select an IP-address to bind to.
However, when using speetest-cli from another Python script, it seems I have to use something like

    import speedtest
    speedtest.SOURCE = mysource
    speedtest.socket.socket = speedtest.bound_socket
 
i.e. setting some global variables across modules. While that does work, it is hardly the cleanest approach. Having a function in the API that allows setting the source ip address seems much cleaner. Or am I wrong?

**Comment by sivel** [comment]
Eventually I plan on an update that will move source to a different location.  For now, you are doing what is required.
