### ISSUE TITLE
The main try/catch does not respect `quiet` on error

### ISSUE THREAD

**Issue by ajm188** [sivel/speedtest-cli#438]
The problem is that `quiet` does not get passed to the `printer` function here: https://github.com/sivel/speedtest-cli/blob/master/speedtest.py#L1399

**Comment by sivel** [comment]
I don't think I want it to.

**Comment by ajm188** [comment]
Hmm, so consider this use case:

I am running this tool on a periodic basis to collect metrics on my network performance, via cron and appending to a file. One run of the speedtest failed for ... reasons, and now that line is polluting my data file.

Thoughts on best way to work around this?

Of course I could filter those lines with a quick pipe to grep, but I think that in an error case, this tool should either:

1. respect `quiet`/`debug`
1. print to stderr so it can be split out from the normal output

**Comment by ajm188** [comment]
Also, thanks for the prompt reply! :)

**Comment by sivel** [comment]
I'll think about the stderr idea.  For now, you should not use the data that is returned if the exit code is anything other than 0.

**Comment by ajm188** [comment]
That's fair, but this is my cron:

`@hourly speedtest --secure --json >> /some/file.txt`

There doesn't seem to be a convenient way to switch on the status code?
I _could_ do something like
`@hourly data=$(speedtest --secure --json) && echo $data >> /some/file.txt` but that feels gross to me as a user.

**Comment by sivel** [comment]
This should be resolved in the no-globals branch that I hope to merge to devel soon as the base of the next release.

And by resolved, I mean that those messages should go to stderr.
