### ISSUE TITLE
Printing csv-headers with "--csv-header" ignores --csv-delimiter

### ISSUE THREAD

**Issue by Kafkalasch** [sivel/speedtest-cli#440]
Hello,

just wanted to report a minor issue:

When printing csv-headers with --csv-headers the delimiter passed by --csv-delimiter is ignored.

`> speedtest --csv-delimiter ";" --csv-header`
`Server ID,Sponsor,Server Name,Timestamp,Distance,Ping,Download,Upload`

Normal output (without the argument "--csv-header") works fine.

I am using speedtest v. 1.0.6.

**Comment by sivel** [comment]
This is expected. The idea is that you should print the CSV header piped into a file only once, and all future runs would not use that option.

**Comment by Kafkalasch** [comment]
Yeah, I understand that. But if I need a csv-file with semicolons as delimiters I also need a header with semicolons as delimiters. Currently, I can only print a header with the default commas and have to replace them manually afterwards.
