### ISSUE TITLE
Speed results totally wrong

### ISSUE THREAD

**Issue by KurumoAkane** [sivel/speedtest-cli#444]
Hi, i do not know why, but speedtest-cli give me totally wrong results respect test made on speedtest.net website..

I've tried both with specific server (same on the website) and without giving an id...
But still wrong results..

There's a problem with APIs?

Heres a screenshot:
![image](https://user-images.githubusercontent.com/12990276/31864789-25e55522-b764-11e7-84e0-8075ff7c51fe.png)

**Comment by roe1974** [comment]
Same Prob here ... how did you solve it ???
Richard
