### ISSUE TITLE
Custom Server Support

### ISSUE THREAD

**Issue by stevezau** [sivel/speedtest-cli#445]
Hi,

Any there any plans to support custom speedtest servers?

IE: I'd like to test again the TPG Speedtest server @ http://tpg.speedtestcustom.com/ which uses http://speedtest.tpg.com.au:8080/

**Comment by sivel** [comment]
This application only supports custom speedtest mini.  It does not support the version of speedtest at that URL.

There are additionally no plans to implement netguage or speedtest custom functionality.

**Comment by AndrewSav** [comment]
But mini is discontinued...

**Comment by sivel** [comment]
This application does not support, in any form, the protocol needed to test against Speedtest Custom.  It still uses the legacy HTTP testing functionality.

I have an experimental client which supports that protocol, but does not support custom servers yet: https://github.com/sivel/speedtest
