### ISSUE TITLE
Not all Speedtest Servers are listed (speedtest-cli --list)

### ISSUE THREAD

**Issue by rsaanon** [sivel/speedtest-cli#447]
Seems like not all servers are listed with the --list parameter.  

For example, Searching for Server ID: 9816 on https://www.speedtestserver.com/ returns one result; however, if I do a speedtest-cli --list, this list does not contain the server with ID 9816.

Running speedtest-cli --server 9816 displays error:  "No matched servers: 9816"

Question is are the server list retrieved from each time from the speedtest.net each time or are these cached.  If cached, how do you refresh the list?

**Comment by sivel** [comment]
speedtest.net lists that as a server that shouldn't be used.  As such, it should be removed from all operations.

I'm guessing there may be a bug that allows it to be listed, regardless of speedtest.net indicating it shouldn't be used.

**Comment by sivel** [comment]
Ok, this isn't a bug.  speedtest-cli is properly filtering out these servers. I'm not sure what https://www.speedtestserver.com does, but it is getting the server list somehow and not filtering out the specified ignored servers.
