### ISSUE TITLE
Tests are inconclusive

### ISSUE THREAD

**Issue by auras** [sivel/speedtest-cli#451]
This tool uses the random jpg as the payload which for some reason it's accelerated in my cable setup.

When using a download payload like this: http://speed.syseleven.net:5060/download?nocache=f50c4aa4-601f-43da-a281-df1de8ee53dc&size=2500000 the results are very different and way lower.

**Comment by sivel** [comment]
I'm not even sure what this means, but this tool attempts to mimic speedtest.net by using their infra and methods of testing.

**Comment by auras** [comment]
Speedtest.net doesn't use that kind of test, not where I live, in Germany, at least it doesn't.

See this: https://imgur.com/a/cCjZN

The 1st test is the kind speedtest-cli uses and the 2nd one is the kind speedtest.net uses. The 2nd one is actually my real bandwidth right now. I've tested on speedtest.net also and I never get close to the speeds reported by speedtest-cli. I'm guessing the jpg mode uses some form of compression to artificially inflate the numbers.

**Comment by auras** [comment]
Check my fork for the correct method: https://github.com/auras/speedtest-cli

**Comment by auras** [comment]
And now I get why I got so vastly different results. My ISP, Kabel Deutschland is prioritizing jpg downloads so that the old speedtests would deceive the users into thinking they have a higher bandwidth than they really do. https://imgur.com/a/u9Epg
