### ISSUE TITLE
Upload fail.

### ISSUE THREAD

**Issue by OXEDAN1337** [sivel/speedtest-cli#457]
Retrieving speedtest.net configuration...
Testing from CoProSys a.s. (ip-address)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Tlapnet s.r.o. (Caslav) [29.61 km]: 30.022 ms
Testing download speed................................................................................
Download: 34.55 Mbit/s
Testing upload speedTraceback (most recent call last):
  File "speedtest.py", line 1508, in <module>
    main()
  File "speedtest.py", line 1498, in main
    shell()
  File "speedtest.py", line 1470, in shell
    speedtest.upload(callback=callback, pre_allocate=args.pre_allocate)
  File "speedtest.py", line 1151, in upload
    data.pre_allocate()
  File "speedtest.py", line 551, in pre_allocate
    (chars * multiplier)[0:int(self.length) - 9]
MemoryError

https://s2.postimg.org/w80uyz2op/error_speedtest.jpg
How can I fix it?

**Comment by sivel** [comment]
Read the README or use `--help`
