### ISSUE TITLE
Difference in result between speedtest-cli and speedtest.net web app

### ISSUE THREAD

**Issue by hiigami** [sivel/speedtest-cli#458]
Why do I get such a gap in the results between the 2? 

speedtest.net web app always show a faster upload / download speeds.

**Comment by hiigami** [comment]
Sorry, I just so the same thing on an earlier [issue](https://github.com/sivel/speedtest-cli/issues/370).

I am closing this one.

**Comment by auras** [comment]
Use this fork: https://github.com/auras/speedtest-cli It uses the same tests as speedtest.net
