### ISSUE TITLE
Skip printing "skipping download test" when outputting json

### ISSUE THREAD

**Issue by jorisroovers** [sivel/speedtest-cli#461]
Great tool :)

When using ```--no-download``` or ```--no-upload``` it would be good that the message ```Skipping download/upload test``` is not printed or printed to stderr instead of stdout when the output is set to csv or json.

That would make it possible to easily manipulate the output by piping it into other commands like ```jq```.

Example:
```
$ speedtest-cli --json --no-download | jq ".upload"
# This currently gives the following error because of the "Skipping download test" message
parse error: Invalid numeric literal at line 1, column 9
```

**Comment by sivel** [comment]
I've committed the fix to the `no-globals` branch which will become the next major release. I need to plan that release soon. If it's not going to be ready soon-ish, I'll look to cherry pick https://github.com/sivel/speedtest-cli/commit/fa2e15ee08b0c55930bb7a251784ca7b2c529c1c into a new bugfix release.

Feel free to test with the `no-globals` branch: https://raw.githubusercontent.com/sivel/speedtest-cli/no-globals/speedtest.py
