### ISSUE TITLE
Incorrect speeds reported

### ISSUE THREAD

**Issue by richard-kimber** [sivel/speedtest-cli#468]
I'm on a 200 Mbps tariff and am currently getting 185 Mbps according to the Which? online tool, and 171 Mbps according to my attached Fingbox

speedtest.py gives a download speed of e.g.

 0.53 Mbps and an upload speed of 0.83 Mbps
 1.58 MBPS and an upload speed of 1.03 Mbps

**Comment by richard-kimber** [comment]
Could you give some sort of comment?  I'm baffled by the r3esults

**Comment by prbipul** [comment]
you should check the speedtest host it is connecting to and try with other speedtest hosts.
speeds vary on the test server hosts you're connecting to.
