### ISSUE TITLE
Use HTTPS by default

### ISSUE THREAD

**Issue by ZJaume** [sivel/speedtest-cli#471]
The title explains itself. Could the script use HTTPS by default instead of HTTP? I think the `--secure` argument could be changed for another one called `--no-secure` for use HTTP.

**Comment by sivel** [comment]
This was done originally, and it created many problems for users.  I honestly didn't expect it to be a problem, but due to the large number of complaints, the logic was flipped.

I have no intention on making secure the default in the near future.
