### ISSUE TITLE
ValueError: could not convert string to float: None

### ISSUE THREAD

**Issue by virtualghetto** [sivel/speedtest-cli#472]
Using master branch commit: 20e5d12a5caa015653564c31f7845f1493148bed

./speedtest.py
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "./speedtest.py", line 1508, in <module>
    main()
  File "./speedtest.py", line 1498, in main
    shell()
  File "./speedtest.py", line 1401, in shell
    speedtest = Speedtest()
  File "./speedtest.py", line 743, in __init__
    self.get_config()
  File "./speedtest.py", line 840, in get_config
    self.lat_lon = (float(client['lat']), float(client['lon']))
ValueError: could not convert string to float: None

**Comment by sivel** [comment]
Please try with the devel branch and let me know how that works.

**Comment by virtualghetto** [comment]
Using branch devel commit: 48a3d33ae478e218a5548a484b07e87413cc0c27

./speedtest.py 
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "./speedtest.py", line 1834, in <module>
    main()
  File "./speedtest.py", line 1823, in main
    shell()
  File "./speedtest.py", line 1720, in shell
    secure=args.secure
  File "./speedtest.py", line 1003, in __init__
    self.get_config()
  File "./speedtest.py", line 1116, in get_config
    self.lat_lon = (float(client['lat']), float(client['lon']))
ValueError: could not convert string to float: None

**Comment by sivel** [comment]
Please run with `--debug` and provide the output.

**Comment by virtualghetto** [comment]
I tried this on debian and ubuntu, and I got the same error.
Each machine is on a different network and location.
Attached is the debug output from the ubuntu machine using the devel branch.

[debug.txt](https://github.com/sivel/speedtest-cli/files/1613318/debug.txt)

**Comment by sivel** [comment]
I could potentially add some guards there, however speedtest.net seems to have no indication where your IP address originates from:

```
<client ip="137.74.73.179" lat="None" lon="None" isp="OVH SAS" isprating="3.7" rating="0" ispdlavg="0" ispulavg="0" loggedin="0" country="None" />
```

Without that data, this tool would be unable to properly validate closest servers, and thus would not proceed.  So short of an error, I doubt there is anything useful I could do, until speedtest.net starts returning valid information for your location.

There has been a request to allow providing a lat/lon via the command line, potentially, that would allow you to get further, should it be implemented.

**Comment by Nowaker** [comment]
Why not display a human readable error instead?

**Comment by Nowaker** [comment]
Yes! Good stuff. 😀
