### ISSUE TITLE
Ping time incorrect

### ISSUE THREAD

**Issue by robdejonge** [sivel/speedtest-cli#474]
```
% date ; python speedtest.py --server 1536 --secure --simple ; date
Mon Jan 15 14:41:10 +07 2018
Ping: 1200028.614 ms
Download: 43.76 Mbit/s
Upload: 20.07 Mbit/s
Mon Jan 15 14:41:34 +07 2018
```

Out of the servers I commonly use, this is the only server where this issue happens. But it seems to be happening consistently. Can anyone confirm?

**Comment by sivel** [comment]
That value is an indication that 2 out of the 3 attempts to test latency failed.

In the code, a failure to retrieve the latency test, will result in a value of 3600s being used, to help offset a server that is unstable.

The calculation then follows something like:

```python
>>> latencies = [0.171684, 3600, 3600]
>>> total = sum(latencies)
>>> latency = (total / 6) * 1000
>>> latency
1200028.614
```

Where `0.171684` would have been a successful attempt.

If you run with `--debug`, you would see an `ERROR` indicated during the latency tests, that may provide an answer as to what exactly is happening.
