### ISSUE TITLE
ModuleNotFoundError: No module named '__builtin__'

### ISSUE THREAD

**Issue by MattIPv4** [sivel/speedtest-cli#478]
Fresh install of Python 3.6.4 on Windows Server 2016.
Seems that the import of __builtin__ isn't being captured by the importerror except on line 145?
Any fix?

**Comment by MattIPv4** [comment]
Full traceback: https://i.dabbitpri.me/8ce928c9383603aad081.txt

**Comment by sivel** [comment]
Your actual traceback is a problem with wrapping `stdout`, nothing to do specifically with `__builtin__`

```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\speedtester.py", line 13, in <module>
    __import__('speedtest')
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\speedtest.py", line 166, in <module>
    _py3_utf8_stdout = _Py3Utf8Stdout()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\speedtest.py", line 154, in __init__
    buf = FileIO(sys.stdout.fileno(), 'w')
io.UnsupportedOperation: fileno
```

**Comment by MattIPv4** [comment]
That's also an internal issue?

**Comment by sivel** [comment]
Potentially.  I don't have a windows machine to test this on currently.  So it likely won't be addressed until such a time that I can get a windows test environment.

**Comment by sivel** [comment]
I cannot duplicate this on win2016.  How is your `speedtester.py` being executed?

**Comment by MattIPv4** [comment]
```
‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌import datetime, pip, platform

# Import/Install requests
try:
    __import__('requests')
except ImportError:
    pip.main(['install', 'requests'])
finally:
    import requests

# Import/Install speedtest-cli
try:
    __import__('speedtest')
except ImportError:
    pip.main(['install', 'speedtest-cli'])
finally:
    import speedtest

# Begin speed test
print("Commencing speedtest")
st = speedtest.Speedtest()
st.get_servers([])
st.get_best_server()
st.download()
st.upload()

# Get results
results = st.results.dict()
upload = results['upload']
download = results['download']
ping = results['ping']

# Print data
print("Device: {}\nUpload: {}\nDownload: {}\nPing: {}\n".format(
    platform.node(),
    upload,
    download,
    ping
))

# Create new data
d = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
newdata = {'device': platform.node(), 'datetime': d, 'ping': ping, 'download': download, 'upload': upload}

# Post data
r = requests.post('[redacted]', data = newdata)
print(r.text)
```

Tried via IDLE and Task Scheduler, both result in the same

**Comment by sivel** [comment]
In the example of use in IDLE, this comes down to stdout being replaced with an object that doesn't support all of the functionality of `sys.stdout`.  Not sure about the Task Scheduler.

But I've just pushed a change to devel that should hopefully resolve the issue.

Please try: https://raw.githubusercontent.com/sivel/speedtest-cli/devel/speedtest.py

**Comment by MattIPv4** [comment]
This has indeed fixed the issue. Any eta for when this will be published to pip?

**Comment by sivel** [comment]
I'll try to get to it soon.  I've been waiting your confirmation.

**Comment by MattIPv4** [comment]
Oh sorry, had completely forgot about this until today when I deployed a new WS2016 again. Ty for the help and quick fix though.
