### ISSUE TITLE
--csv doesnt output share result

### ISSUE THREAD

**Issue by MesserMesut** [sivel/speedtest-cli#483]
`pi@speedtestpi:~ $ speedtest --csv-header

Server ID,Sponsor,Server Name,Timestamp,Distance,Ping,Download,Upload,Share,IP Address

pi@speedtestpi:~ $ speedtest --csv

5351,UPC,Vienna,2018-02-20T19:33:16.598968Z,2.805302137039485,32.028,92979778.19286498,10236019.287158411,,80.xxx.xxx.xxx

pi@speedtestpi:~ $`
notice the ,, before the IP. according to csv-header there should be "Share", which i guess means the share URL?

**Comment by sivel** [comment]
To include the share URL, you must also supply `--share`.

**Comment by MesserMesut** [comment]
pi@speedtestpi:~ $ speedtest --csv --share
15819,Timewarp IT Consulting GmbH,Vienna,2018-02-20T19:49:57.604270Z,2.790089884789666,33.89,34908598.202725366,2908073.192604583,,80.110.109.207
pi@speedtestpi:~ $ speedtest --share --csv
5351,UPC,Vienna,2018-02-20T19:50:37.525515Z,2.805302137039485,31.418,96399619.0772168,10020753.165665096,,80.110.109.207

am I doing something wrong here?

**Comment by sivel** [comment]
It looks like there may be an issue in some logic.  I'll take a closer look.

**Comment by sivel** [comment]
This has been resolved in the devel branch and will be part of a 2.0.1 release.
