### ISSUE TITLE
Store data in database

### ISSUE THREAD

**Issue by Disane87** [sivel/speedtest-cli#484]
Is it possible to store the data in a database, mysql for example?

**Comment by sivel** [comment]
Sure.  You have a few options.

1) Use one of the machine parsable output formats (`--json` or `--csv`), execute speedtest-cli, parse the results, insert into a DB
2) Use the [Python API](https://github.com/sivel/speedtest-cli/wiki#python-api) directly, get the results, insert into a DB

**Comment by Disane87** [comment]
Thank you, the solution is totally obvious. Now I parse the return of the csv and push the values in the database. Thank you for pushing me into the right direction.
