### ISSUE TITLE
Check Speedtest with Icinga 2

### ISSUE THREAD

**Issue by samjaseu** [sivel/speedtest-cli#488]
Dear sivel,

thanks for your incredible work =)

I'm no python-programmer (yet :-D) but I did some minor changes to use speedtest-cli for Icinga2 monitoring - would be grateful if you could help me or include it in your script ?
I simply should output the "--simple" output and some perfdata for eg. grafana.

What I have so far:

~$ vi speedtest-cli  
`parser.add_argument('--icinga2', action='store_true', default=False,`
`                        help='Suppress verbose output, only show basic '  `
`                             'information with perfdata for Icinga2')  `

`if args.simple or args.icinga2 or args.csv or args.json:  `
`        quiet = True  `
`    else:  `
`        quiet = False  `

`if args.simple or args.icinga2:  `
`        printer('Ping: %s ms\nDownload: %0.2f M%s/s\nUpload: %0.2f M%s/s' %  `
`                (results.ping,  `
`                 (results.download / 1000.0 / 1000.0) / args.units[1],  `
`                 args.units[0],  `
`                 (results.upload / 1000.0 / 1000.0) / args.units[1],  `
`                 args.units[0]))  `

`if args.icinga2:  `
`        #printer('|ping=%s;10;20\n|download=%0.2f;200;100\n|upload=%0.2f;200;100' %  `
`        printer('|ping=%s\n|download=%0.2f\n|upload=%0.2f' %  `
`                (results.ping,  `
`                 results.download / 1000.0 / 1000.0,`  
`                 results.upload / 1000.0 / 1000.0))  `

~$ ./speedtest-cli --icinga2  
`Ping: 5.108 ms  `
`Download: 321.87 Mbit/s  `
`Upload: 644.90 Mbit/s  `
`|ping=5.108  `
`|download=321.87  `
`|upload=644.90`

@Icinga Director:
![image](https://user-images.githubusercontent.com/25737482/36780616-c8c2b112-1c73-11e8-8aa8-1a8d93a9299d.png)

![image](https://user-images.githubusercontent.com/25737482/36780622-cc3ed79e-1c73-11e8-886f-7b85c5de8686.png)

![image](https://user-images.githubusercontent.com/25737482/36780626-ce904316-1c73-11e8-86a6-43377b48ff84.png)

@Icingaweb2:
![image](https://user-images.githubusercontent.com/25737482/36780640-d2404a92-1c73-11e8-87be-d285bbd4ebeb.png)

@Grafana:
![image](https://user-images.githubusercontent.com/25737482/36781077-21247376-1c75-11e8-99ff-1208f662a03a.png)

What do I need to have but cannot manage with my no-python-skills:

- [ ] adding parameters for warning/critical Limits for Ping, Download and Upload, as you see on ´#printer('|ping=%s;10;20\n|download=%0.2f;200;100\n|upload=%0.2f;200;100' % ´ I hard-coded it but I'm not able to check if Ping over limit or Up-/Download are under limits.
- [ ] also exit codes for Icinga2 telling if a warning / critical / unknown state happened would be nice.

Thanks in advance,
best wishes

Andreas

**Comment by sivel** [comment]
Thank you for the issue.

The recommended way to achieve this, to integrate with additional external services, is to utilize the python API, and implement your own callable.

I do not plan on accepting features like this directly into the main code for speedtest-cli, but may be open to either a contrib directory containing these small scripts, or listing them on a wiki page.

**Comment by samjaseu** [comment]
Hi.

And theres no chance you could help me a bit with this ?

regards
