### ISSUE TITLE
wrong server chosen with --server parameter

### ISSUE THREAD

**Issue by phit42** [sivel/speedtest-cli#489]
If I provide the serverid of the server that would currently be chosen by get_best_server as well (and it is up and running of course), it goes to a completely wrong server half way around the world?

> root@DiskStation:/volume1/Daten/scripts# ./speedtest.sh --verbose
> Retrieving speedtest.net configuration...
> Testing from Unitymedia (95.222.26.199)...
> Retrieving speedtest.net server list...
> Selecting best server based on ping...
> Hosted by Spacken.net (Hagen) [98.87 km]: 26.086 ms
> Testing download speed................................................................................
> Download: 293.39 Mbit/s
> Testing upload speed................................................................................................
> Upload: 20.23 Mbit/s

 _
> root@DiskStation:/volume1/Daten/scripts# ./speedtest.sh --list | grep Spacken
> 15431) Spacken.net (Hagen, Germany) [98.87 km]

 _
> root@DiskStation:/volume1/Daten/scripts# ./speedtest.sh --fav 15431
> Retrieving speedtest.net configuration...
> Testing from Unitymedia (95.222.26.199)...
> Retrieving speedtest.net server list...
> Retrieving information for the selected server...
> Hosted by Ayera Technologies, Inc. (Modesto, CA) [8944.84 km]: 197.459 ms
> Testing download speed................................................................................
> Download: 68.91 Mbit/s
> Testing upload speed................................................................................................
> Upload: 15.51 Mbit/s

Note: speedtest.sh is just a wrapper script from https://github.com/rsvp/speedtest-linux

**Comment by sivel** [comment]
You should really report this to https://github.com/rsvp/speedtest-linux

That project hard codes the favorite server to 1335:

https://github.com/rsvp/speedtest-linux/blob/6d85106d1274217589f09672ea1e505b0b2aa720/speedtest#L90-L92

It does not appear to accept a supplied server from the CLI as the favorite.

**Comment by phit42** [comment]
You are absolutely right. My bad. Didn't read the script properly. Thank you.
