### ISSUE TITLE
'apt install speedtest-cli' does not get the latest version on Ubuntu 16.04

### ISSUE THREAD

**Issue by 19wolf** [sivel/speedtest-cli#493]
Not sure if this counts as an 'issue' but the Ubuntu PPA version is not updated and does not include the --csv option. Installing from the github page after installing the ppa has lead to many issues for a novice user.

**Comment by sivel** [comment]
I do not manage any ubuntu ppa of speedtest-cli.  You would need to contact the maintainer of that PPA.
