### ISSUE TITLE
Server list missing entries on latest speedtest-cli

### ISSUE THREAD

**Issue by jnfern** [sivel/speedtest-cli#494]
One of my closest servers is provided by 'Virgin Media' with server ID 3726 which I can find in https://www.speedtestserver.com/ and is usable via the speedtest.net website (based on provider and location, I can't see how to verify the actual ID).

If I use speedtest-cli that is available via apt on Ubuntu this also appears in the list of valid servers:
me@adlet:$ speedtest-cli --version
0.3.4
me@adlet:$ speedtest-cli --list | head
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
3726) Virgin Media (Bromley, Great Britain) [5.85 km]
 226) Structured Communications (London, Great Britain) [9.70 km]
3728) Virgin Media (London, Great Britain) [9.70 km]
2789) Vodafone UK (London, Great Britain) [9.70 km]
11123) Spitfire Network Services (London, United Kingdom) [9.70 km]
11547) KamaTera INC (London, United Kingdom) [9.70 km]
6115) Cybersmart Pty Ltd (London, Great Britain) [9.70 km]

If I use the latest version (installed via pip) then the servers are different:
me@Centaur:$ speedtest-cli --version
2.0.0
me@Centaur:$ speedtest-cli --list | head
Retrieving speedtest.net configuration...
  226) Structured Communications (London, Great Britain) [9.70 km]
 2789) Vodafone UK (London, Great Britain) [9.70 km]
11123) Spitfire Network Services (London, United Kingdom) [9.70 km]
11547) KamaTera INC (London, United Kingdom) [9.70 km]
 6115) Cybersmart Pty Ltd (London, Great Britain) [9.70 km]
10262) Interoute VDC (London, Great Britain) [9.70 km]
 8066) Coreix Ltd (London, Great Britain) [9.70 km]

As the server isn't listed in version 2.0, I can't use it with --server (ERROR: No matched servers: 3726)

I've seen a previous bug that suggested a similar issue was because the server isn't valid - however there was no information about how to show if the server is valid (and it does work via the web interface on speedetest.net and on the Ubuntu version 0.3.4 of speedtest-cli).

Any ideas?

**Comment by sivel** [comment]
speedtest.net is indicating in their config that speedtest-cli uses, that `3726` should be ignored currently.

I don't know how speedtestserver.com is generating the list it displays, but it must not be respecting the `ignoreids` setting from speedtest.net.

**Comment by gavtaylor** [comment]
cant see anything in the code that would cache it, so wondered if its the useragent, it is.

I tweaked `build_user_agent()` to return my current Firefox agent and the test runs

they're parsing `speedtest-cli` in the useragent and setting servers to ignore. cheeky so and so's.

**Comment by sivel** [comment]
> they're parsing speedtest-cli in the useragent and setting servers to ignore. cheeky so and so's.

I am trying to be a good steward and not try and trick anyone. This is an unofficial client, and they are of course entitled to do that kind of thing.

I've been debating exposing an argument that could allow a person to specify their own custom UA, but haven't gotten around to it yet.  I'll try and add something for that soon.

**Comment by gavtaylor** [comment]
yeah of course they are, meant cheeky in jovial sense

ability to set a custom agent would be helpful, although if they are purposely wanting to block this UA from certain servers (probably to reduce load from automated testing) then they may not be pleased if you add support for changing the agent to bypass that.

want me to pop a new issue in for a custom agent feature request? couldnt see one. will keep the discussion off this closed issue.

Ive tweaked my ansible for now to replace the UA string on the box I test with.
