### ISSUE TITLE
[question] What upload, download, bytes_received and bytes_sent are mean?

### ISSUE THREAD

**Issue by XnIcRaM** [sivel/speedtest-cli#496]
I found in results.dict() **download**, **upload**, **bytes_sent** and **bytes_received** which one is value of my upload and download and whats the other values are?

**Comment by XnIcRaM** [comment]
another question is in this API function to convert bytes to human redable values (kbps, Mbps etc)?

**Comment by sivel** [comment]
The other values are the number of bytes sent and received as part of the testing.  There is no public function for converting bytes to human readable values.

**Comment by XnIcRaM** [comment]
so simple :) 👍
