### ISSUE TITLE
Arbitrary endpoint

### ISSUE THREAD

**Issue by charlesreid1** [sivel/speedtest-cli#501]
I know this package bills itself as using speedtest.net, but would it be possible to write a speedtest.net "clone" so that speedtest-cli could use that as an arbitrary endpoint? (This might open up a new use case for speedtest-cli: measuring speed between two specific locations.)

**Comment by sivel** [comment]
Currently this app only supports speedtest.net and speedtest mini installations (see --mini).

I am doing work to support speedtest custom, which would allow for potential speedtest custom clones to work.
