### ISSUE TITLE
"Error: 1" on Raspberry

### ISSUE THREAD

**Issue by 6hardmod9** [sivel/speedtest-cli#502]
Hi everybody,
I found speedtest-cli today which works really great on my vServer.
Unfortunately I can't make it run on my Raspi:

`root@raspberrypi:/home/pi# speedtest-cli
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: 1`

I tried it with a specific server as well - which I had to list on the vserver as this options doesn't work, too.

Does anybody know how to fix?

BTW the Raspi has 2 active connections: LAN + openVPN. So I tried to bind it with --source - the same.

Regards

**Comment by sivel** [comment]
You can try running with `--debug` which may provide additional information.  Also, based on seeing `ERROR: 1`, that may indicate you are also running an older version, and should look into upgrading.

**Comment by lucasff** [comment]
In my Raspberry works just fine. It's something on your setup.
