### ISSUE TITLE
Specify size upload and download 

### ISSUE THREAD

**Issue by narendranaren14** [sivel/speedtest-cli#504]
Hi,

Query! What is the size of upload and download data size used for speed measurement? Can it be possible to test the speed with specific data size like 1MB, 5MB instead of default?

Regards
Narendra NA

**Comment by sivel** [comment]
https://github.com/sivel/speedtest-cli/blob/master/speedtest.py#L1086

There are no plans to allow this to be configurable

**Comment by narendranaren14** [comment]
Thanks @sivel ! Appreciate the response. I need to understand bit more. Is download data size is also 32768, 65536, 131072, 262144, 524288, 1048576, 7340032? Does the script upload/download the data of the size listed and measure speed for each time, provide the average speed? If I want to choose a particular data size, what are changes required in the script for both upload and download?
