### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by chimcen** [sivel/speedtest-cli#507]
Hi,

i want to execute the script serval times a day and append the output to a textfile - no problem so far - but actual there is no timestamp showing in the output from speedtest.py... only lookin like this:
Retrieving speedtest.net configuration...
Testing from Vodafone DSL (88.72.232.100)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by InterNetX GmbH (Munich) [11.75 km]: 29.063 ms
Testing download speed................................................................................
Download: 47.13 Mbit/s
Testing upload speedRetrieving speedtest.net configuration...
Testing from Vodafone DSL (88.72.232.100)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Net-D-Sign GmbH (Garching) [20.20 km]: 25.775 ms
Testing download speed................................................................................
Download: 47.92 Mbit/s
Testing upload speed...............................................................................................
.Upload: 9.18 Mbit/s

Is it possible to integrate a timestamp added to this file in the first line of each measurement?

**Comment by sivel** [comment]
Utilize the machine parsable formats to get a timestamp (`--json` or `--csv`)

Otherwise, run the date command before the test.

**Comment by chimcen** [comment]
Thank you

> Otherwise, run the date command before the test.
... no idea how to do this... :(
