### ISSUE TITLE
the test is dependent on DNS resoultion speed. 

### ISSUE THREAD

**Issue by washuu** [sivel/speedtest-cli#509]
I got a case, when the download/upload speed was about 13 MBytes/s  (about 100MBit/s), but the speed test showed about 1% of the values. I tracked this down to the DNS server, which was resolving the DNS queries in about 5 seconds. After adding several speedtest servers and their IPs to the /etc/hosts, the test started showing the real speeds. 

Of course, the DNS was a culprit, but this program should measure the real download/upload speed, without the DNS resolution time in the calculations.

**Comment by sivel** [comment]
You aren't incorrect.  However, python offers no way to cache DNS responses.  As you found, this is a local configuration issue, and that is something you will need to resolve external to speedtest cli.  Perhaps look into something like nscd.

**Comment by washuu** [comment]
Sure, I understand that. But the phase of resolving the IPs can be done at the beginning, and the tests can use the IPs only for increased precision.
