### ISSUE TITLE
log speedtests

### ISSUE THREAD

**Issue by USRGH** [sivel/speedtest-cli#524]
Hello,
is there any way to log speedtest results?

currently using bash script (st.bash) which contents command ./speedtest-cli

Any way to save results into 1 log file?
Thank you

**Comment by smartbsd** [comment]
I don't see a log facility on the documentation but I think implementing logging seems feasible and easy by using the logging module but your solution and appending results should do the magic. 

BTW I am just another user trying to learn from speedtest-cli code.

**Comment by sivel** [comment]
speedtest-cli supports 2 machine parsable formats: `--json` and `--csv`

Execute it with one of those flags and pipe the results to a file.
