### ISSUE TITLE
Malformed speedtest.net configuration ERROR

### ISSUE THREAD

**Issue by rastosz** [sivel/speedtest-cli#526]
Hello,

i have stumbled upon an error when i try to start the speedtest:
C:\speedtest-cli-2.0.1>python speedtest.py
Retrieving speedtest.net configuration...
ERROR: Malformed speedtest.net configuration: mismatched tag: line 59, column

I'm using python version 3.5.0

Do you know, what might be the problem?

Best Regards,

Rasto

**Comment by sivel** [comment]
The XML data that speedtest.net is returning is malformed.  They usually fix this within a few days.
