### ISSUE TITLE
What format do downlad and upload return?

### ISSUE THREAD

**Issue by AlexSnell232** [sivel/speedtest-cli#535]
Hi there,
When using this with the Python API, what format does running "`s.download()`" and "`s.upload()`" return, and how can this be calculated to get Mb/s?
Alex.

**Comment by sivel** [comment]
bits/s:

https://github.com/sivel/speedtest-cli/blob/72ed585c6f9d19b39a80e0c9364592095d070f62/speedtest.py#L1497-L1499

Mb/s (Megabits/s):

```
s.download() / 1000**2
```

MB/s (Megabytes/s):

```
s.download() / 8 / 1000**2
```

**Comment by AlexSnell232** [comment]
Thank you very much Sivel, this tool is extremely useful. I am finding my way with Python, but this is easy to use.
