### ISSUE TITLE
account support

### ISSUE THREAD

**Issue by skapytek** [sivel/speedtest-cli#538]
Hello,
is it possible to add account support for speedtest.net?
Would be awesome to collect and archive the download statistics.
Or is there any other possible solution for this?

kind regards

**Comment by sivel** [comment]
This has been attempted several times.  The functionality has been fragile and hasn't worked for any extended period of time.  As such, I recommend using some other tracking technique, such as using the `--csv` or `--json` outputs, and tracking yourself.
