### ISSUE TITLE
--csv

### ISSUE THREAD

**Issue by skapytek** [sivel/speedtest-cli#540]
`speedtest-cli --server 17392 --secure --share --csv`
isnt working
without the `--csv` its working

regards

**Comment by sivel** [comment]
"isn't working" is not a sufficient explanation of the problem for anyone to hope to resolve this.

When I run that command, I get:

```
$ speedtest-cli --server 17392 --secure --share --csv
17392,myLoc managed IT AG,Dusseldorf,2018-08-24T14:46:34.062296Z,8448.92267704374,198.072,56386845.420030974,26554310.293668218,http://www.speedtest.net/result/7578141725.png,1.2.3.4
```

Which is the expected functionality.
