### ISSUE TITLE
Error: Malformed Server List V2.0.2 Ubuntu 18.04LTS

### ISSUE THREAD

**Issue by mcheavens** [sivel/speedtest-cli#541]
Three installs yesterday from scratch - All have the same error message. My older installs with version 1.0.3 on 16.04 work just fine.
- I have searched but not found a reason.

Mark
[root@co-needles /] # uname -a
Linux co-needles 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x
86_64 x86_64 x86_64 GNU/Linux
[root@co-needles /] # speedtest-cli --version
2.0.2
[root@co-needles /] # speedtest-cli
Retrieving speedtest.net configuration...
Testing from SurfControl (208.87.239.180)...
Retrieving speedtest.net server list...
ERROR: Malformed speedtest.net server list: syntax error: line 1, column 15
[root@co-needles /] #

**Comment by sivel** [comment]
This means that the data that speedtest.net is sending is invalid XML. It happens from time to time, they usually fix it within a few days.  You might also try adding `--secure` to the command, sometimes that will use a different server not affected by the malformed XML.

**Comment by mcheavens** [comment]
--secure was the solution!!!

Thank you very much. I hope with the exact error anyone else searching for it will find the answer.

Mark
