### ISSUE TITLE
Source Parameter not Working

### ISSUE THREAD

**Issue by bladebeam** [sivel/speedtest-cli#543]
I'm trying to force speedtest-cli to use my eth0 connection instead of wlan0 (both are connected).  I use "speedtest-cli --source x.x.x.x" where x.x.x.x is the static IP of my eth0.  It either returns "cannot retrieve configuration" or "cannot open URL".   I can ping my own interface just fine.

Second issue is that when running my script (speedtest.py and speedtest-cron.sh) for speedtest-cli --simple it works fine.  But when the Rpi uses a cron job to output to a local csv file it outputs "0" for both download and upload.  There is zero difference in the code being run except that running manually gives good speed and allowing the cron to run it ouputs "0" or close to zero.

**Comment by sivel** [comment]
> I'm trying to force speedtest-cli to use my eth0 connection instead of wlan0 (both are connected). I use "speedtest-cli --source x.x.x.x" where x.x.x.x is the static IP of my eth0. It either returns "cannot retrieve configuration" or "cannot open URL". I can ping my own interface just fine.

This indicates that your eth0 is not configured with proper routes to allow communication outside of your subnet.



> Second issue is that when running my script (speedtest.py and speedtest-cron.sh) for speedtest-cli --simple it works fine. But when the Rpi uses a cron job to output to a local csv file it outputs "0" for both download and upload. There is zero difference in the code being run except that running manually gives good speed and allowing the cron to run it ouputs "0" or close to zero

Unsure why cron would impact anything, if it is, that sounds like a local configuration issue.

**Comment by bladebeam** [comment]
Thanks for the reply.  Focusing on the source issue, what would be incorrect about my eth0 config?  It's set to static in the Interfaces file, with the correct default gateway and mask.  It does work fine with wlan0, which would seem to support your assertion.  Any idea what's wrong with my eth0, given that it works fine for access via SSH or VNC but not with speedtest-cli?

auto wlan0
auto eth0
allow-hotplug wlan0
iface wlan0 inet dhcp
wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
#post-up iw wlan0 set power_save off
iface default inet dhcp
iface eth0 inet static
address 192.168.101.157
netmask 255.255.255.0
gateway 192.168.101.1

ifconfig gives this:

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.101.157  netmask 255.255.255.0  broadcast 192.168.101.255
        ether b8:27:eb:f7:8b:63  txqueuelen 1000  (Ethernet)
        RX packets 5720867  bytes 1721066581 (1.6 GiB)
        RX errors 0  dropped 1783005  overruns 0  frame 0
        TX packets 461693  bytes 46638663 (44.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Thanks!
