### ISSUE TITLE
results are totally wrong ?!?!?

### ISSUE THREAD

**Issue by roe1974** [sivel/speedtest-cli#550]
i am using speedtest-cli since about 2 month and i am very happy with that ;-)

But since about 1 week the results are totally wrong. I run it on a Synology NAS (But i also tried it on a raspi P3B+) .... i have an internet connection of 300MBit down/30MBit up .... (as shown on speedtest.net on Windows) .... But since one week, i get results with speedtest-cli from 20MBit down / 1,5 Mbit up for example....
Was anything changed on the test Servers ?

please help, ragards Richard

**Comment by kennedyshead** [comment]
Same for me :/
