### ISSUE TITLE
Upload results are wrong. Is it a unit pb. or else ?

### ISSUE THREAD

**Issue by MantaRayDeeJay** [sivel/speedtest-cli#552]
I have an ADSL cnx with usually 6Mb/s DN and 1Mb/s UP.
For several days I have some cnx troubleshooting. My download bandwith is actually about 1,1Mb/s (DN) and estimated between 10 and 100kb/s only (UP). Speedtest Websites can't check upload bandwith and generate sometimes some error.
I'm using speedtest-cli since today to check my bandwith and if the detected download bandwith seems to be right (about 1,2Mb/s), the upload bandwith is totally wrong (about 1,87Mb/s)
I'm asking if it could be a wrong unit : 1,87Kb/s instead 1,87MB/s.
or an other bug
or my faulty cnx which could be at the origin of generating a bad result.

**Comment by William04A** [comment]
Well, many people use this tool, so I´m pretty sure that this isn´t a unit problem. I don´t think that @sivel will move forward with this issue as stated in the readme.md:
`Issues relating to inconsistencies will be closed as wontfix and without additional reason or context.`

If you want more information about why you may get inconsistent results, that is in the readme.md as well.
And if somebody for some reason wants to move forward with solving this, could you perhaps specify what error you get from the "Speedtest Websites" sometimes? speedtest-cli are based on Speedtest.net, and if their website gives you an error, speedtest-cli won´t work either. And with an upload speed this low, inconsistent results aren´t really that surprising. At least not for me.

**Comment by Delawen** [comment]
On my case, I get like ten times less speed on speedtest-cli than in the speedtest.net website. I thought it may be an issue with the server, but trying with other servers, the result is the same.

![imagen](https://user-images.githubusercontent.com/726590/61453714-32284d00-a95f-11e9-84ec-a8ac4e9561c7.png)

```
$ speedtest-cli 
Retrieving speedtest.net configuration...
Testing from XXXXX (XXXXX)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by XXXXXX [XXXXX]: 26.219 ms
Testing download speed................................................................................
Download: 46.45 Mbit/s
Testing upload speed......................................................................................................
Upload: 3.80 Mbit/s
```
```
$ speedtest-cli --exclude XXXXX  --no-pre-allocate
Retrieving speedtest.net configuration...
Testing from XXXXX (XXXXX)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by XXXXX (XXXX) [XXXXXX]: 26.112 ms
Testing download speed................................................................................
Download: 43.17 Mbit/s
Testing upload speed......................................................................................................
Upload: 3.73 Mbit/s
```

**Comment by dirk12345ger** [comment]
Same problem here. ADSL connection with 90 mbit down / 35 mbit up.

speedtest-cli 90 mbit down / 3,5 mbit up
Tried several servers, result of upload speed is always too slow.
