### ISSUE TITLE
Error 407: Proxy

### ISSUE THREAD

**Issue by danniiffxi** [sivel/speedtest-cli#556]
Hey guys, any idea how to fix this? I am unable to bypass the proxy on the server I am using as it is needed for other Synthetic Transaction I have configured. 

Cannot retrieve speedtest configuration
ERROR: HTTP Error 407: Proxy Authentication Required

**Comment by sivel** [comment]
You will need to set `http_proxy` and `https_proxy` env vars so that include the user:password in the env vars.

This application provides no way to configure the proxy directly, and relies on native python means of doing so.

```
export http_proxy=https://user:password@proxy:8080
export https_proxy=$http_proxy
```
