### ISSUE TITLE
About Error Messages

### ISSUE THREAD

**Issue by LBYPatrick** [sivel/speedtest-cli#558]
I am thinking about integrating this thing to my [Shadowsocks Manager Project](https://github.com/LBYPatrick/YAMATO), so...

I know what a success output from your program looks like, then:

- What message would be prompted when **timeout** ?
- What message would be prompted when **the internet is simply unavailable**?

This may help me a lot. Thank you.

**Comment by sivel** [comment]
All errors should start with `ERROR`. They will also result in a non-zero exit code, and they will be printed to stderr instead of stdout.
