### ISSUE TITLE
CSV DL/UL Value

### ISSUE THREAD

**Issue by NitaroF** [sivel/speedtest-cli#560]
Hello,

i use speedtest-cli with the --csv flag and i have a quastion.
I get the following result:
`Server ID,Sponsor,Server Name,Timestamp,Distance,Ping,Download,Upload,Share,IP Address
5733,LWLcom GmbH,Bremen,2018-12-13T23:00:05.373302Z,196.3797013567676,140.945,31269154.93681974,9877670.922662351,,XX.XX.XX`

So, this here "31269154.93681974" is the Download result. But what value is it ? Its seperatet by a dot so it cant be the bit/s result or am i wrong ? It seems that these are two results. 
Can anyone explain that ?

**Comment by sivel** [comment]
The value is bits/s.
