### ISSUE TITLE
Fatal Error detected with import speedtest and pyinstaller -noconsole

### ISSUE THREAD

**Issue by CodyDeGhetto** [sivel/speedtest-cli#562]
I am looking into this but I am not sure where the issue lies yet.

When freezing a script with PyInstaller 3.5.dev0+e29c04727, the compiled exe fails to run at "import speedtest"

![image](https://user-images.githubusercontent.com/19859958/50302109-f87d7b00-043d-11e9-8598-7c5c5998e444.png)

**Comment by CodyDeGhetto** [comment]
I have narrowed it down to lines 170 and 171 in speedtest.py:
        _py3_utf8_stdout = _Py3Utf8Output(sys.stdout)
        _py3_utf8_stderr = _Py3Utf8Output(sys.stderr)

If I comment out the try:except lines 169:174 and only use lines 175:176 the issue is resolved.
    _py3_utf8_stdout = sys.stdout
    _py3_utf8_stderr = sys.stderr

I have also verfified I can still run a speedtest with python 3.6.

**Comment by sivel** [comment]
I'd have to guess that for whatever reason the `except OSError` doesn't catch whatever exception is raised when running from pyinstaller.

FWIW, I could not duplicate this issue.  The executable was created and runs fine, but I'm also not running from Windows.

You could try changing that to `except Exception as e:` and then `print(type(e))` to determine what exception is happening for you at that point.

With that, I might be willing to catch the additional exception.

In fact, I might just be ok with `except Exception:` there anyway.

**Comment by CodyDeGhetto** [comment]
I only run into the issue when using -noconsole. With a visible cmd prompt it works just fine. 

And here is the error:
'log' object has no attribute 'fileno'
<class 'AttributeError'>

**Comment by CodyDeGhetto** [comment]
So I just found this issue is exclusive to me as I was overriding stdout with a class that did not include the fileno attribute.

I will close this issue. Thanks again for your help.

**Comment by LeNarvalo** [comment]
@CodyDeGhetto
> If I comment out the try:except lines 169:174 and only use lines 175:176 the issue is resolved.
> _py3_utf8_stdout = sys.stdout
> _py3_utf8_stderr = sys.stderr


Thx a lot !!! I was looking for an issue for 4h !!!
