### ISSUE TITLE
When measuring speeds above 2Gbps

### ISSUE THREAD

**Issue by nsa2006** [sivel/speedtest-cli#564]
Testing download speed................................................................................
Download: 4281.54 Mbit/s
Testing upload speed................................................................................................
Upload: 949.79 Mbit/s

 http://www.speedtest.net/result/0.png

Why such a link?

**Comment by jtl999** [comment]
I believe it's a serverside limitation of speedtest.net website

**Comment by sivel** [comment]
Duplicate of https://github.com/sivel/speedtest-cli/issues/241
