### ISSUE TITLE
Speedtest-cli reports 0.00 mbit throughput and 1800000.0 ms ping

### ISSUE THREAD

**Issue by stephendt** [sivel/speedtest-cli#567]
As per the title, I appear to be having issues with speedtest-cli (version 2.0.2) at the moment. Not sure when this began, but it did work a few months ago. This is my output when allowing speedtest-cli to select a server automatically:

```
owner@Linux-PC:~$ speedtest-cli
Retrieving speedtest.net configuration...
Testing from Optus (49.197.60.111)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by AARNet (Brisbane) [16.26 km]: 1800000.0 ms
Testing download speed................................................................................
Download: 0.00 Mbit/s
Testing upload speed......................................................................................................
Upload: 0.00 Mbit/s
```

I proceeded to try several servers and most of them would output similar results to the above (for example, 2604, which is a Telstra server in Brisbane), but a couple of servers did work normally. This is output I get from a Sunshine Coast server, which looks normal:

```
owner@Linux-PC:~$ speedtest-cli --server 10443
Retrieving speedtest.net configuration...
Testing from Optus (49.197.60.111)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by Optus (Sunshine Coast) [199.10 km]: 77.834 ms
Testing download speed................................................................................
Download: 29.58 Mbit/s
Testing upload speed......................................................................................................
Upload: 3.01 Mbit/s

```

I gather it has something to do with changes to the speedtest.net servers? If I go to speedtest.net in the browser I am able to connect and do speed tests with these servers normally.

**Comment by sivel** [comment]
`1800000.0 ms` indicates that no server could be tested for latency.  As such, I am guessing there is some issue with your network setup that is preventing access to the 5 closest servers (or potentially more).

Also, note that the browser based test uses a pure socket implementation, instead of http/https.
