### ISSUE TITLE
List in reverse

### ISSUE THREAD

**Issue by radonrose** [sivel/speedtest-cli#570]
Perhaps displaying of the list of servers should be shorted in reverse order by distance. This makes the servers closest to the client visible without scrolling up or putting in extra text in the command (appending to a file, show only first ten lines, etc), thus making the shortest command the easiest one to use.

**Comment by sivel** [comment]
I've thought about this, and even implemented a new argument called `--list-reverse`, but in the end I have decided against adding it.

It's actually shorter to just do `speedtest --list|head`
