### ISSUE TITLE
[Feature Request] Single & Multiple connections

### ISSUE THREAD

**Issue by cybersteel8** [sivel/speedtest-cli#571]
I have noticed a feature on Ookla's Speedtest.net website that would be a brilliant feature to include in this project: Single-/Multi-connection mode.

From the website:
> Multi connection mode will show your maximum potential speed by using multiple streams in parallel.

> Single connection mode is best for testing over a VPN or simulating a single file download.

I am not sure what speedtest-cli is using currently, nor which method was used by the website prior to this feature's introduction.

**Comment by sivel** [comment]
This has been implemented in the devel branch in the commit referenced above.
