### ISSUE TITLE
Combine --simple and --json switches

### ISSUE THREAD

**Issue by aheath70** [sivel/speedtest-cli#578]
Would be great if these switches could be used in combination. Currently, if you use --simple, it ignores the --json. 

Ideally, the resultant JSON would look like 
```
{
	"download": 103017507.03373872,
	"timestamp": "2019-02-26T09:47:52.611619Z",
	"ping": 22.423,
	"upload": 5045209.7586044
}
```

**Comment by sivel** [comment]
I'm going to decline such a feature.  It shouldn't matter. JSON shouldn't be used for human consumption, and machines don't care about extra keys.
