### ISSUE TITLE
Automatically select the closest server

### ISSUE THREAD

**Issue by amjad** [sivel/speedtest-cli#581]
How can I automatically specify the closest server? Without any parameters, its choosing random servers.

**Comment by sivel** [comment]
There is often no single closest server.  I have 5 that are equidistant.  As such, the way this application works is to select the 5 closest servers, and then perform a latency test against each one to find the closest server with the lowest latency, and then that server is used for testing.

There is no automatic way to select the closest server.  You would need to use `--list` and pick a server manually.
