### ISSUE TITLE
urlopen error [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by dinoRkz** [sivel/speedtest-cli#594]
The IP address of the host A is 192.168.0.80 [Fedora29 on Laptop]
The IP address of the host B is 192.168.0.136 [Ubuntu minimal on OdroidXU4 single board computer]

Both the hosts are connected to the same router. I want to test the upload and download speeds between both the hosts. I tried speedtest source and the error is shown below. @sivel could you please help me out to resolve this error. Thanks. 

`[username@host Proj]$ speedtest-cli --source 192.168.0.136`
`Retrieving speedtest.net configuration...`
`Cannot retrieve speedtest configuration`
`ERROR: <urlopen error [Errno 99] Cannot assign requested address>`

**Comment by dinoRkz** [comment]
I tried testing using https://raw.githubusercontent.com/sivel/speedtest-cli/devel/speedtest.py and the output is the same.

[username@host Proj]$ python speedtest.py --source 192.168.0.136
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: <urlopen error [Errno 99] Cannot assign requested address>

**Comment by sivel** [comment]
`--source` is what IP address to bind to locally.  For example, it is useful for a host that has 2 interfaces.

It does not enable you to test the speed between 2 hosts.
