### ISSUE TITLE
bit/s in CSV unrealistic

### ISSUE THREAD

**Issue by AnderCrafter** [sivel/speedtest-cli#597]
Hello, i am running speedtest-cli as a Cronjob, the csv output i am saving via >> is unrealistic, i get a lot of gigabits, althought i have a 100Mbps downstream only. How shall i calculate this?

**Comment by sivel** [comment]
The value in the CSV is bit/s. And based on the calculation that speedtest.net uses, to get Mbit/s, you would use:

`value / 1000 / 1000`
