### ISSUE TITLE
0.0 Mbit/s ???

### ISSUE THREAD

**Issue by azimut2000** [sivel/speedtest-cli#600]
Hello

Since some days (?), i have a problem with speedtest-cli : my version is the latest (2.1.1 and Python 2.7.15)... It return me 0.0 Mbit/s whatever server number i choose... exept for one !!! 
Here is what i get : 

```
thierry@pine64:~$ speedtest-cli --server 16232
Retrieving speedtest.net configuration...
Testing from Orange (90.3.32.xxx)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by Fibragglo (Forbach) [322.65 km]: 1800000.0 ms
Testing download speed................................................................................
Download: 0.00 Mbit/s
Testing upload speed................................................................................................
Upload: 0.00 Mbit/s
thierry@pine64:~$ speedtest-cli --server 10443
Retrieving speedtest.net configuration...
Testing from Orange (90.3.32.xxx)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by Optus (Sunshine Coast) [16380.94 km]: 330.864 ms
Testing download speed................................................................................
Download: 5.30 Mbit/s
Testing upload speed................................................................................................
Upload: 4.62 Mbit/s
```

Have you an idea why we can have this problem ? I've search on Internet and other issue, but i do not find a solution :-( 

Thank's again for your work, it's a famous application.

Thierry

**Comment by sivel** [comment]
The reason is cryptically buried in the output:

```
Hosted by Fibragglo (Forbach) [322.65 km]: 1800000.0 ms
```

This line indicates that you are unable to communicate with that server.  The value there is derived from the default value used for listing a timeout of 3600s.

I have plans to further improve this output, to make this more clear in the future.

I don't know why you are unable to communicate with that server, that would be something outside of the control of this application.

**Comment by NoSubstitute** [comment]
Ubuntu 2.0.0-1 version also gives wrong upload speed, 1.67 Mbits/s. Both with and without manually selecting servers, regardless of which server is chosen.

Using the 2,1,2 python version works perfectly, 8-900 Mbits/s.
