### ISSUE TITLE
On 5th Mar 2019, my reported upload speed went from consistent 20Mbs to consistent 3Mbs, but speedtest.net (and others) still show 20Mbs

### ISSUE THREAD

**Issue by DanTup** [sivel/speedtest-cli#601]
I know this sounds like an ISP issue, but hear me out :-)

I have speedtests running on two raspberry pi every hour logging to files, and also home-assistant logging speeds (which uses speedtest-cli). My results have been completely consistent forever, at around 80Mbs down and 20Mbs up (which is exactly what my router shows I'm connected as - it's a Fibre ADSL line, I'm close to the cabinet).

<img width="266" alt="Screenshot 2019-05-19 at 10 43 07" src="https://user-images.githubusercontent.com/1078012/57980389-fd614d80-7a22-11e9-8eea-9e179664158d.png">

On 5th March, my reported upstream dropped to 3Mbs in my speedtest-cli logs - yet my router shows still connected at 20Mbs and if I go to speedtest.net or perform an upload to something like Google drive, this seems accurate.

It wasn't just a blip, it just changed and has been that way forever since:

<img width="276" alt="Screenshot 2019-05-19 at 10 45 01" src="https://user-images.githubusercontent.com/1078012/57980431-91331980-7a23-11e9-82b4-5b02d368291c.png">

I'm wondering whether anything may have changed in speedtest.net that could cause speedtest-cli to be logging the results incorrectly?

**Comment by dbartelmus** [comment]
Same. 1.66mbit upload
