### ISSUE TITLE
Just cannot work in mac Terminal.

### ISSUE THREAD

**Issue by proxyBug** [sivel/speedtest-cli#602]
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>

Is this because I have a ip shell?

what can i do?

**Comment by sivel** [comment]
This error indicates that the version of openssl that your python was compiled against cannot support the SSL requirements of the speedtest.net servers.  You will need to look at upgrading to a newer version of macOS, or look into compiling a new python install against a more recent version.
