### ISSUE TITLE
ubuntu 18.04 with bbr , upload rate 4.1Mbits

### ISSUE THREAD

**Issue by yelban** [sivel/speedtest-cli#605]
ubuntu 16.04 w/o bbr
get Upload: 542.13 Mbit/s
from linode tokyo datacenter to 19256) Love4Taylor (Tokyo, Japan) [12.55 km]

ubuntu 18.04 w/ bbr
always get Upload: `4.17 Mbit/s`
all test node in Tokyo got 4.x Mbit/s exclude `21569) i3D.net (Tokyo, Japan) [0.96 km]`

speedtest-cli --server 11703
> Upload: 4.10 Mbit/s

speedtest-cli --server 24333
> Upload: 4.16 Mbit/s

same issue with Taiwan nodes in Taiwan

speedtest-cli --server 2595
> Upload: 4.10 Mbit/s

**Comment by sivel** [comment]
Sounds like a problem with bbr.  I have no plans at all to look into this issue.  Feel free to troubleshoot yourself.  If you find a bug in speedtest-cli that can be resolved via code, feel free to submit a PR.

**Comment by iRomanyshyn** [comment]
Today I got exactly the same problem. It measures only 4.16 Mbits/sec when uploading. Speedtest's website works well though.

**Comment by billstephens** [comment]
Same on Macbook Pro today:  Should be ~100Mbps

`Testing download speed................................................................................
Download: 28.46 Mbit/s
Testing upload speed......................................................................................................
Upload: 3.91 Mbit/s`
