### ISSUE TITLE
Proxy compatibility seems broken

### ISSUE THREAD

**Issue by lbsou** [sivel/speedtest-cli#610]
Hi!

Problem : I'm unable to get speedtest-cli to work behing a proxy.

Here's what I did :

### Proxy variable declaration : 
```
export http_proxy=http://10.1.1.1:8080
export https_proxy=http://10.1.1.1:8080
```

### Speedtest-cli give an error :
```
[root@perfsonar speedtest-cli]# speedtest-cli
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:618)>
```

### Validate that the proxy settings are in the speedtest-cli environement :

``` 
speedtest-cli &
pgrep speedtest-cli
cat /proc/`pgrep speedtest-cli`/environ
```

**http_proxy=http://10.120.138.22:8080**rootMAIL=/var/spool/mail/lbsoullierePATH=/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/binPWD=/home/lbsoulliere/speedtest-cliDJANGO_SETTINGS_MODULE=esmond.settingsLANG=en_US.UTF-8**https_proxy=http://10.120.138.22:8080**

### Packet capture to make sure the proxy is used :
tcpdump -i eno1 -s 0 -w spdt.pcap

![image](https://user-images.githubusercontent.com/30626084/60128229-22528a00-9760-11e9-8124-c4814c9cca58.png)

What is happening here is that speedtest-cli try to fetch the file via http but get the anser "moved permanently". Then, it try to fetch via https (Wireshark is not able to decode this https call) and the proxy return : **bad request**

### If I try to download this web page with wget :
![image](https://user-images.githubusercontent.com/30626084/60124358-655c2f80-9757-11e9-877e-ae7bf4549b4d.png)

OK

### Tried with older version

I tried v1.0.7 and it is working but it does not support multiple connection. (I think?) and I need to do testing on a satellite link (LFN)

Starting from version 2.0.0, the proxy compatibility seems to be broken.

I made sure that the speedtest works without proxy. 
 
Everything was tested on :

Two different client : CentOS 7.6.1810 and Ubuntu 18.04.2
Two different proxy : PFSense 2.4.4 and Fortinet v?
Python 2.7.5

Thanks!

Louis-B

**Comment by lbsou** [comment]
Anyone?

**Comment by lbsou** [comment]
@sivel ?

**Comment by sivel** [comment]
Feel free to see if this branch fixes your issues:

https://raw.githubusercontent.com/sivel/speedtest-cli/proxy-fixes/speedtest.py

**Comment by lbsou** [comment]
Hi Matt,

It does work now.

```
root:~# echo $http_proxy  $https_proxy
http://10.x.x.x:8080
http://10.x.x.x:8080
```

```
root:~# python speedtest.py
Retrieving speedtest.net configuration...
Testing from ACME (142.x.x.x)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Sogetel (Nicolet, QC) [1350.51 km]: 1800000.0 ms
Testing download speed................................................................................
Download: 4.54 Mbit/s
Testing upload speed................................................................................................
Upload: 7.52 Mbit/s
```

```
root:~# python speedtest.py --version
speedtest-cli 2.1.2a
Python 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```


Thanks!

**Comment by New2Python** [comment]
Hi, 
I have the same issue on my Windows 10 OS laptop where on few networks i see the upload and download speed, but on some networks i see the error

Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration

I am using python 3.7.3 and Speedtest version 2.1.1. 

i tried using the code from 
https://raw.githubusercontent.com/sivel/speedtest-cli/proxy-fixes/speedtest.py which resulted in the same error.

Any help on this will be really helpful. :)

Thanks.
