### ISSUE TITLE
Inconsistent speeds: RESOLVED

### ISSUE THREAD

**Issue by Zachucks** [sivel/speedtest-cli#612]
Just wanted to let everyone know that I found a resolution to actual inconsistent speeds (NOT PING/LATENCY).

I ran this program on 3 different devices and 3 different versions of python3:
[Aries] (RaspberryPi 3 Model B+): Python3 Version = Python 3.4.2 --> Runs perfect speedtests with correct results (Correct Download, Correct Upload)
[Taurus] (RaspberryPi 3 Model B+): Python3 Version = Python 3.7.3 --> Runs imperfect speedtests with incorrect results (Correct Download, Max ~3Mbps Upload)
[Leo] (Ubuntu Custom Machine): Python3 Version = Python 3.6.8 --> Runs imperfect speedtests with incorrect results (Correct-ish Download, Max ~3Mbps Upload)

I also ran it with my two WSL machines, one at home and one at work, and they both report incorrect speeds (one on python3 3.5.2 and one on python3 3.6.8).

I then went to attempt to research the issue and notably found that different python versions can report different results.

I attempted to uninstall and reinstall the program with no luck, and attempted upgrading my python3 version also with no luck.

Finally, I somehow (I forget how I found it, probably when I was reinstalling it) found the path of the program (/usr/lib/python3/dist-packages/speedtest.py) and forced it to just use python (2.7.15rc1) and it worked!

Command: python /usr/lib/python3/dist-packages/speedtest.py

**Comment by nonissue** [comment]
Haha, it's funny that this makes a difference. But you're right, I'm able to reproduce the original issue, and then your resolution on my server (upload jumps from 4mb/s to 400mb/s)
