### ISSUE TITLE
SSL Certificate Error with Python3.6

### ISSUE THREAD

**Issue by BrockSmedley** [sivel/speedtest-cli#621]
```
  File "main.py", line 21, in <module>
    main()
  File "main.py", line 15, in main
    result = testSpeed()
  File "main.py", line 5, in testSpeed
    s = speedtest.Speedtest()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/speedtest.py", line 1053, in __init__
    self.get_config()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/speedtest.py", line 1085, in get_config
    raise ConfigRetrievalError(e)
speedtest.ConfigRetrievalError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed (_ssl.c:749)>
```

**Comment by wormuths** [comment]
I too am having issues with Speedtest on the Home Assistant platform related to certificates.  They are all loosely related, but between all the different configuration possibilities, it all comes down to certificate issues between Speedtest, Python, and your chosen platform.

We really need to sort this out...

**Comment by sivel** [comment]
This indicates that the ca cert bundle that your python is using does not have the correct ca certs to validate the SSL certificate used by speedtest.net.

In newer versions of Python you should able to find the path used for CA certs using the following:

```
$ python -c 'import ssl; print(ssl.get_default_verify_paths())'
DefaultVerifyPaths(cafile='/usr/local/etc/openssl/cert.pem', capath='/usr/local/etc/openssl/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/usr/local/etc/openssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/usr/local/etc/openssl/certs')
```

That is an example from my system.

Once you have that, you will need to find out how to update that ca cert bundle for your OS.  On Linux it is usually solved by installing or updating a `ca-certificates` package.

In a future version speedtest-cli will offer you a way to ignore invalid certs, but my recommendation is to get your ca bundle updated.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
