### ISSUE TITLE
--single option is not working

### ISSUE THREAD

**Issue by KevinLapagna** [sivel/speedtest-cli#628]
The ```--single``` option is not working correctly. I still see multiple TCP connections at once. So when disabling _window scaling_, speedtest-cli gives unrealistic high values.
(```sysctl -w net.ipv4.tcp_window_scaling=0```)

I tested a server with a RTT of 3.757 ms and had a downlad speed of 557.26 Mbit/s. Mathematically, with a window size of max 64KB and and RTT of 3.757, I should reach at best 139.55 Mbit/sec in a single TCP connection.
This number is suspiciously near to a quarter of the displayed speed - and I have 4 cores.

Can it be, that ```--single``` limits the test to one connection _per core_?

**Comment by sivel** [comment]
Can you test the following branch and see if it resolves your issues?

https://raw.githubusercontent.com/sivel/speedtest-cli/thread-limiter/speedtest.py

**Comment by KevinLapagna** [comment]
> Can you test the following branch and see if it resolves your issues?

Yes, it does. Thanks!
