### ISSUE TITLE
--source parameter doesn't work on Synology

### ISSUE THREAD

**Issue by error401de** [sivel/speedtest-cli#630]
Hi again,
just tried the --source parameter, I get this error without any more information:

```
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: <urlopen error timed out>
```

Can anybody help?

//EDIT: Additional info: It does work over a VPN interface, it does not work on regular eth0

**Comment by sivel** [comment]
This indicates that the interface you are trying to test does not have routes installed that enable it to properly communicate with an external network.
