### ISSUE TITLE
--share doesnt work with speeds over ~5000mbit/s

### ISSUE THREAD

**Issue by Trustmega** [sivel/speedtest-cli#632]
With speeds over something around 5000mbit/s download the image link is https://speedtest.net/result/0.png 

Could be related to the speed, could be something else but when i test several times on the same server the only time i get a 0.png is with upload and download speeds over 5000mbit/s

**Comment by sivel** [comment]
Duplicate of https://github.com/sivel/speedtest-cli/issues/241
