### ISSUE TITLE
This is throwing 5xx

### ISSUE THREAD

**Issue by bhatguru** [sivel/speedtest-cli#635]
Earlier it was working perfectly fine, i have been using this for quite long, but today it started throwing 5XX for me, any help will be appreciated.

```Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: HTTP Error 500: Service Unavailable```

**Comment by ploedman** [comment]
I had that issues too, but now it works again.

**Comment by bhatguru** [comment]
Let me check now...

**Comment by bhatguru** [comment]
Now It is working, thanks for letting me know @ploedman

**Comment by sivel** [comment]
Yeah, not really anything I can do here. speedtest.net is ran by Ookla, and this project isn't. If their service gives a 500, it's likely just some transient issue on their side.

**Comment by bhatguru** [comment]
Yes, may be possible, any how thaks.
