### ISSUE TITLE
Seems like slow DNS resolution provides slow results

### ISSUE THREAD

**Issue by RobinLabadie** [sivel/speedtest-cli#638]
Hello,

Using latest speedtest-cli from today.

I had a network speed issues on a server. I thought it looked like DNS resolution resolution delay, but first, I tried a speedtest-cli, showing aweful speeds (around 3mbps for about 100 expected). So I ditched the DNS resolution hypothesis.

After 20 minutes or fiddling around, I tried changing the DNS which were pretty bad ones, and suddently all issues were resolved. -even the speedtest bandwidth test-

Conclusion: It seems like the speetest-cli test doesn't handle the case where DNS resolution is slow, and I would also think that the DNS resolution delay is included in the overall upload and download speedtest which in my opinion, should not be.

The issue might be hard to reproduce (getting slow DNS servers isn't easy...), but I would suggest reviewing the code with in mind that the DNS resolution time shouldn't be part of the speed result. Fix might be pretty easy.

Maybe I'm not right about how it works currently, I just wanted to let you know this, just in case. I remain available if I can help on this one. (I know Bash, and I got sysadmin knowlege, if it can be any use).

Best regards

**Comment by sivel** [comment]
Python has no DNS caching capabilities.  I recommend setting up some form of local caching mechanism to avoid such issues.

**Comment by RobinLabadie** [comment]
This is likely not about caching DNS, but rather about finding a way to run the test once the DNS resolution has been made. For example, the script could start counting after the first byte of data has been received or sent. This would increase the reliability of the test, and prevent penalizing bandwidth measures when the ping (or DNS resolution) has a high value.
