### ISSUE TITLE
Speedtest.net just released an official CLI client, installs to /usr/bin/speedtest

### ISSUE THREAD

**Issue by Strykar** [sivel/speedtest-cli#663]
The just released Ookla Speedtest binary also installs to `/usr/bin/speedtest` and thus conflicts with `speedtest-cli`. Any chance of renaming your binary in future releases?

1. https://www.reddit.com/r/HomeNetworking/comments/dpalqu/speedtestnet_just_launched_an_official_c_cli/
2. https://aur.archlinux.org/packages/ookla-speedtest-bin

**Comment by sivel** [comment]
No
