### ISSUE TITLE
Possible to use Fast.com instead of speedtest.net?

### ISSUE THREAD

**Issue by Quinncuatro** [sivel/speedtest-cli#667]
I remember reading somewhere that half the reason Netflix built fast.com was so that they could host it at Netflix. Most ISP's don't have an incentive to give fast on demand traffic to Netflix (just due to the sheer amount of data) like they do to sites like speedtest.net.

Using fast.com would be a more accurate representation of your actual bandwidth.

**Comment by sivel** [comment]
Nope. That is out of scope. This tool is explicitly for testing against Speedtest.net.
