### ISSUE TITLE
Can i change the python version speedtest-cli used?

### ISSUE THREAD

**Issue by NBSOD** [sivel/speedtest-cli#669]
Recently, i found some network servers use speedtest-cli can't get a right result,so i think the reason might be the different python version.So can i set a python for my speedtest-cli ?
Just like i have python2 and 3,but default the speedtest-cli use python3.5.3, i want use python 2.7

**Comment by philshem** [comment]
you can use the curl method and specify which python version in the command line

    curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python2.7 -

otherwise, clone and build from your own source

    python2.7 setup.py install

**Comment by sivel** [comment]
Closing per above
