### ISSUE TITLE
It can not run in centos 8

### ISSUE THREAD

**Issue by A-nameless-geek** [sivel/speedtest-cli#671]
![image](https://user-images.githubusercontent.com/37324193/69033681-76655000-0a1a-11ea-97b2-819287cf0c9a.png)
**python version 2.7.17**

**Comment by sivel** [comment]
How did you install Python?  It appears as though you have not installed python in a way that it has SSL/HTTPS support.

**Comment by A-nameless-geek** [comment]
I download the packages in  python.org 
and i compile the package in my vps

**Comment by sivel** [comment]
Ok, in any case, they are compile wrong.  I'd recommend installing python via dnf on CentOS 8.
