### ISSUE TITLE
Armbian Buster (Linux rock64 4.4.192-rockchip64 ) "speedtest-cli" package outputs incorrect results

### ISSUE THREAD

**Issue by Matei-Ciobotaru** [sivel/speedtest-cli#672]
Hi,

First off, thanks for putting in the time to develop this handy tool!

I recently noticed some discrepancies between the "speedtest-cli" results when installed using the "apt" package manager vs running the script itself.

I noticed that when using [Armbian Buster](https://www.armbian.com/rock64/) OS on a Rock64 ARM processor based single board computer where "speedtest-cli' was installed via the apt package manager the tool very different results (lower values) when compared to running the [speedtest-cli.py](https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py) script using Python 2.7.15.

The repository and package version used to install "speedtest-cli":

`speedtest-cli/bionic,bionic,now 2.0.0-1 all [installed]`

Example:

```
localhost:~$ speedtest-cli 
Retrieving speedtest.net configuration...
Testing from ISP_CENSURED (IP_CENSURED)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by ISP_CENSURED: 4.866 ms
Testing download speed................................................................................
Download: 233.49 Mbit/s
Testing upload speed......................................................................................................
Upload: 4.08 Mbit/s
localhost:~$ curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
Retrieving speedtest.net configuration...
Testing from ISP_CENSURED (IP_CENSURED)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by ISP_CENSURED [6.90 km]: 5.145 ms
Testing download speed................................................................................
Download: 468.78 Mbit/s
Testing upload speed................................................................................................
Upload: 272.79 Mbit/s
localhost:~$
```

I have also tested this on Raspbian Buster and Fedora Workstation 31 and no such discrepancies were noticed.

Regards,

**Comment by sivel** [comment]
I do not maintain, package, or have direct communication with the debian package maintainers for speedtest-cli.

An issue will need to be filed with the maintainers of the OS package.
