### ISSUE TITLE
Cannot retrieve speedtest configuration

### ISSUE THREAD

**Issue by Phosphorus31** [sivel/speedtest-cli#673]
When running `speedtest-cli` from the terminal it gives an error:
```
% speedtest-cli
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
```
Current version:
```
% speedtest-cli --version
speedtest-cli 2.1.2
Python 2.7.16 (v2.7.16:413a49145e, Mar  2 2019, 14:32:10) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
```
Installed with `brew install speedtest-cli`

**Comment by laudatioUno** [comment]
Same here.
Error appeared since 23th nov 3pm.

# ./speedtest.py 
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: <urlopen error [Errno -2] Name or service not known>
# ./speedtest.py --version
speedtest-cli 2.1.2
Python 2.7.17 (default, Oct 21 2019, 17:20:57) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]

**Comment by laudatioUno** [comment]
> Same here.
> Error appeared since 23th nov 3pm.
> 
> # ./speedtest.py
> Retrieving speedtest.net configuration...
> Cannot retrieve speedtest configuration
> ERROR: <urlopen error [Errno -2] Name or service not known>
> 
> # ./speedtest.py --version
> speedtest-cli 2.1.2
> Python 2.7.17 (default, Oct 21 2019, 17:20:57) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]

Update: Yesterday I disabled ipv6 on my router for test-pourposes. So my server is acting over ipv6 in the local network. So as I activete ipv6 on my router again, all worked fine again ;->

**Comment by Phosphorus31** [comment]
> When running `speedtest-cli` from the terminal it gives an error:
> 
> ```
> % speedtest-cli
> Retrieving speedtest.net configuration...
> Cannot retrieve speedtest configuration
> ERROR: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
> ```
> 
> Current version:
> 
> ```
> % speedtest-cli --version
> speedtest-cli 2.1.2
> Python 2.7.16 (v2.7.16:413a49145e, Mar  2 2019, 14:32:10) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
> ```
> 
> Installed with `brew install speedtest-cli`

Update: I have updated by python version from 2.7.16 to 2.7.17 and now it appears to be working again. Current version:
```
% speedtest-cli --version
speedtest-cli 2.1.2
Python 2.7.17 (default, Oct 24 2019, 12:57:38) [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)]
```
