### ISSUE TITLE
Slow speed compare to desktop client

### ISSUE THREAD

**Issue by buscseik** [sivel/speedtest-cli#674]
![speedtest](https://user-images.githubusercontent.com/20754053/69680377-9ba13080-10a2-11ea-8568-19d9b0757501.png)

Speedtest cli can achive onlyu about 40% less than the desktop client.

**Comment by Tr1pke** [comment]
upload is 3,7 while on the desktop is almost 40...

**Comment by buscseik** [comment]
My one is 2.1.2 on Windows

**Comment by Tr1pke** [comment]
Debian 10
