### ISSUE TITLE
JSON output structure ?

### ISSUE THREAD

**Issue by DaveJCollier** [sivel/speedtest-cli#681]
Hi all,
Can someone explain why the structure of the JSON output differs when I execute speedtest-cli --json multiple times ?

[run2.txt](https://github.com/sivel/speedtest-cli/files/3944890/run2.txt)
[run3.txt](https://github.com/sivel/speedtest-cli/files/3944891/run3.txt)
[run1.txt](https://github.com/sivel/speedtest-cli/files/3944892/run1.txt)

I'm starting to doubt my own eyes but I could have sworn that "Jitter" was returned when I first executed it.

Is it because different speedtest servers support different metrics ?

**Comment by sivel** [comment]
The structure of all three of those txt files are identical. Except that you tested against a different server in run2 that also included a url2 (which isn't used by this app).

**Comment by DaveJCollier** [comment]
No problem, I'll find an alternative.
