### ISSUE TITLE
Cannot retrieve speedtest configuration 

### ISSUE THREAD

**Issue by Azat868** [sivel/speedtest-cli#682]
Hey. I'm trying to measure speed using zabbix. 
`UserParameter=Speed.download,/usr/bin/speedtest-cli --simple --no-upload`
Everything works in the terminal.
```
/home/pi# sudo -u zabbix zabbix_agentd -t Speed.download
Speed.download                                [t|Ping: 49.175 ms
Download: 24.62 Mbit/s
Upload: 0.00 Mbit/s]
```

 Add to zabbix, writes an error. Tell me, what does this error mean?
```
Cannot retrieve speedtest configuration
ERROR: <urlopen error [Errno -3] Temporary failure in name resolution>
```

**Comment by sivel** [comment]
According to the output, DNS resolution failed.
