### ISSUE TITLE
[Feature Request] Support to list nearest servers

### ISSUE THREAD

**Issue by PeterDaveHello** [sivel/speedtest-cli#684]
speedtest-cli is awesome and very helpful, I'd like to contribute where I can, but sorry that I'm not a Python developer, so just fire an issue here first, and will dig deeper to see if I have a chance to send a pull request to implement it. 
(if the suggestion is accepted, of course)

Speedtest released official command line tool recently: https://www.speedtest.net/apps/cli

There is a parameter very useful to me: `-L, --servers  List nearest servers`, and below is its output:

```
$ speedtest -L
Closest servers:

    ID  Name                           Location             Country
==============================================================================
 14623  IPA CyberLab                   Bunkyo               Japan
 15047  OPEN Project (via 20G SINET)   Tokyo                Japan
 20976  GLBB Japan                     Tokyo                Japan
 24333  Rakuten Mobile , Inc           Tokyo                Japan
 28910  fdcservers.net                 Tokyo                Japan
 21569  i3D.net                        Tokyo                Japan
 18516  GIAM PING VIETPN.COM           Tokyo                Japan
 24537  ymsr.cloud                     Yamato               Japan
  8407  Allied Telesis Capital Corporation Sagamihara           Japan
  6087  Allied Telesis Capital Corporation Fussa-shi            Japan
```

As the test results various, sometimes the range is very wide, depends on the routes, ISPs and peering, Internet exchange bandwidth, I'd like to run the tests with some manually specified near servers, originally I have to list all the servers and filter the near ones, with this feature it can be 10x times easy to find out the servers I'm looking for. So I wonder if this feature can also be added in this original speedtest-cli project?

Many thanks.

I'd also like to share the test output of the official command line tool as reference here, for those who wants to take a quick look:
```
$ speedtest

   Speedtest by Ookla

     Server: IPA CyberLab - Bunkyo (id = 14623)
        ISP: Microsoft Corporation
    Latency:     1.68 ms   (0.33 ms jitter)
   Download:  2930.94 Mbps (data used: 3.4 GB)                               
     Upload:   926.58 Mbps (data used: 418.4 MB)                               
Packet Loss:     0.0%
 Result URL: https://www.speedtest.net/result/c/635b228f-5fbd-4dc6-bf6e-16aaeb63a861
```

**Comment by sivel** [comment]
This already exists, however the `--list` outputs all servers, ordered by distance.  just pipe it to `head`

```
$ speedtest-cli --list | head
```

**Comment by PeterDaveHello** [comment]
Oh okay, just wondered if I can do it without a pipe/redirection :)
