### ISSUE TITLE
certificate verify failed (_ssl.c:727)>

### ISSUE THREAD

**Issue by PkWhaley** [sivel/speedtest-cli#690]
Installed to MacOS 10.14.16 with Home-brew.
```
$ speedtest-cli
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
```
```
$ speedtest-cli --version
speedtest-cli 2.1.2
Python 2.7.16 (v2.7.16:413a49145e, Mar  2 2019, 14:32:10) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
```

**Comment by sivel** [comment]
I don't recommend using python from homebrew, as it doesn't use the same certificate store as the system python.

As such, I think you need to install `openssl` from homebrew to get the ca cert bundle.  In any case, this is a system configuration issue, and not a speedtest-cli issue.
