### ISSUE TITLE
Adding 3 new features for this program

### ISSUE THREAD

**Issue by ammk1996** [sivel/speedtest-cli#700]
Hi, I'm interested to add 3 new features for this program. :) :)
1. Make a GUI for this program
2. Inside GUI, add start speed test button instead of starting speed test directly when you run the program & add pop up message to let user know when the speed test is finished
3. Save the result data on a text format file within same directory of speedtest.py

**Comment by rakibulhaque84** [comment]
I already did this

**Comment by sivel** [comment]
I have no plans of implementing 1 and 2 here.  3 can roughly be done by just piping the output to a file.
