### ISSUE TITLE
Request for the use of speedtest-cli project for my school project

### ISSUE THREAD

**Issue by jagadeeshwar831** [sivel/speedtest-cli#701]
Hi, I am Jagadeeshwar Ankathi, a bachelor Student, and I would like to work with your project for my Module Assignment.

**Comment by runninggamesstudios** [comment]
Dude, you should probably do 5 minutes of reading before asking a stupid question.

If you paid attention, you'd notice this is released under the Apache license version 2.0 

I'd rather you Google it from here but fuck it, it basically means yes, you can...

**Comment by BigBobDalton** [comment]
LOL 👍
