### ISSUE TITLE
Very slow upload

### ISSUE THREAD

**Issue by pladaria** [sivel/speedtest-cli#702]
I'm getting very strange results
```
$ speedtest-cli
Retrieving speedtest.net configuration...
Testing from Telefonica de Espana Static IP (88.27.129.234)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by ServiHosting Networks (Madrid) [16.00 km]: 4.434 ms
Testing download speed................................................................................
Download: 621.67 Mbit/s
Testing upload speed......................................................................................................
Upload: 4.16 Mbit/s
```
Using web based speed tests, I get 600 Mbps upload

This happens both in my desktop and laptop computers (using linux), but surprisingly on a raspberry pi4 I get 600/600.

All tests using ethernet cable connected directly to the router

I see there were similar issues in the past and closed without any solution. 

The readme says:
```
Issues relating to inconsistencies will be closed as wontfix and without additional 
reason or context
```
But I think this is worth to investigate

**Comment by pladaria** [comment]
I've removed the package installed from apt (using latest linux mint) and installed using:
`wget -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py`

This time I get:
```
$ ./speedtest-cli 
Retrieving speedtest.net configuration...
Testing from Telefonica de Espana Static IP (88.27.129.234)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by ServiHosting Networks (Madrid) [16.00 km]: 4.535 ms
Testing download speed................................................................................
Download: 622.00 Mbit/s
Testing upload speed................................................................................................
Upload: 606.33 Mbit/s
```
I don't know why the apt package performs so bad, performs a note in README warning about this would be useful

**Comment by notDavid** [comment]
@pladaria i think the issue is related to https://github.com/sivel/speedtest-cli#inconsistency

Anyways fyi, use [SpeedTest++](https://github.com/taganaka/SpeedTest) and you will get correct results...
