### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Lyr3x** [sivel/speedtest-cli#708]
Since i updated OpenSSL to version 1.1.1b the speedtest-cli is not working anymore

`Cannot retrieve speedtest configuration
ERROR: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>`

**Comment by sivel** [comment]
This is something between openssl and python. Not this script.

**Comment by Lyr3x** [comment]
May u give me a hint?
