### ISSUE TITLE
slow/missing DNS server has huge effect on results

### ISSUE THREAD

**Issue by idallen** [sivel/speedtest-cli#711]
If I add a non-existent DNS `nameserver` to the top of `/etc/resolv.conf` (e.g. 192.168.8.254), the resulting DNS slowness has a huge effect on the download/upload speeds.  I read that other people found the same DNS problems (#638, #381, #117) over the past five years.  I would hope that the script could be modified to do the DNS lookups first, before the timing loop, so that the server URLs would use IP addresses instead of host names and not require any DNS lookup?  The [Ookla CLI client](https://www.speedtest.net/apps/cli) doesn't have this problem.

Here's a (correct) result without the bogus DNS server:

`# bin/speedtest-cli_2.1.2 --server 16610      `                                                                             
`Download: 47.15 Mbit/s       `                                                                                             
`Upload: 11.53 Mbit/s`

I add the bogus DNS server to the top of `/etc/resolv.conf` and things go very wrong:
                                                        
`# bin/speedtest-cli_2.1.2 --server 16610     `                                                                                 
`Download: 2.17 Mbit/s        `                                                                                             
`Upload: 2.51 Mbit/s `

The reason I found this, is that I have two Internet connections from two providers, with two DNS `nameserver` lines in my `/etc/resolv.conf` file, and the first provider went down last night and caused the `speedtest` results from the other provider to go wrong.  DNS look-up delays should not be part of the output results.

**Comment by sivel** [comment]
I have no intention of trying to implement DNS caching.
