### ISSUE TITLE
Custom Remote Host

### ISSUE THREAD

**Issue by sp7412** [sivel/speedtest-cli#713]
I have a remote linux server that I access using open vpn. Is there a way to specify a custom host? I'm trying to do a upload/download speed test from my machine to the remote server when I'm connected using open vpn.

**Comment by sivel** [comment]
The remote host would have to be running the ookla speedtest server.

**Comment by sarahbx** [comment]
@sivel are there any other requirements for this? Currently testing this out as well.

**Comment by sarahbx** [comment]
I should include I'm doing this on a private network.

**Comment by sp7412** [comment]
I don't have the ability to install the ookla speedtest server on the remote host.
