### ISSUE TITLE
CSV Output Issue - Server Name Comma

### ISSUE THREAD

**Issue by bix6** [sivel/speedtest-cli#714]
Hello! Thanks for making this :D

*Server Name* includes a comma like **"Trantor, CA"** which splits that data in two when using `column` in bash. 

Would you consider using **"Trantor CA"** instead?

**Comment by sivel** [comment]
The CSV output is properly quoted, please make sure you are using a CSV parser, and not blindly splitting on commas.  Otherwise, consider switching to `--json` and use `jq` to parse the data from bash.
