### ISSUE TITLE
Downlink speed is way off

### ISSUE THREAD

**Issue by dceee** [sivel/speedtest-cli#716]
I am a bit puzzled by the results for the downlink. Download tests with wget range up to 1Gbps whereas speedtest-cli hardly reports anything above 10Mbit/s. The uplink seems reasonable though.
This machine is connected over a cat6 connection. 
A laptop running same kernel, same python version and same speedtest-cli reports way more accurate results. What could be the culprit here?

**Comment by Hades32** [comment]
Similar here. On a Pine64 (arm64) I measure >900MBit/s down and >40MBit/s up with the [official speedtest-cli](https://www.speedtest.net/de/apps/cli) - which is pretty much what my line is capable of.
But with this lib (and inside Docker) I can't seem to get more than ~280MBit/s down...

**Comment by Hades32** [comment]
@sivel would you mind explaining the close? I searched the open issues and there is no duplicate. Also my test was both times with the same official speedtest.net servers and therefore should be reproducible...

**Comment by michaelkolber** [comment]
Read the bottom of the README...

**Comment by Hades32** [comment]
Well, it's your library, so whatever you say. But:
* it's not about latency
* it's not a little inconsistent it's a factor of nearly 400% (!) wrong

FYI for other coming after me: The official speedtest.net CLI has a `--format=json` option. So probably better to just execute this and use the output...

**Comment by garypaduana** [comment]
I found success with the official client. https://www.speedtest.net/apps/cli

This sivel/speedtest-cli app wasted many hours of my time as it produces incorrect results.

**Comment by dceee** [comment]
I can confirm this. My results for download are are:

official ookla cli: 896 Mbps
speedtest-cli: 17 Mbps
