### ISSUE TITLE
Bad location?

### ISSUE THREAD

**Issue by DevUrbi** [sivel/speedtest-cli#720]
I think it's not choosing correctly my location.
I live in San Sebastian(North of spain) and it chooses San sebastian de la gomera. More than [2000km](https://www.google.com/maps/place/San+Sebasti%C3%A1n+de+La+Gomera,+Santa+Cruz+de+Tenerife/@36.9574134,-4.2623295,5.5z/data=!4m5!3m4!1s0xc6ae577932a7697:0xd509e0e4aaed3149!8m2!3d28.0937998!4d-17.1098582).
And when list the servers it starts from here.
is it searching by name??
Thank you.

**Comment by sivel** [comment]
This tool just uses the data provided by speedtest.net.  It sorts all of the servers based on geographic location, closest to where your IP address is reported to be in use.

Either your IP is being reported to be used in the wrong location, or there is some other inconsistency in the data provided by speedtest.net. In either case, I don't control the data sources.
