### ISSUE TITLE
--list seems to be incomplete

### ISSUE THREAD

**Issue by car-gli** [sivel/speedtest-cli#722]
Hi, I'm testing Servers in Germany, so I made me a list of servers only from Germany, but the since some times, I don't know exactly how long I get errors, "No matched servers: ID". I know that the list can change, therefore I wanted to recreate my list, but the command give me no Servers from Germany anymore, Is there a change or is ther another possibility to get an updated list?

**Comment by sivel** [comment]
Duplicate of https://github.com/sivel/speedtest-cli/issues/717
