### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by RyanGuyCode** [sivel/speedtest-cli#723]
My server has outbound access to the internet, however, when I run speedtest, I get no data. Do you have a way to troubleshoot this or recommendations?

 speedtest-cli
Retrieving speedtest.net configuration...
Testing from Suddenlink Communications (47.x.x.x)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Education Service Center, Region 13 (Austin, TX) [24.09 km]: 1800000.0 ms
Testing download speed................................................................................
Download: 0.00 Mbit/s
Testing upload speed................................................................................................
Upload: 0.00 Mbit/s

**Comment by Comaxim** [comment]
try:
`speedtest-cli --server 16089`

As indicated by the latency, there might be some issues at Education Service Center, Region 13 (Austin, TX).

**Comment by RyanGuyCode** [comment]
Very odd...I get the same, when I point to UT, Austin, and when I run the list, I get no response.

omv5:/# speedtest --server 16089            
Retrieving speedtest.net configuration...
Testing from Suddenlink Communications (47.222.229.142)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by University of Texas, Austin (Austin, TX) [24.09 km]: 1800000.0 ms
Testing download speed................................................................................
Download: 0.00 Mbit/s
Testing upload speed................................................................................................
Upload: 0.00 Mbit/s

omv5:/# speedtest-cli --list | less
-bash: speedtest-cli: command not found

**Comment by Comaxim** [comment]
Sorry that I find out this script is `Selecting best server based on ping...`, so with the high latency server output. 
It means that all the servers close to you are the same with high latency.
It will be difficult to find a usable server.

By the way, you need to change command to ```speedtest --list | less```  because your execuatable name is ```speedtest```.
If this failed like ```less: command not found```, your may try installing ```less``` with your package manager such as ```apt install less``` and try again.
This helps choose servers but may be not useful in your case. Perhaps servers located in other state work.

As for recommendations, [official CLI](https://www.speedtest.net/apps/cli#download) is available if you do not mind.

**Comment by Comaxim** [comment]
https://github.com/sivel/speedtest-cli/blob/c58ad3367bf27f4b4a4d5b1bca29ebd574731c5d/speedtest.py#L1472-L1486

the 1800000.0 ms is calculated that all three latency tests failed.
And something preventing speedtest can be infered from the 0.00 Mbit/s speed.

If you really need to test the line speed, other ways are available, such as wgeting some linux isos from closest mirror or testing from web browsers with alternatives like [Netflix Fast](https://fast.com/).

**Comment by Comaxim** [comment]
Similar previous [issues](https://github.com/sivel/speedtest-cli/issues?q=0.00) exist.
maybe firewall, maybe ISP.

**Comment by RyanMilton** [comment]
I can do this from my desktop...I will see about the official. What are firewall requirements at server? I can validate that, but it shouldn't be an issue.

**Comment by sivel** [comment]
Many speedtest.net HTTP server implementations operate on TCP port 8080.

If you are getting `1800000.0ms` that indicates that you cannot communicate with the test server.

The server configurations can be seen in http://c.speedtest.net/speedtest-servers-static.php

**Comment by RyanGuyCode** [comment]
I found a rule that blocked outbound 8080.
