### ISSUE TITLE
Always shows wrong upload speeds

### ISSUE THREAD

**Issue by fuxoft** [sivel/speedtest-cli#724]
While visiting the speedtest.net website with my Chrome browser shows the correct speeds for my network (around 100 mbps for both upload and download). However, when I run "speedtest-cli" on the same computer, it always shows upload speed around mere 4 mbps (between 3.9 and 4.1 mbps, to be precise). The upload speed is shown correctly. This is speedtest-cli 2.0.0. included in Ubuntu Linux.

**Comment by abdulocracy** [comment]
I'm experiencing the same issue, was this fixed?

**Comment by fuxoft** [comment]
> I'm experiencing the same issue, was this fixed?

You have to manually download the latest version, that one is fixed.
