### ISSUE TITLE
CSV header explanation

### ISSUE THREAD

**Issue by adrian1906** [sivel/speedtest-cli#725]
`speedtest --format=csv --output-header` produced this header:

"server name","server id","latency","jitter","packet loss","download","upload","download bytes","upload bytes","share url"
"i3D.net - Ashburn, VA","21542","19.083","0.5","0","10204795","5793680","94691176","79544133","https://www.speedtest.net/result/c/ef277162-9b29-4ac1-b00b-46b4c9c75221"

What is the difference between "download"/ "download bytes" and "upload"/"upload bytes"?

download:  "10204795"
download bytes: "94691176"

upload: "5793680"
upload bytes: "79544133"

Note:  These values registered as  Download: 81.64 Mbps and Upload: 46.35 Mbps on the share URL

**Comment by sivel** [comment]
The tool you indicate is not the one provided by this repository.
