### ISSUE TITLE
Cannot retrieve speedtest configuration ERROR: <urlopen error [Errno -2] Name or service not known>

### ISSUE THREAD

**Issue by t3chbg** [sivel/speedtest-cli#727]
Hi im having a problem running the speedtest-cli. Getting the following error:
Cannot retrieve speedtest configuration
ERROR: <urlopen error [Errno -2] Name or service not known>

Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-1062.12.1.el7.x86_64
Architecture: x86-64

speedtest-cli --version
speedtest-cli 2.1.2
Python 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

wget https://speedtest.net
--2020-04-25 20:22:45--  https://speedtest.net/
Resolving speedtest.net (speedtest.net)... 151.101.194.219, 151.101.2.219, 151.101.130.219, ...
Connecting to speedtest.net (speedtest.net)|151.101.194.219|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.speedtest.net/ [following]
--2020-04-25 20:22:45--  https://www.speedtest.net/
Resolving www.speedtest.net (www.speedtest.net)... 151.101.2.219, 151.101.66.219, 151.101.130.219, ...
Connecting to www.speedtest.net (www.speedtest.net)|151.101.2.219|:443... connected.
HTTP request sent, awaiting response... 200 OK

**Comment by Comaxim** [comment]
Try `--secure` .

**Comment by t3chbg** [comment]
Thanks that worked.

Regards
Brendan Gilbert

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
