### ISSUE TITLE
What port is used?

### ISSUE THREAD

**Issue by ShaiMagal** [sivel/speedtest-cli#734]
Hello,

what port is used for testing via speedtest-cli?

I am using firewall and if is enabled, speedtest-cli is not working.

If I disable firewall, it starts work again.

So, what port I have to put on whitelist at my firewall settings?

Thank you for reply.

**Comment by Comaxim** [comment]
Mostly dst port 8080.

**Comment by ShaiMagal** [comment]
> Mostly dst port 8080.

Hello,

thank you for reply, I added port 8080 to whitelist (TCP incoming+outgoing), and working well.

Fixed, thank you!
