### ISSUE TITLE
Bump supported Python3 version to Python 3.8

### ISSUE THREAD

**Issue by tellenbach** [sivel/speedtest-cli#747]
Would it be possible to support Python 3.8? This is in particular relevant since the macOS package manager Homebrew defaults Python to 3.8.3 and `speedtest-cli` therefore doesn't work through Homebrew anymore:

```
zsh: /usr/local/bin/speedtest-cli: bad interpreter: /usr/local/opt/python/bin/python3.7: no such file or directory
```

This is somewhat relevant since `speedtest-cli` is downloaded [~3500 x per month](https://formulae.brew.sh/formula/speedtest-cli#default) through Homebrew.

Thanks!

**Comment by hoxovic** [comment]
It supports Python 3.8.x just fine, but the shebang in `$(which speedtest-cli)` is hardcoded at installation time. Thus, this is probably a result of installing speedtest-cli first and then updating Python 3.7 -> 3.8.

**Comment by tellenbach** [comment]
Thanks for your answer. Reinstalling made it work and this can be closed from my side.
