### ISSUE TITLE
Unable to parse server list

### ISSUE THREAD

**Issue by breiter** [sivel/speedtest-cli#86]
```
$ speedtest --list
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Failed to parse list of speedtest.net servers
$ speedtest --version
0.3.0
$ python --version
Python 2.7.8
```

**Comment by jml3on** [comment]
fwiw, server list parsing broke for me today.
was using the head branch for the past month or so with no problem.

using the devel branch, things work again.

**Comment by sivel** [comment]
This is fixed in devel. Release coming soon

**Comment by rasjani** [comment]
The block on the speedtest server side is (currently?) based on UserAgent header sent in by client - devel branch still sends speedtest as useragent ( https://github.com/sivel/speedtest-cli/blob/devel/speedtest_cli.py#L30 ) and thus it won't get the server list.  So, quick fix for those who just *need* to get the cli working, modify that line 30 to what ever user agent that is allowed, for example:

user_agent = 'Mozilla/5.0 (Android; Mobile; rv:30.0) Gecko/30.0 Firefox/30.0'

**Comment by jdsmit60** [comment]
I just got the same error message today. I was able to fix it by changing
uh = urlopen('http://www.speedtest.net/speedtest-servers-static.php')
to
uh = urlopen('https://www.speedtest.net/speedtest-servers-static.php')

I'm not sure why this worked, but it did for me. This was on Raspbian, speedtest-cli version 0.3.1, python version 2.7.9, kernel version 4.4.13+

**Comment by FujiMakoto** [comment]
@jdsmit60 I'm not sure why that works either. I referenced your fix in the issue linked above, which suggests another fix for the bug.

**Comment by cbseven** [comment]
thanks for the hint @jdsmit60 - with this info in hand, I simply changed the value for the global variable 'scheme' from:

scheme = 'http'

to:

scheme = 'https'

and all is working beautifully now.

**Comment by cbseven** [comment]
of course simply running:

speedtest-cli --secure

accomplishes the exact same thing (and works like a charm).
